#define IDS_UI_RESOURCE_TEST 100
#define IDS_UI_RESOURCE_ENGLISH_ONLY 101
#define IDD_UI_RESOURCE_TEST 200
#define IDD_UI_RESOURCE_PAGE_TEST 201
#define IDC_UI_RESOURCE_LABEL 202
#define IDD_UI_RESOURCE_LEGACY_TEST 203
#define IDM_UI_RESOURCE_TEST 300
#define IDM_UI_RESOURCE_COMMAND 301
