//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DotNetTools.rc
//
#define IDD_PROCDOTNETPERF              101
#define IDD_PROCDOTNETASM               102
#define ID_CLR_OPENFILELOCATION         103
#define ID_CLR_OPENNATIVELOCATION       104
#define ID_CLR_COPY                     105
#define ID_CLR_INSPECT                  106
#define ID_CLR_INSPECTNATIVE            107
#define ID_COPY                         108
#define IDS_DN_PERF_GROUP_MEMORY        2000
#define IDS_DN_PERF_GROUP_EXCEPTIONS    2001
#define IDS_DN_PERF_GROUP_INTEROP       2002
#define IDS_DN_PERF_GROUP_JIT           2003
#define IDS_DN_PERF_GROUP_LOADING       2004
#define IDS_DN_PERF_GROUP_LOCKS_AND_THREADS 2005
#define IDS_DN_PERF_GROUP_REMOTING      2006
#define IDS_DN_PERF_GROUP_SECURITY      2007
#define IDS_DN_PERF_ITEM_MEMORY_GENZEROCOLLECTIONS 2008
#define IDS_DN_PERF_ITEM_MEMORY_GENONECOLLECTIONS 2009
#define IDS_DN_PERF_ITEM_MEMORY_GENTWOCOLLECTIONS 2010
#define IDS_DN_PERF_ITEM_MEMORY_PROMOTEDFROMGENZERO 2011
#define IDS_DN_PERF_ITEM_MEMORY_PROMOTEDFROMGENONE 2012
#define IDS_DN_PERF_ITEM_MEMORY_PROMOTEDFINALFROMGENZERO 2013
#define IDS_DN_PERF_ITEM_MEMORY_PROCESSID 2014
#define IDS_DN_PERF_ITEM_MEMORY_GENZEROHEAPSIZE 2015
#define IDS_DN_PERF_ITEM_MEMORY_GENONEHEAPSIZE 2016
#define IDS_DN_PERF_ITEM_MEMORY_GENTWOHEAPSIZE 2017
#define IDS_DN_PERF_ITEM_MEMORY_LOHSIZE 2018
#define IDS_DN_PERF_ITEM_MEMORY_FINALSURVIVORS 2019
#define IDS_DN_PERF_ITEM_MEMORY_GCHANDLES 2020
#define IDS_DN_PERF_ITEM_MEMORY_INDUCEDGC 2021
#define IDS_DN_PERF_ITEM_MEMORY_TIMEINGC 2022
#define IDS_DN_PERF_ITEM_MEMORY_BYTESINALLHEAPS 2023
#define IDS_DN_PERF_ITEM_MEMORY_TOTALCOMMITTED 2024
#define IDS_DN_PERF_ITEM_MEMORY_TOTALRESERVED 2025
#define IDS_DN_PERF_ITEM_MEMORY_TOTALPINNED 2026
#define IDS_DN_PERF_ITEM_MEMORY_TOTALSINKS 2027
#define IDS_DN_PERF_ITEM_MEMORY_TOTALBYTESSINCESTART 2028
#define IDS_DN_PERF_ITEM_MEMORY_TOTALLOHBYTESSINCESTART 2029
#define IDS_DN_PERF_ITEM_MEMORY_GC0PROMOTEDBYTESPERSEC 2030
#define IDS_DN_PERF_ITEM_MEMORY_GC1PROMOTEDBYTESPERSEC 2031
#define IDS_DN_PERF_ITEM_MEMORY_FINALPROMOTEDBYTESPERSEC 2032
#define IDS_DN_PERF_ITEM_MEMORY_ALLOCATEDBYTESPERSEC 2033
#define IDS_DN_PERF_ITEM_EXCEPTIONS_THROWNCOUNT 2034
#define IDS_DN_PERF_ITEM_EXCEPTIONS_FILTERSCOUNT 2035
#define IDS_DN_PERF_ITEM_EXCEPTIONS_FINALLYCOUNT 2036
#define IDS_DN_PERF_ITEM_EXCEPTIONS_THROWNPERSEC 2037
#define IDS_DN_PERF_ITEM_EXCEPTIONS_FILTERSPERSEC 2038
#define IDS_DN_PERF_ITEM_EXCEPTIONS_FINALLYPERSEC 2039
#define IDS_DN_PERF_ITEM_EXCEPTIONS_THROWTOCATCHDEPTHPERSEC 2040
#define IDS_DN_PERF_ITEM_INTEROP_CCWCOUNT 2041
#define IDS_DN_PERF_ITEM_INTEROP_STUBCOUNT 2042
#define IDS_DN_PERF_ITEM_INTEROP_MARSHALCOUNT 2043
#define IDS_DN_PERF_ITEM_INTEROP_TLBIMPORTPERSEC 2044
#define IDS_DN_PERF_ITEM_INTEROP_TLBEXPORTPERSEC 2045
#define IDC_OPTIONS                     1002
#define IDC_COUNTERS                    1003
#define IDC_REFRESH                     1003
#define IDC_LIST                        1005
#define IDC_SEARCHEDIT                  1035

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           2046
#endif
#endif
