#!/usr/bin/env python3

import importlib.util
import json
import pathlib
import re
import unittest
from collections import Counter
from typing import Optional


REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
APP_ROOT = REPO_ROOT / "SystemInformer"
APIS = {"PhAddTreeNewColumn", "PhAddTreeNewColumnEx", "PhAddTreeNewColumnEx2"}

NEW_RESOURCE_DATA = r"""
IDS_PH_TREENEW_APP_ID|3126|App ID|应用 ID
IDS_PH_TREENEW_ARCHITECTURE|3127|Architecture|架构
IDS_PH_TREENEW_ASLR|3128|ASLR|ASLR
IDS_PH_TREENEW_ATTACHED_PID|3129|Attached PID|附加 PID
IDS_PH_TREENEW_ATTACHED_PROCESS|3130|Attached process|附加进程
IDS_PH_TREENEW_ATTACHED_START_KEY|3131|Attached start key|附加启动密钥
IDS_PH_TREENEW_ATTRIBUTES|3132|Attributes|属性
IDS_PH_TREENEW_AUTHENTICATION_PACKAGE|3133|Authentication package|身份验证包
IDS_PH_TREENEW_BASE_ADDRESS|3134|Base address|基址
IDS_PH_TREENEW_BASE_PRIORITY|3135|Base priority|基本优先级
IDS_PH_TREENEW_BASE_PRIORITY_ACTUAL|3136|Base priority (actual)|基本优先级 (实际)
IDS_PH_TREENEW_BINARY_PATH|3137|Binary path|可执行文件路径
IDS_PH_TREENEW_BITS|3138|Bits|位数
IDS_PH_TREENEW_CAPABILITIES|3139|Capabilities|功能
IDS_PH_TREENEW_CATEGORY|3140|Category|类别
IDS_PH_TREENEW_CET|3141|CET|CET
IDS_PH_TREENEW_CF_GUARD|3142|CF Guard|CF 保护
IDS_PH_TREENEW_CODE_PAGE|3143|Code page|代码页
IDS_PH_TREENEW_COM_APARTMENT|3144|COM apartment|COM 单元
IDS_PH_TREENEW_COM_FLAGS|3145|COM flags|COM 标志
IDS_PH_TREENEW_COMMAND_LINE|3146|Command line|命令行
IDS_PH_TREENEW_COMPANY_NAME|3147|Company name|公司名称
IDS_PH_TREENEW_CONTROL_ADDRESS|3148|Control address|控制地址
IDS_PH_TREENEW_CPU_HISTORY|3149|CPU history|CPU 历史
IDS_PH_TREENEW_DEFAULT|3150|Default|默认
IDS_PH_TREENEW_DEP|3151|DEP|DEP
IDS_PH_TREENEW_DESKTOP|3152|Desktop|桌面
IDS_PH_TREENEW_DETAILS|3153|Details|详细信息
IDS_PH_TREENEW_DNS_DOMAIN_NAME|3154|DNS domain name|DNS 域名
IDS_PH_TREENEW_DPI_AWARENESS|3155|DPI awareness|DPI 感知
IDS_PH_TREENEW_DURATION|3156|Duration|持续时间
IDS_PH_TREENEW_ELEVATION|3157|Elevation|提权
IDS_PH_TREENEW_ENCLAVE_BASE_ADDRESS|3158|Enclave base address|Enclave 基址
IDS_PH_TREENEW_ENCLAVE_SIZE|3159|Enclave size|Enclave 大小
IDS_PH_TREENEW_ENCLAVE_TYPE|3160|Enclave type|Enclave 类型
IDS_PH_TREENEW_ENTRY_POINT|3161|Entry point|入口点
IDS_PH_TREENEW_ERROR_CONTROL|3162|Error control|错误控制
IDS_PH_TREENEW_ERROR_MODE|3163|Error mode|错误模式
IDS_PH_TREENEW_EVENT|3164|Event|事件
IDS_PH_TREENEW_EXIT_CODE|3165|Exit code|退出代码
IDS_PH_TREENEW_FAILED_LOGON_ATTEMPTS_SINCE|3166|Failed logon attempts since|失败登录次数 (自上次成功登录)
IDS_PH_TREENEW_FIBER|3167|Fiber|纤程
IDS_PH_TREENEW_FILE_MODIFIED_TIME|3168|File modified time|文件修改时间
IDS_PH_TREENEW_FILE_SHARE_ACCESS|3169|File share access|文件共享访问
IDS_PH_TREENEW_FILE_SIZE|3170|File size|文件大小
IDS_PH_TREENEW_FRAME|3171|Frame|帧
IDS_PH_TREENEW_FRAME_ADDRESS|3172|Frame address|帧地址
IDS_PH_TREENEW_FRAME_DISTANCE|3173|Frame distance|帧距离
IDS_PH_TREENEW_GRANTED_ACCESS_SYMBOLIC|3174|Granted access (symbolic)|已授予访问权限 (符号)
IDS_PH_TREENEW_HANDLE_COUNT|3175|Handle count|句柄数
IDS_PH_TREENEW_HANDLE_VALUE|3176|Handle value|句柄值
IDS_PH_TREENEW_HOME_DIRECTORY|3177|Home directory|主目录
IDS_PH_TREENEW_HOME_DIRECTORY_DRIVE|3178|Home directory drive|主目录驱动器
IDS_PH_TREENEW_HYPER_V_SERVICE|3179|Hyper-V service|Hyper-V 服务
IDS_PH_TREENEW_IO_HISTORY|3180|I/O history|I/O 历史
IDS_PH_TREENEW_IO_OTHER_DELTA|3181|I/O other delta|I/O 其他增量
IDS_PH_TREENEW_IO_READ_OTHER_RATE|3182|I/O read+other rate|I/O 读取+其他速率
IDS_PH_TREENEW_IO_READS_DELTA|3183|I/O reads delta|I/O 读取增量
IDS_PH_TREENEW_IO_TOTAL_RATE|3184|I/O total rate|I/O 总速率
IDS_PH_TREENEW_IO_WRITE_RATE|3185|I/O write rate|I/O 写入速率
IDS_PH_TREENEW_IO_WRITES_DELTA|3186|I/O writes delta|I/O 写入增量
IDS_PH_TREENEW_IDEAL_PROCESSOR|3187|Ideal processor|理想处理器
IDS_PH_TREENEW_IMAGE_COHERENCY|3188|Image coherency|映像一致性
IDS_PH_TREENEW_IMPERSONATION|3189|Impersonation|模拟
IDS_PH_TREENEW_JOB_OBJECT_ID|3190|Job Object ID|作业对象 ID
IDS_PH_TREENEW_KERNEL_CPU_TIME|3191|Kernel CPU time|内核 CPU 时间
IDS_PH_TREENEW_KERNEL_STACK_USAGE|3192|Kernel stack usage|内核堆栈使用量
IDS_PH_TREENEW_KEY_MODIFIED_TIME|3193|Key modified time|注册表项修改时间
IDS_PH_TREENEW_KICKOFF_TIME|3194|Kickoff time|强制注销时间
IDS_PH_TREENEW_LAST_FAILED_LOGON|3195|Last failed logon|上次失败登录
IDS_PH_TREENEW_LAST_STATUS_CODE|3196|Last status code|上次状态代码
IDS_PH_TREENEW_LAST_SUCCESSFUL_LOGON|3197|Last successful logon|上次成功登录
IDS_PH_TREENEW_LAST_SYSTEM_CALL|3198|Last system call|上次系统调用
IDS_PH_TREENEW_LINE_NUMBER|3199|Line number|行号
IDS_PH_TREENEW_LOAD_COUNT|3200|Load count|加载计数
IDS_PH_TREENEW_LOAD_REASON|3201|Load reason|加载原因
IDS_PH_TREENEW_LOAD_TIME|3202|Load time|加载时间
IDS_PH_TREENEW_LOCAL_ADDRESS|3203|Local address|本地地址
IDS_PH_TREENEW_LOCAL_HOSTNAME|3204|Local hostname|本地主机名
IDS_PH_TREENEW_LOCAL_PORT|3205|Local port|本地端口
IDS_PH_TREENEW_LOCKED_WS|3206|Locked WS|锁定 WS
IDS_PH_TREENEW_LOGOFF_TIME|3207|Logoff time|注销时间
IDS_PH_TREENEW_LOGON_DOMAIN|3208|Logon domain|登录域
IDS_PH_TREENEW_LOGON_ID|3209|Logon ID|登录 ID
IDS_PH_TREENEW_LOGON_SERVER|3210|Logon server|登录服务器
IDS_PH_TREENEW_LOGON_TYPE|3211|Logon type|登录类型
IDS_PH_TREENEW_LONGON_SCRIPT|3212|Longon script|登录脚本
IDS_PH_TREENEW_MAXIMUM_WORKING_SET|3213|Maximum working set|最大工作集
IDS_PH_TREENEW_MEMORY_TYPE|3214|Memory type|内存类型
IDS_PH_TREENEW_MINIMUM_WORKING_SET|3215|Minimum working set|最小工作集
IDS_PH_TREENEW_MITIGATION_POLICIES|3216|Mitigation policies|缓解策略
IDS_PH_TREENEW_NAMESPACE|3217|Namespace|命名空间
IDS_PH_TREENEW_NON_PAGED_POOL|3218|Non-paged pool|非分页池
IDS_PH_TREENEW_NONPAGED_SIZE|3219|Nonpaged size|非分页大小
IDS_PH_TREENEW_ORIGINAL_NAME|3220|Original name|原始名称
IDS_PH_TREENEW_ORIGINAL_PAGES|3221|Original pages|原始页面
IDS_PH_TREENEW_ORIGINAL_PROTECTION|3222|Original protection|原始保护
IDS_PH_TREENEW_OS_CONTEXT|3223|OS context|OS 上下文
IDS_PH_TREENEW_PACKAGE_NAME|3224|Package name|包名称
IDS_PH_TREENEW_PAGED_POOL|3225|Paged pool|分页池
IDS_PH_TREENEW_PAGED_SIZE|3226|Paged size|分页大小
IDS_PH_TREENEW_PARENT_BASE_ADDRESS|3227|Parent base address|父级基址
IDS_PH_TREENEW_PARENT_CONSOLE_PID|3228|Parent console PID|父控制台 PID
IDS_PH_TREENEW_PARENT_PID|3229|Parent PID|父 PID
IDS_PH_TREENEW_PASSWORD_CAN_SET|3230|Password can set|密码可修改
IDS_PH_TREENEW_PASSWORD_LAST_SET|3231|Password last set|密码上次设置
IDS_PH_TREENEW_PASSWORD_MUST_SET|3232|Password must set|密码必须修改
IDS_PH_TREENEW_PEAK_NON_PAGED_POOL|3233|Peak non-paged pool|非分页池峰值
IDS_PH_TREENEW_PEAK_PAGED_POOL|3234|Peak paged pool|分页池峰值
IDS_PH_TREENEW_PENDING_IRP|3235|Pending IRP|挂起 IRP
IDS_PH_TREENEW_PID_HEX|3236|PID (Hex)|PID (十六进制)
IDS_PH_TREENEW_PID_LXSS|3237|PID (LXSS)|PID (LXSS)
IDS_PH_TREENEW_POWER_THROTTLING|3238|Power throttling|电源限制
IDS_PH_TREENEW_PRIORITY_SYMBOLIC|3239|Priority (symbolic)|优先级 (符号)
IDS_PH_TREENEW_PRIORITY_BOOST|3240|Priority boost|优先级提升
IDS_PH_TREENEW_PRIORITY_CLASS|3241|Priority class|优先级类
IDS_PH_TREENEW_PRIVATE|3242|Private|专用
IDS_PH_TREENEW_PRIVATE_BYTES_HISTORY|3243|Private bytes history|专用字节历史
IDS_PH_TREENEW_PROCESS_NAME|3244|Process name|进程名称
IDS_PH_TREENEW_PROFILE_PATH|3245|Profile path|配置文件路径
IDS_PH_TREENEW_PROTECTION|3246|Protection|保护
IDS_PH_TREENEW_PROTOCOL|3247|Protocol|协议
IDS_PH_TREENEW_PROVIDER|3248|Provider|提供程序
IDS_PH_TREENEW_REFERENCE_COUNT|3249|Reference count|引用计数
IDS_PH_TREENEW_REGION_TYPE|3250|Region type|区域类型
IDS_PH_TREENEW_RELATIVE_START_TIME|3251|Relative start time|相对启动时间
IDS_PH_TREENEW_REMOTE_ADDRESS|3252|Remote address|远程地址
IDS_PH_TREENEW_REMOTE_HOSTNAME|3253|Remote hostname|远程主机名
IDS_PH_TREENEW_REMOTE_PORT|3254|Remote port|远程端口
IDS_PH_TREENEW_RETURN_ADDRESS|3255|Return address|返回地址
IDS_PH_TREENEW_RPC_USAGE|3256|RPC usage|RPC 使用
IDS_PH_TREENEW_SHORT_USER_NAME|3257|Short user name|短用户名
IDS_PH_TREENEW_SIGNING_LEVEL|3258|Signing level|签名级别
IDS_PH_TREENEW_STACK_ADDRESS|3259|Stack address|堆栈地址
IDS_PH_TREENEW_STACK_PARAMETER_1|3260|Stack parameter #1|堆栈参数 #1
IDS_PH_TREENEW_STACK_PARAMETER_2|3261|Stack parameter #2|堆栈参数 #2
IDS_PH_TREENEW_STACK_PARAMETER_3|3262|Stack parameter #3|堆栈参数 #3
IDS_PH_TREENEW_STACK_PARAMETER_4|3263|Stack parameter #4|堆栈参数 #4
IDS_PH_TREENEW_STACK_USAGE|3264|Stack usage|堆栈使用量
IDS_PH_TREENEW_START_ADDRESS|3265|Start address|起始地址
IDS_PH_TREENEW_START_ADDRESS_NATIVE|3266|Start address (Native)|起始地址 (本机)
IDS_PH_TREENEW_START_ADDRESS_SYMBOLIC|3267|Start address (symbolic)|起始地址 (符号)
IDS_PH_TREENEW_START_ADDRESS_WIN32|3268|Start address (Win32)|起始地址 (Win32)
IDS_PH_TREENEW_START_KEY|3269|Start key|启动密钥
IDS_PH_TREENEW_START_MODULE|3270|Start module|起始模块
IDS_PH_TREENEW_START_TIME|3271|Start time|启动时间
IDS_PH_TREENEW_START_TYPE|3272|Start type|启动类型
IDS_PH_TREENEW_STRING|3273|String|字符串
IDS_PH_TREENEW_SUBPROCESSES|3274|Subprocesses|子进程数
IDS_PH_TREENEW_SUBSYSTEM|3275|Subsystem|子系统
IDS_PH_TREENEW_THREAD_LOCAL_STORAGE|3276|Thread local storage|线程本地存储
IDS_PH_TREENEW_THREAD_NAME|3277|Thread name|线程名称
IDS_PH_TREENEW_TID|3278|TID|TID
IDS_PH_TREENEW_TID_HEX|3279|TID (hex)|TID (十六进制)
IDS_PH_TREENEW_TID_LXSS|3280|TID (LXSS)|TID (LXSS)
IDS_PH_TREENEW_TIME|3281|Time|时间
IDS_PH_TREENEW_TIME_STAMP|3282|Time stamp|时间戳
IDS_PH_TREENEW_TOTAL_CPU_TIME|3283|Total CPU time|总 CPU 时间
IDS_PH_TREENEW_TOTAL_WS|3284|Total WS|总 WS
IDS_PH_TREENEW_USER_CPU_TIME|3285|User CPU time|用户 CPU 时间
IDS_PH_TREENEW_USER_FLAGS|3286|User flags|用户标志
IDS_PH_TREENEW_USER_PRINCIPAL_NAME|3287|User principal name|用户主体名称
IDS_PH_TREENEW_USERNAME|3288|Username|用户名
IDS_PH_TREENEW_VERIFICATION_STATUS|3289|Verification status|验证状态
IDS_PH_TREENEW_VERIFIED_SIGNER|3290|Verified signer|已验证签名者
IDS_PH_TREENEW_VERSION|3291|Version|版本
IDS_PH_TREENEW_VIRTUALIZED|3292|Virtualized|虚拟化
IDS_PH_TREENEW_WAIT_TIME|3293|Wait time|等待时间
IDS_PH_TREENEW_WINDOW_STATUS|3294|Window status|窗口状态
IDS_PH_TREENEW_WINDOW_TITLE|3295|Window title|窗口标题
""".strip()
NEW_RESOURCES = tuple(
    (symbol, int(resource_id), english, chinese)
    for symbol, resource_id, english, chinese in
    (line.split("|", 3) for line in NEW_RESOURCE_DATA.splitlines())
)

REUSED_RESOURCE_DATA = r"""
Address|IDS_PH_LISTVIEW_ADDRESS|地址
Committed|IDS_PH_LISTVIEW_COMMITTED|已提交
Created|IDS_PH_HANDLE_CREATED|创建时间
Critical|IDS_PH_MENU_THREAD_CRITICAL|关键
Description|IDS_PH_LISTVIEW_DESCRIPTION|描述
Display name|IDS_PH_LISTVIEW_DISPLAY_NAME|显示名称
Granted access|IDS_PH_HANDLE_GRANTED_ACCESS|已授予的权限
Group|IDS_PH_HANDLE_SECURITY_GROUP|组
Handle|IDS_PH_LISTVIEW_HANDLE|句柄
Handles|IDS_PH_STAT_HANDLES|句柄
Integrity|IDS_PH_HANDLE_SECURITY_INTEGRITY|完整性
Length|IDS_PH_LISTVIEW_LENGTH|长度
Logon time|IDS_PH_SESSION_LOGON_TIME|登录时间
Name|IDS_PH_TOKEN_NAME|名称
Object address|IDS_PH_HANDLE_OBJECT_ADDRESS|对象地址
Owner|IDS_PH_HANDLE_SECURITY_OWNER|所有者
Package|IDS_PH_GROUP_PACKAGE|程序包
Path|IDS_PH_TOKEN_PATH|路径
Policy|IDS_PH_LISTVIEW_POLICY|策略
Process|IDS_PH_LISTVIEW_PROCESS|进程
References|IDS_PH_GROUP_REFERENCES|引用数
Result|IDS_PH_LISTVIEW_RESULT|结果
Service|IDS_PH_LOGON_SERVICE|服务
Services|IDS_PH_GROUP_SERVICES|服务
Session ID|IDS_PH_SESSION_ID|会话 ID
SID|IDS_PH_TOKEN_SID|SID
Size|IDS_PH_HANDLE_SIZE|大小
State|IDS_PH_SESSION_STATE|状态
Status|IDS_PH_LISTVIEW_STATUS|状态
Symbol|IDS_PH_LISTVIEW_SYMBOL|符号
Threads|IDS_PH_GROUP_THREADS|线程
Type|IDS_PH_TOKEN_TYPE|类型
Use|IDS_PH_LISTVIEW_USE|用途
User|IDS_PH_GROUP_USER|用户
User name|IDS_PH_SESSION_USER_NAME|用户名
""".strip()
REUSED_RESOURCES = {english: (symbol, chinese) for english, symbol, chinese in (line.split("|", 2) for line in REUSED_RESOURCE_DATA.splitlines())}
RESOURCE_BY_ENGLISH = {english: symbol for symbol, _resource_id, english, _chinese in NEW_RESOURCES} | {english: symbol for english, (symbol, _chinese) in REUSED_RESOURCES.items()}

ROUTE_DATA = r"""
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_PROCESS|IDS_PH_LISTVIEW_PROCESS
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_TYPE|IDS_PH_TOKEN_TYPE
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_NAME|IDS_PH_TOKEN_NAME
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_HANDLE|IDS_PH_LISTVIEW_HANDLE
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_OBJECTADDRESS|IDS_PH_HANDLE_OBJECT_ADDRESS
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_ORIGINALNAME|IDS_PH_TREENEW_ORIGINAL_NAME
findobj.c|PhAddTreeNewColumn|PH_OBJECT_SEARCH_TREE_COLUMN_GRANTEDACCESS|IDS_PH_HANDLE_GRANTED_ACCESS
hndllist.c|PhAddTreeNewColumn|PHHNTLC_TYPE|IDS_PH_TOKEN_TYPE
hndllist.c|PhAddTreeNewColumn|PHHNTLC_NAME|IDS_PH_TOKEN_NAME
hndllist.c|PhAddTreeNewColumn|PHHNTLC_GRANTEDACCESSSYMBOLIC|IDS_PH_TREENEW_GRANTED_ACCESS_SYMBOLIC
hndllist.c|PhAddTreeNewColumn|PHHNTLC_HANDLE|IDS_PH_LISTVIEW_HANDLE
hndllist.c|PhAddTreeNewColumn|PHHNTLC_OBJECTADDRESS|IDS_PH_HANDLE_OBJECT_ADDRESS
hndllist.c|PhAddTreeNewColumnEx|PHHNTLC_ATTRIBUTES|IDS_PH_TREENEW_ATTRIBUTES
hndllist.c|PhAddTreeNewColumn|PHHNTLC_GRANTEDACCESS|IDS_PH_HANDLE_GRANTED_ACCESS
hndllist.c|PhAddTreeNewColumn|PHHNTLC_ORIGINALNAME|IDS_PH_TREENEW_ORIGINAL_NAME
hndllist.c|PhAddTreeNewColumnEx|PHHNTLC_FILESHAREACCESS|IDS_PH_TREENEW_FILE_SHARE_ACCESS
hndllist.c|PhAddTreeNewColumn|PHHNTLC_HANDLEVALUE|IDS_PH_TREENEW_HANDLE_VALUE
hndllist.c|PhAddTreeNewColumn|PHHNTLC_HANDLECOUNT|IDS_PH_TREENEW_HANDLE_COUNT
hndllist.c|PhAddTreeNewColumn|PHHNTLC_POINTERCOUNT|IDS_PH_TREENEW_REFERENCE_COUNT
hndllist.c|PhAddTreeNewColumn|PHHNTLC_PAGEDSIZE|IDS_PH_TREENEW_PAGED_SIZE
hndllist.c|PhAddTreeNewColumn|PHHNTLC_NONPAGEDSIZE|IDS_PH_TREENEW_NONPAGED_SIZE
informerwnd.c|PhAddTreeNewColumn|PHIC_TIME|IDS_PH_TREENEW_TIME
informerwnd.c|PhAddTreeNewColumn|PHIC_DURATION|IDS_PH_TREENEW_DURATION
informerwnd.c|PhAddTreeNewColumn|PHIC_PROCESS|IDS_PH_LISTVIEW_PROCESS
informerwnd.c|PhAddTreeNewColumn|PHIC_TID|IDS_PH_TREENEW_TID
informerwnd.c|PhAddTreeNewColumn|PHIC_START_KEY|IDS_PH_TREENEW_START_KEY
informerwnd.c|PhAddTreeNewColumn|PHIC_ATTACHED_PROCESS|IDS_PH_TREENEW_ATTACHED_PROCESS
informerwnd.c|PhAddTreeNewColumn|PHIC_ATTACHED_PID|IDS_PH_TREENEW_ATTACHED_PID
informerwnd.c|PhAddTreeNewColumn|PHIC_ATTACHED_START_KEY|IDS_PH_TREENEW_ATTACHED_START_KEY
informerwnd.c|PhAddTreeNewColumn|PHIC_CATEGORY|IDS_PH_TREENEW_CATEGORY
informerwnd.c|PhAddTreeNewColumn|PHIC_EVENT|IDS_PH_TREENEW_EVENT
informerwnd.c|PhAddTreeNewColumn|PHIC_PATH|IDS_PH_TOKEN_PATH
informerwnd.c|PhAddTreeNewColumn|PHIC_RESULT|IDS_PH_LISTVIEW_RESULT
informerwnd.c|PhAddTreeNewColumn|PHIC_DETAILS|IDS_PH_TREENEW_DETAILS
memlist.c|PhAddTreeNewColumn|PHMMTLC_BASEADDRESS|IDS_PH_TREENEW_BASE_ADDRESS
memlist.c|PhAddTreeNewColumn|PHMMTLC_TYPE|IDS_PH_TOKEN_TYPE
memlist.c|PhAddTreeNewColumnEx|PHMMTLC_SIZE|IDS_PH_HANDLE_SIZE
memlist.c|PhAddTreeNewColumn|PHMMTLC_PROTECTION|IDS_PH_TREENEW_PROTECTION
memlist.c|PhAddTreeNewColumn|PHMMTLC_USE|IDS_PH_LISTVIEW_USE
memlist.c|PhAddTreeNewColumnEx|PHMMTLC_TOTALWS|IDS_PH_TREENEW_TOTAL_WS
memlist.c|PhAddTreeNewColumnEx|PHMMTLC_LOCKEDWS|IDS_PH_TREENEW_LOCKED_WS
memlist.c|PhAddTreeNewColumnEx|PHMMTLC_COMMITTED|IDS_PH_LISTVIEW_COMMITTED
memlist.c|PhAddTreeNewColumnEx|PHMMTLC_PRIVATE|IDS_PH_TREENEW_PRIVATE
memlist.c|PhAddTreeNewColumn|PHMMTLC_SIGNING_LEVEL|IDS_PH_TREENEW_SIGNING_LEVEL
memlist.c|PhAddTreeNewColumn|PHMMTLC_ORIGINAL_PROTECTION|IDS_PH_TREENEW_ORIGINAL_PROTECTION
memlist.c|PhAddTreeNewColumn|PHMMTLC_ORIGINAL_PAGES|IDS_PH_TREENEW_ORIGINAL_PAGES
memlist.c|PhAddTreeNewColumn|PHMMTLC_REGIONTYPE|IDS_PH_TREENEW_REGION_TYPE
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_BASE_ADDRESS|IDS_PH_TREENEW_BASE_ADDRESS
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_ADDRESS|IDS_PH_LISTVIEW_ADDRESS
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_TYPE|IDS_PH_TOKEN_TYPE
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_LENGTH|IDS_PH_LISTVIEW_LENGTH
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_STRING|IDS_PH_TREENEW_STRING
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_PROTECTION|IDS_PH_TREENEW_PROTECTION
memsrcht.c|PhAddTreeNewColumnEx2|PH_MEMSTRINGS_TREE_COLUMN_ITEM_MEMORY_TYPE|IDS_PH_TREENEW_MEMORY_TYPE
miniinfo.c|PhAddTreeNewColumnEx2|MIP_SINGLE_COLUMN_ID|IDS_PH_LISTVIEW_PROCESS
modlist.c|PhAddTreeNewColumn|PHMOTLC_NAME|IDS_PH_TOKEN_NAME
modlist.c|PhAddTreeNewColumn|PHMOTLC_BASEADDRESS|IDS_PH_TREENEW_BASE_ADDRESS
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_SIZE|IDS_PH_HANDLE_SIZE
modlist.c|PhAddTreeNewColumn|PHMOTLC_DESCRIPTION|IDS_PH_LISTVIEW_DESCRIPTION
modlist.c|PhAddTreeNewColumn|PHMOTLC_COMPANYNAME|IDS_PH_TREENEW_COMPANY_NAME
modlist.c|PhAddTreeNewColumn|PHMOTLC_VERSION|IDS_PH_TREENEW_VERSION
modlist.c|PhAddTreeNewColumn|PHMOTLC_TYPE|IDS_PH_TOKEN_TYPE
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_LOADCOUNT|IDS_PH_TREENEW_LOAD_COUNT
modlist.c|PhAddTreeNewColumn|PHMOTLC_VERIFICATIONSTATUS|IDS_PH_TREENEW_VERIFICATION_STATUS
modlist.c|PhAddTreeNewColumn|PHMOTLC_VERIFIEDSIGNER|IDS_PH_TREENEW_VERIFIED_SIGNER
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_ASLR|IDS_PH_TREENEW_ASLR
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_TIMESTAMP|IDS_PH_TREENEW_TIME_STAMP
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_CFGUARD|IDS_PH_TREENEW_CF_GUARD
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_LOADTIME|IDS_PH_TREENEW_LOAD_TIME
modlist.c|PhAddTreeNewColumn|PHMOTLC_LOADREASON|IDS_PH_TREENEW_LOAD_REASON
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_FILEMODIFIEDTIME|IDS_PH_TREENEW_FILE_MODIFIED_TIME
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_FILESIZE|IDS_PH_TREENEW_FILE_SIZE
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_ENTRYPOINT|IDS_PH_TREENEW_ENTRY_POINT
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_PARENTBASEADDRESS|IDS_PH_TREENEW_PARENT_BASE_ADDRESS
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_CET|IDS_PH_TREENEW_CET
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_COHERENCY|IDS_PH_TREENEW_IMAGE_COHERENCY
modlist.c|PhAddTreeNewColumn|PHMOTLC_ORIGINALNAME|IDS_PH_TREENEW_ORIGINAL_NAME
modlist.c|PhAddTreeNewColumn|PHMOTLC_SERVICE|IDS_PH_LOGON_SERVICE
modlist.c|PhAddTreeNewColumn|PHMOTLC_ENCLAVE_TYPE|IDS_PH_TREENEW_ENCLAVE_TYPE
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_ENCLAVE_BASE_ADDRESS|IDS_PH_TREENEW_ENCLAVE_BASE_ADDRESS
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_ENCLAVE_SIZE|IDS_PH_TREENEW_ENCLAVE_SIZE
modlist.c|PhAddTreeNewColumnEx|PHMOTLC_ARCHITECTURE|IDS_PH_TREENEW_ARCHITECTURE
netlist.c|PhAddTreeNewColumn|PHNETLC_PROCESS|IDS_PH_TOKEN_NAME
netlist.c|PhAddTreeNewColumn|PHNETLC_LOCALADDRESS|IDS_PH_TREENEW_LOCAL_ADDRESS
netlist.c|PhAddTreeNewColumn|PHNETLC_LOCALPORT|IDS_PH_TREENEW_LOCAL_PORT
netlist.c|PhAddTreeNewColumn|PHNETLC_REMOTEADDRESS|IDS_PH_TREENEW_REMOTE_ADDRESS
netlist.c|PhAddTreeNewColumn|PHNETLC_REMOTEPORT|IDS_PH_TREENEW_REMOTE_PORT
netlist.c|PhAddTreeNewColumn|PHNETLC_PROTOCOL|IDS_PH_TREENEW_PROTOCOL
netlist.c|PhAddTreeNewColumn|PHNETLC_STATE|IDS_PH_SESSION_STATE
netlist.c|PhAddTreeNewColumn|PHNETLC_OWNER|IDS_PH_HANDLE_SECURITY_OWNER
netlist.c|PhAddTreeNewColumnEx|PHNETLC_TIMESTAMP|IDS_PH_TREENEW_TIME_STAMP
netlist.c|PhAddTreeNewColumn|PHNETLC_LOCALHOSTNAME|IDS_PH_TREENEW_LOCAL_HOSTNAME
netlist.c|PhAddTreeNewColumn|PHNETLC_REMOTEHOSTNAME|IDS_PH_TREENEW_REMOTE_HOSTNAME
netlist.c|PhAddTreeNewColumn|PHNETLC_HV_SERVICE|IDS_PH_TREENEW_HYPER_V_SERVICE
options.c|PhAddTreeNewColumnEx|PH_OPTIONS_ADVANCED_COLUMN_ITEM_NAME|IDS_PH_TOKEN_NAME
options.c|PhAddTreeNewColumnEx|PH_OPTIONS_ADVANCED_COLUMN_ITEM_TYPE|IDS_PH_TOKEN_TYPE
options.c|PhAddTreeNewColumnEx|PH_OPTIONS_ADVANCED_COLUMN_ITEM_DEFAULT|IDS_PH_TREENEW_DEFAULT
options.c|PhAddTreeNewColumnEx|PH_OPTIONS_ADVANCED_COLUMN_ITEM_DESCRIPTION|IDS_PH_LISTVIEW_DESCRIPTION
proctree.c|PhAddTreeNewColumn|PHPRTLC_NAME|IDS_PH_TOKEN_NAME
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IOTOTALRATE|IDS_PH_TREENEW_IO_TOTAL_RATE
proctree.c|PhAddTreeNewColumn|PHPRTLC_USERNAME|IDS_PH_SESSION_USER_NAME
proctree.c|PhAddTreeNewColumn|PHPRTLC_DESCRIPTION|IDS_PH_LISTVIEW_DESCRIPTION
proctree.c|PhAddTreeNewColumn|PHPRTLC_COMPANYNAME|IDS_PH_TREENEW_COMPANY_NAME
proctree.c|PhAddTreeNewColumn|PHPRTLC_VERSION|IDS_PH_TREENEW_VERSION
proctree.c|PhAddTreeNewColumn|PHPRTLC_COMMANDLINE|IDS_PH_TREENEW_COMMAND_LINE
proctree.c|PhAddTreeNewColumn|PHPRTLC_SESSIONID|IDS_PH_SESSION_ID
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PRIORITYCLASS|IDS_PH_TREENEW_PRIORITY_CLASS
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_BASEPRIORITY|IDS_PH_TREENEW_BASE_PRIORITY
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_THREADS|IDS_PH_GROUP_THREADS
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_HANDLES|IDS_PH_STAT_HANDLES
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IORORATE|IDS_PH_TREENEW_IO_READ_OTHER_RATE
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IOWRATE|IDS_PH_TREENEW_IO_WRITE_RATE
proctree.c|PhAddTreeNewColumn|PHPRTLC_INTEGRITY|IDS_PH_HANDLE_SECURITY_INTEGRITY
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_STARTTIME|IDS_PH_TREENEW_START_TIME
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_TOTALCPUTIME|IDS_PH_TREENEW_TOTAL_CPU_TIME
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_KERNELCPUTIME|IDS_PH_TREENEW_KERNEL_CPU_TIME
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_USERCPUTIME|IDS_PH_TREENEW_USER_CPU_TIME
proctree.c|PhAddTreeNewColumn|PHPRTLC_VERIFICATIONSTATUS|IDS_PH_TREENEW_VERIFICATION_STATUS
proctree.c|PhAddTreeNewColumn|PHPRTLC_VERIFIEDSIGNER|IDS_PH_TREENEW_VERIFIED_SIGNER
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_ASLR|IDS_PH_TREENEW_ASLR
proctree.c|PhAddTreeNewColumn|PHPRTLC_RELATIVESTARTTIME|IDS_PH_TREENEW_RELATIVE_START_TIME
proctree.c|PhAddTreeNewColumn|PHPRTLC_BITS|IDS_PH_TREENEW_BITS
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_ELEVATION|IDS_PH_TREENEW_ELEVATION
proctree.c|PhAddTreeNewColumn|PHPRTLC_WINDOWTITLE|IDS_PH_TREENEW_WINDOW_TITLE
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_WINDOWSTATUS|IDS_PH_TREENEW_WINDOW_STATUS
proctree.c|PhAddTreeNewColumnEx2|PHPRTLC_CPUHISTORY|IDS_PH_TREENEW_CPU_HISTORY
proctree.c|PhAddTreeNewColumnEx2|PHPRTLC_PRIVATEBYTESHISTORY|IDS_PH_TREENEW_PRIVATE_BYTES_HISTORY
proctree.c|PhAddTreeNewColumnEx2|PHPRTLC_IOHISTORY|IDS_PH_TREENEW_IO_HISTORY
proctree.c|PhAddTreeNewColumn|PHPRTLC_DEP|IDS_PH_TREENEW_DEP
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_VIRTUALIZED|IDS_PH_TREENEW_VIRTUALIZED
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IOREADSDELTA|IDS_PH_TREENEW_IO_READS_DELTA
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IOWRITESDELTA|IDS_PH_TREENEW_IO_WRITES_DELTA
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IOOTHERDELTA|IDS_PH_TREENEW_IO_OTHER_DELTA
proctree.c|PhAddTreeNewColumn|PHPRTLC_OSCONTEXT|IDS_PH_TREENEW_OS_CONTEXT
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PAGEDPOOL|IDS_PH_TREENEW_PAGED_POOL
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PEAKPAGEDPOOL|IDS_PH_TREENEW_PEAK_PAGED_POOL
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_NONPAGEDPOOL|IDS_PH_TREENEW_NON_PAGED_POOL
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PEAKNONPAGEDPOOL|IDS_PH_TREENEW_PEAK_NON_PAGED_POOL
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_MINIMUMWORKINGSET|IDS_PH_TREENEW_MINIMUM_WORKING_SET
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_MAXIMUMWORKINGSET|IDS_PH_TREENEW_MAXIMUM_WORKING_SET
proctree.c|PhAddTreeNewColumn|PHPRTLC_SUBSYSTEM|IDS_PH_TREENEW_SUBSYSTEM
proctree.c|PhAddTreeNewColumn|PHPRTLC_PACKAGENAME|IDS_PH_TREENEW_PACKAGE_NAME
proctree.c|PhAddTreeNewColumn|PHPRTLC_APPID|IDS_PH_TREENEW_APP_ID
proctree.c|PhAddTreeNewColumn|PHPRTLC_DPIAWARENESS|IDS_PH_TREENEW_DPI_AWARENESS
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_CFGUARD|IDS_PH_TREENEW_CF_GUARD
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_TIMESTAMP|IDS_PH_TREENEW_TIME_STAMP
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_FILEMODIFIEDTIME|IDS_PH_TREENEW_FILE_MODIFIED_TIME
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_FILESIZE|IDS_PH_TREENEW_FILE_SIZE
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_SUBPROCESSCOUNT|IDS_PH_TREENEW_SUBPROCESSES
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_JOBOBJECTID|IDS_PH_TREENEW_JOB_OBJECT_ID
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PROTECTION|IDS_PH_TREENEW_PROTECTION
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_DESKTOP|IDS_PH_TREENEW_DESKTOP
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_CRITICAL|IDS_PH_MENU_THREAD_CRITICAL
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PIDHEX|IDS_PH_TREENEW_PID_HEX
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_CET|IDS_PH_TREENEW_CET
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_IMAGE_COHERENCY|IDS_PH_TREENEW_IMAGE_COHERENCY
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_ERRORMODE|IDS_PH_TREENEW_ERROR_MODE
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_CODEPAGE|IDS_PH_TREENEW_CODE_PAGE
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_POWERTHROTTLING|IDS_PH_TREENEW_POWER_THROTTLING
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_ARCHITECTURE|IDS_PH_TREENEW_ARCHITECTURE
proctree.c|PhAddTreeNewColumn|PHPRTLC_PARENTPID|IDS_PH_TREENEW_PARENT_PID
proctree.c|PhAddTreeNewColumn|PHPRTLC_PARENTCONSOLEPID|IDS_PH_TREENEW_PARENT_CONSOLE_PID
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_PRIORITYBOOST|IDS_PH_TREENEW_PRIORITY_BOOST
proctree.c|PhAddTreeNewColumn|PHPRTLC_GRANTEDACCESS|IDS_PH_TREENEW_GRANTED_ACCESS_SYMBOLIC
proctree.c|PhAddTreeNewColumn|PHPRTLC_TLSBITMAPDELTA|IDS_PH_TREENEW_THREAD_LOCAL_STORAGE
proctree.c|PhAddTreeNewColumnEx|PHPRTLC_REFERENCEDELTA|IDS_PH_GROUP_REFERENCES
proctree.c|PhAddTreeNewColumn|PHPRTLC_LXSSPID|IDS_PH_TREENEW_PID_LXSS
proctree.c|PhAddTreeNewColumn|PHPRTLC_START_KEY|IDS_PH_TREENEW_START_KEY
proctree.c|PhAddTreeNewColumn|PHPRTLC_MITIGATION_POLICIES|IDS_PH_TREENEW_MITIGATION_POLICIES
proctree.c|PhAddTreeNewColumn|PHPRTLC_SERVICES|IDS_PH_GROUP_SERVICES
proctree.c|PhAddTreeNewColumn|PHPRTLC_SHORT_USERNAME|IDS_PH_TREENEW_SHORT_USER_NAME
prpgwmi.c|PhAddTreeNewColumn|PROCESS_WMI_COLUMN_ITEM_PROVIDER|IDS_PH_TREENEW_PROVIDER
prpgwmi.c|PhAddTreeNewColumn|PROCESS_WMI_COLUMN_ITEM_NAMESPACE|IDS_PH_TREENEW_NAMESPACE
prpgwmi.c|PhAddTreeNewColumn|PROCESS_WMI_COLUMN_ITEM_USER|IDS_PH_GROUP_USER
runaspkg.c|PhAddTreeNewColumnEx2|PH_RUNASPACKAGE_TREE_COLUMN_ITEM_NAME|IDS_PH_GROUP_PACKAGE
srvlist.c|PhAddTreeNewColumn|PHSVTLC_NAME|IDS_PH_TOKEN_NAME
srvlist.c|PhAddTreeNewColumn|PHSVTLC_DISPLAYNAME|IDS_PH_LISTVIEW_DISPLAY_NAME
srvlist.c|PhAddTreeNewColumn|PHSVTLC_TYPE|IDS_PH_TOKEN_TYPE
srvlist.c|PhAddTreeNewColumn|PHSVTLC_STATUS|IDS_PH_LISTVIEW_STATUS
srvlist.c|PhAddTreeNewColumn|PHSVTLC_STARTTYPE|IDS_PH_TREENEW_START_TYPE
srvlist.c|PhAddTreeNewColumn|PHSVTLC_BINARYPATH|IDS_PH_TREENEW_BINARY_PATH
srvlist.c|PhAddTreeNewColumn|PHSVTLC_ERRORCONTROL|IDS_PH_TREENEW_ERROR_CONTROL
srvlist.c|PhAddTreeNewColumn|PHSVTLC_GROUP|IDS_PH_HANDLE_SECURITY_GROUP
srvlist.c|PhAddTreeNewColumn|PHSVTLC_DESCRIPTION|IDS_PH_LISTVIEW_DESCRIPTION
srvlist.c|PhAddTreeNewColumnEx|PHSVTLC_KEYMODIFIEDTIME|IDS_PH_TREENEW_KEY_MODIFIED_TIME
srvlist.c|PhAddTreeNewColumn|PHSVTLC_VERIFICATIONSTATUS|IDS_PH_TREENEW_VERIFICATION_STATUS
srvlist.c|PhAddTreeNewColumn|PHSVTLC_VERIFIEDSIGNER|IDS_PH_TREENEW_VERIFIED_SIGNER
srvlist.c|PhAddTreeNewColumn|PHSVTLC_EXITCODE|IDS_PH_TREENEW_EXIT_CODE
srvlist.c|PhAddTreeNewColumn|PHSVTLC_USERNAME|IDS_PH_TREENEW_USERNAME
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_TID|IDS_PH_TREENEW_TID
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_STARTADDRESSWIN32|IDS_PH_TREENEW_START_ADDRESS_WIN32
thrdlist.c|PhAddTreeNewColumnEx|PH_THREAD_TREELIST_COLUMN_PRIORITYSYMBOLIC|IDS_PH_TREENEW_PRIORITY_SYMBOLIC
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_SERVICE|IDS_PH_LOGON_SERVICE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_NAME|IDS_PH_TOKEN_NAME
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_STARTED|IDS_PH_HANDLE_CREATED
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_STARTMODULE|IDS_PH_TREENEW_START_MODULE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_BASEPRIORITY|IDS_PH_TREENEW_BASE_PRIORITY
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_STATE|IDS_PH_SESSION_STATE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_IDEALPROCESSOR|IDS_PH_TREENEW_IDEAL_PROCESSOR
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_CRITICAL|IDS_PH_MENU_THREAD_CRITICAL
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_TIDHEX|IDS_PH_TREENEW_TID_HEX
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_TOKEN_STATE|IDS_PH_TREENEW_IMPERSONATION
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_PENDINGIRP|IDS_PH_TREENEW_PENDING_IRP
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_LASTSYSTEMCALL|IDS_PH_TREENEW_LAST_SYSTEM_CALL
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_LASTSTATUSCODE|IDS_PH_TREENEW_LAST_STATUS_CODE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_APARTMENTTYPE|IDS_PH_TREENEW_COM_APARTMENT
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_APARTMENTFLAGS|IDS_PH_TREENEW_COM_FLAGS
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_FIBER|IDS_PH_TREENEW_FIBER
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_PRIORITYBOOST|IDS_PH_TREENEW_PRIORITY_BOOST
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_STACKUSAGE|IDS_PH_TREENEW_STACK_USAGE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_WAITTIME|IDS_PH_TREENEW_WAIT_TIME
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_LXSSTID|IDS_PH_TREENEW_TID_LXSS
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_POWERTHROTTLING|IDS_PH_TREENEW_POWER_THROTTLING
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_STARTADDRESS|IDS_PH_TREENEW_START_ADDRESS_NATIVE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_KSTACKUSAGE|IDS_PH_TREENEW_KERNEL_STACK_USAGE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_RPC|IDS_PH_TREENEW_RPC_USAGE
thrdlist.c|PhAddTreeNewColumn|PH_THREAD_TREELIST_COLUMN_ACTUALBASEPRIORITY|IDS_PH_TREENEW_BASE_PRIORITY_ACTUAL
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_SYMBOL|IDS_PH_TOKEN_NAME
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_STACKADDRESS|IDS_PH_TREENEW_STACK_ADDRESS
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_FRAMEADDRESS|IDS_PH_TREENEW_FRAME_ADDRESS
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_PARAMETER1|IDS_PH_TREENEW_STACK_PARAMETER_1
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_PARAMETER2|IDS_PH_TREENEW_STACK_PARAMETER_2
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_PARAMETER3|IDS_PH_TREENEW_STACK_PARAMETER_3
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_PARAMETER4|IDS_PH_TREENEW_STACK_PARAMETER_4
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_CONTROLADDRESS|IDS_PH_TREENEW_CONTROL_ADDRESS
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_RETURNADDRESS|IDS_PH_TREENEW_RETURN_ADDRESS
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_LINETEXT|IDS_PH_TREENEW_LINE_NUMBER
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_ARCHITECTURE|IDS_PH_TREENEW_ARCHITECTURE
thrdstk.c|PhAddTreeNewColumn|PH_STACK_TREE_COLUMN_FRAMEDISTANCE|IDS_PH_TREENEW_FRAME_DISTANCE
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_SYMBOL|IDS_PH_LISTVIEW_SYMBOL
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_THREADID|IDS_PH_TREENEW_TID
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_FRAMENUMBER|IDS_PH_TREENEW_FRAME
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_ARCHITECTURE|IDS_PH_TREENEW_ARCHITECTURE
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_STACKADDRESS|IDS_PH_TREENEW_STACK_ADDRESS
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_FRAMEADDRESS|IDS_PH_TREENEW_FRAME_ADDRESS
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_PARAMETER1|IDS_PH_TREENEW_STACK_PARAMETER_1
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_PARAMETER2|IDS_PH_TREENEW_STACK_PARAMETER_2
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_PARAMETER3|IDS_PH_TREENEW_STACK_PARAMETER_3
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_PARAMETER4|IDS_PH_TREENEW_STACK_PARAMETER_4
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_CONTROLADDRESS|IDS_PH_TREENEW_CONTROL_ADDRESS
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_RETURNADDRESS|IDS_PH_TREENEW_RETURN_ADDRESS
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_LINETEXT|IDS_PH_TREENEW_LINE_NUMBER
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_FRAMEDISTANCE|IDS_PH_TREENEW_FRAME_DISTANCE
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_STARTADDRESS|IDS_PH_TREENEW_START_ADDRESS
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_STARTADDRESSSYMBOL|IDS_PH_TREENEW_START_ADDRESS_SYMBOLIC
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_PROCESSNAME|IDS_PH_TREENEW_PROCESS_NAME
thrdstks.c|PhAddTreeNewColumn|PH_THREAD_STACKS_COLUMN_THREADNAME|IDS_PH_TREENEW_THREAD_NAME
tokprp.c|PhAddTreeNewColumnEx2|0|IDS_PH_TREENEW_ATTRIBUTES
tokprp.c|PhAddTreeNewColumnEx2|0|IDS_PH_TREENEW_CAPABILITIES
tokprp.c|PhAddTreeNewColumnEx2|0|IDS_PH_LISTVIEW_POLICY
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_USER_NAME|IDS_PH_SESSION_USER_NAME
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGON_DOMAIN|IDS_PH_TREENEW_LOGON_DOMAIN
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_SESSION_ID|IDS_PH_SESSION_ID
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGON_TYPE|IDS_PH_TREENEW_LOGON_TYPE
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_AUTHENTICATION_PACKAGE|IDS_PH_TREENEW_AUTHENTICATION_PACKAGE
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_DNS_DOMAIN_NAME|IDS_PH_TREENEW_DNS_DOMAIN_NAME
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGON_TIME|IDS_PH_SESSION_LOGON_TIME
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_PASSWORD_LAST_SET|IDS_PH_TREENEW_PASSWORD_LAST_SET
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_SID|IDS_PH_TOKEN_SID
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGON_ID|IDS_PH_TREENEW_LOGON_ID
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGON_SERVER|IDS_PH_TREENEW_LOGON_SERVER
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_USER_PRINCIPAL_NAME|IDS_PH_TREENEW_USER_PRINCIPAL_NAME
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_USER_FLAGS|IDS_PH_TREENEW_USER_FLAGS
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_FAILED_ATTEMPTS_SINCE_LAST_SUCCESSFUL_LOGON|IDS_PH_TREENEW_FAILED_LOGON_ATTEMPTS_SINCE
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LAST_SUCCESSFUL_LOGON|IDS_PH_TREENEW_LAST_SUCCESSFUL_LOGON
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LAST_FAILED_LOGON|IDS_PH_TREENEW_LAST_FAILED_LOGON
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGON_SCRIPT|IDS_PH_TREENEW_LONGON_SCRIPT
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_PROFILE_PATH|IDS_PH_TREENEW_PROFILE_PATH
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_HOME_DIRECTORY|IDS_PH_TREENEW_HOME_DIRECTORY
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_HOME_DIRECTORY_DRIVE|IDS_PH_TREENEW_HOME_DIRECTORY_DRIVE
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_LOGOFF_TIME|IDS_PH_TREENEW_LOGOFF_TIME
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_KICKOFF_TIME|IDS_PH_TREENEW_KICKOFF_TIME
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_PASSWORD_CAN_CHANGE|IDS_PH_TREENEW_PASSWORD_CAN_SET
usrlist.c|PhAddTreeNewColumn|PH_USER_LIST_COLUMN_PASSWORD_MUST_CHANGE|IDS_PH_TREENEW_PASSWORD_MUST_SET
""".strip()
EXPECTED_ROUTES = Counter(tuple(line.split("|", 3)) for line in ROUTE_DATA.splitlines())

RUNTIME_COMPATIBILITY_KEYS = {
    'ASLR',
    'Address',
    'Architecture',
    'Attributes',
    'Base address',
    'Bits',
    'CET',
    'CF Guard',
    'CPU history',
    'Capabilities',
    'Created',
    'Critical',
    'DEP',
    'Default',
    'Description',
    'Desktop',
    'Details',
    'Display name',
    'Entry point',
    'Event',
    'Granted access',
    'Group',
    'Handle',
    'Handles',
    'I/O history',
    'Impersonation',
    'Integrity',
    'Length',
    'Local address',
    'Local hostname',
    'Local port',
    'Logon time',
    'Memory type',
    'Name',
    'Namespace',
    'Object address',
    'Original name',
    'Owner',
    'Package',
    'Path',
    'Policy',
    'Priority class',
    'Private',
    'Process',
    'Protection',
    'Protocol',
    'Provider',
    'Remote address',
    'Remote hostname',
    'Remote port',
    'Result',
    'SID',
    'Service',
    'Services',
    'Session ID',
    'Size',
    'Start time',
    'State',
    'Status',
    'String',
    'Subsystem',
    'Symbol',
    'Threads',
    'Time',
    'Time stamp',
    'Type',
    'Use',
    'User',
    'User name',
    'Username',
    'Version',
    'Virtualized',
}


def load_audit_module():
    path = REPO_ROOT / "tools" / "zhcn" / "audit.py"
    spec = importlib.util.spec_from_file_location("treenew_native_audit", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_stringtable(path: pathlib.Path) -> dict[str, str]:
    return {
        symbol: value.replace('""', '"')
        for symbol, value in re.findall(
            r'(?m)^\s*(IDS_PH_[A-Z0-9_]+)\s+"((?:[^"]|"")*)"\s*$',
            path.read_text(encoding="utf-8-sig"),
        )
    }


class SystemInformerTreeNewNativeResourceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.audit = load_audit_module()

    def collect_routes(self, sources: Optional[dict[str, str]] = None) -> Counter:
        sources = sources or {}
        actual = Counter()
        for file_name in sorted({row[0] for row in EXPECTED_ROUTES}):
            source = sources.get(file_name)
            if source is None:
                source = (APP_ROOT / file_name).read_text(encoding="utf-8-sig")
            source = self.audit.mask_c_comments(source)
            for name, args, _spans, _start in self.audit.find_calls(source, APIS):
                if len(args) < 4:
                    continue
                match = re.fullmatch(r"PhGetApplicationUiString\(\s*(IDS_PH_[A-Z0-9_]+)\s*\)", args[3].strip())
                if match and match.group(1) in set(RESOURCE_BY_ENGLISH.values()):
                    actual[(file_name, name, args[1].strip(), match.group(1))] += 1
        return actual

    def test_all_274_calls_keep_exact_file_api_column_and_resource_routes(self) -> None:
        self.assertEqual(EXPECTED_ROUTES, self.collect_routes())
        self.assertEqual(274, sum(EXPECTED_ROUTES.values()))
        self.assertEqual(18, len({row[0] for row in EXPECTED_ROUTES}))

    def test_route_contract_rejects_resource_swap(self) -> None:
        source = (APP_ROOT / "findobj.c").read_text(encoding="utf-8-sig")
        mutated = source.replace(
            "PhGetApplicationUiString(IDS_PH_LISTVIEW_PROCESS)",
            "PhGetApplicationUiString(IDS_PH_TOKEN_TYPE)",
            1,
        )
        self.assertNotEqual(source, mutated)
        with self.assertRaises(AssertionError):
            self.assertEqual(EXPECTED_ROUTES, self.collect_routes({"findobj.c": mutated}))

    def test_170_resources_are_contiguous_bilingual_and_owned_by_one_layer(self) -> None:
        header = (APP_ROOT / "resource.h").read_text(encoding="utf-8-sig")
        english = parse_stringtable(APP_ROOT / "SystemInformer.rc")
        chinese = parse_stringtable(APP_ROOT / "SystemInformer.zh-cn.rc")
        data = json.loads((REPO_ROOT / "tools" / "zhcn" / "zh-CN.json").read_text(encoding="utf-8"))

        for symbol, resource_id, en, zh in NEW_RESOURCES:
            with self.subTest(symbol=symbol):
                self.assertRegex(header, rf"(?m)^#define\s+{symbol}\s+{resource_id}$")
                self.assertEqual(en, english.get(symbol))
                self.assertEqual(zh, chinese.get(symbol))

        translations = {en: zh for _symbol, _resource_id, en, zh in NEW_RESOURCES}
        translations.update({en: zh for en, (_symbol, zh) in REUSED_RESOURCES.items()})
        for en, zh in translations.items():
            layer = "strings" if en in RUNTIME_COMPATIBILITY_KEYS else "native_strings"
            other = "native_strings" if layer == "strings" else "strings"
            self.assertEqual(zh, data[layer].get(en), en)
            self.assertNotIn(en, data[other], en)

        self.assertRegex(header, r"(?m)^#define IDS_PH_LAST\s+IDS_PH_MENU_COLLAPSE_ALL_PLAIN$")
        self.assertRegex(header, r"(?m)^#define _APS_NEXT_SYMED_VALUE\s+3370$")
        self.assertEqual(1370, len(english))
        self.assertEqual(1370, len(chinese))

    def test_shared_runtime_compatibility_set_is_explicit_and_treenew_hooks_remain(self) -> None:
        source = (REPO_ROOT / "phlib" / "treenew.c").read_text(encoding="utf-8-sig")
        self.assertEqual(3, source.count("PhTranslateString("))
        self.assertIn("realColumn->Text = PhTranslateString(Column->Text);", source)
        self.assertIn("translatedText = PhTranslateString(text->Buffer);", source)
        self.assertEqual(72, len(RUNTIME_COMPATIBILITY_KEYS))
        self.assertLessEqual(
            {"Description", "Display name", "Entry point", "Service",
             "Session ID", "State", "Status", "Subsystem", "Symbol", "Time stamp"},
            RUNTIME_COMPATIBILITY_KEYS,
        )

    def test_retired_runtime_keys_have_no_exact_non_native_consumer(self) -> None:
        reviewed_keys = {"Committed", "Home directory", "References"}
        consumers = {key: [] for key in reviewed_keys}

        for root in (APP_ROOT, REPO_ROOT / "phlib", REPO_ROOT / "plugins", REPO_ROOT / "tools"):
            for path in root.rglob("*"):
                if path.suffix.lower() not in {".c", ".cpp", ".h", ".rc"}:
                    continue
                if "tests" in path.parts or path.name == "phtranslation_zhcn.c":
                    continue
                source = path.read_text(encoding="utf-8-sig", errors="ignore")
                if path.suffix.lower() in {".c", ".cpp", ".h"}:
                    source = self.audit.mask_c_comments(source)
                for key in reviewed_keys:
                    if path == APP_ROOT / "SystemInformer.rc":
                        continue
                    if re.search(rf'(?<![A-Za-z])(?:L)?"{re.escape(key)}"', source):
                        consumers[key].append(path.relative_to(REPO_ROOT).as_posix())

        self.assertEqual(
            {"Committed": [], "Home directory": [], "References": []},
            consumers,
        )
        self.assertTrue(reviewed_keys.isdisjoint(RUNTIME_COMPATIBILITY_KEYS))

    def test_systeminformer_has_no_direct_static_treenew_findings(self) -> None:
        unresolved = []
        for path in APP_ROOT.glob("*.c"):
            entries = []
            self.audit.scan_c_file(str(path), entries)
            unresolved.extend(entry for entry in entries if entry["category"] in {"c_treenew_col", "c_treenew_empty"})
        self.assertEqual([], unresolved)


if __name__ == "__main__":
    unittest.main()
