//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UserNotes.rc
//
#define IDD_OPTIONS                     101
#define IDD_PROCCOMMENT                 102
#define IDD_SRVCOMMENT                  103
#define IDS_UN_AFFINITY_INDIVIDUAL_THREADS 2000
#define IDS_UN_IFEO_KEY_DELETED         2001
#define IDS_UN_MULTI_GROUP_AFFINITY     2002
#define IDS_UN_UNABLE_CONFIGURE_IFEO_PRIORITY 2003
#define IDS_UN_UNABLE_QUERY_GRAPHICS_PRIORITY 2004
#define IDS_UN_UNABLE_QUERY_IO_PRIORITY 2005
#define IDS_UN_UNABLE_QUERY_PAGE_PRIORITY 2006
#define IDS_UN_UNABLE_QUERY_PRIORITY    2007
#define IDS_UN_UNABLE_QUERY_PROCESS_AFFINITY 2008
#define IDS_UN_UNABLE_QUERY_PROCESS_BOOST 2009
#define IDS_UN_UNABLE_QUERY_PROCESS_EFFICIENCY 2010
#define IDS_UN_UNABLE_UPDATE_GRAPHICS_PRIORITY 2011
#define IDS_UN_UNABLE_UPDATE_IFEO_IO_PRIORITY 2012
#define IDS_UN_UNABLE_UPDATE_IFEO_PAGE_PRIORITY 2013
#define IDS_UN_UNABLE_UPDATE_IFEO_PRIORITY 2014
#define IDS_UN_DB_TYPE_FILE             2015
#define IDS_UN_DB_TYPE_SERVICE          2016
#define IDS_UN_DB_TYPE_COMMAND_LINE     2017
#define IDS_UN_STATUS_TRUE              2018
#define IDC_COMMENT                     1003
#define IDC_REVERT                      1004
#define IDC_MATCHCOMMANDLINE            1005
#define IDC_COLLAPSE_SERVICES_CHECK     1005
#define IDC_DBLIST                      1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           2019
#endif
#endif
