//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by peview.rc
//
#define IDR_RT_MANIFEST                 1
#define IDD_PEGENERAL                   101
#define IDD_PEIMPORTS                   102
#define IDD_PEEXPORTS                   103
#define IDD_LIBEXPORTS                  104
#define IDD_PECLR                       105
#define IDD_PELOADCONFIG                106
#define IDD_PECFG                       107
#define IDD_PESYMBOLS                   108
#define IDD_PERESOURCES                 109
#define IDB_SEARCH_ACTIVE               110
#define IDD_ELFGENERAL                  110
#define IDB_SEARCH_INACTIVE             111
#define IDD_PEPROPSTORAGE               111
#define IDB_SEARCH_ACTIVE_BMP           112
#define IDD_PEATTR                      112
#define IDB_SEARCH_INACTIVE_BMP         113
#define IDD_PESTREAMS                   113
#define IDD_PELINKS                     114
#define IDD_PIDS                        115
#define IDD_ELFDYNAMIC                  116
#define IDD_TLS                         117
#define IDD_STRINGS                     118
#define IDD_STRINGSMINLEN               119
#define IDI_APPICON                     122
#define IDD_PEPREVIEW                   124
#define IDD_OPTIONS                     126
#define IDD_PEDIRECTORY                 127
#define IDD_PEPRODID                    129
#define IDD_PEDEBUG                     131
#define IDD_PESECTIONS                  132
#define IDD_PESECURITY                  133
#define IDD_PEEHCONT                    134
#define IDD_PEDEBUGPOGO                 135
#define IDD_PEDEBUGCRT                  136
#define IDD_PELAYOUT                    137
#define IDD_PEHASHES                    138
#define IDD_PEEXCEPTIONS                140
#define IDD_PERELOCATIONS               142
#define IDD_TABWINDOW                   146
#define IDD_CHOOSECOLUMNS               166
#define IDD_PEHEADERS                   167
#define IDD_PECLRIMPORTS                168
#define IDD_ELFIMPORTS                  169
#define IDD_ELFEXPORTS                  170
#define IDD_PEVOLATILE                  171
#define IDD_PECLRTABLES                 172
#define IDD_PEVERSIONINFO               173
#define IDD_GETPROCADDR                 174
#define IDD_GETLOADLIBRARY              175
#define IDD_PECLRTABLEPREVIEW           176
#define IDD_PERESOURCEVIEW              177
#define IDD_PEDYNAMICRELOC             178
#define IDD_CONTAINER                   205
#define IDB_SEARCH_REGEX_MODERN_DARK    206
#define IDB_SEARCH_REGEX_MODERN_LIGHT   207
#define IDB_SEARCH_CASE_MODERN_DARK     208
#define IDB_SEARCH_CASE_MODERN_LIGHT    209
#define IDB_SEARCH_ACTIVE_MODERN_DARK   210
#define IDB_SEARCH_ACTIVE_MODERN_LIGHT  211
#define IDB_SEARCH_INACTIVE_MODERN_DARK 212
#define IDB_SEARCH_INACTIVE_MODERN_LIGHT 213
#define IDC_MINIMUMLENGTH               1001
#define IDC_TARGETMACHINE               1003
#define IDC_LIST                        1008
#define IDC_FILEICON                    1009
#define IDC_RUNTIMEVERSION              1011
#define IDC_FILE                        1011
#define IDC_FLAGS                       1012
#define IDC_COMPANYNAME                 1012
#define IDC_VERSION                     1013
#define IDC_TARGETVERSION               1013
#define IDC_VERSIONSTRING               1014
#define IDC_IMAGEBASE                   1015
#define IDC_MVIDSTRING                  1015
#define IDC_ENTRYPOINT                  1016
#define IDC_TOKENSTRING                 1016
#define IDC_IMAGETYPE                   1017
#define IDC_ENTRYPOINTSTRING            1017
#define IDC_NAME                        1019
#define IDC_COMPANYNAME_LINK            1020
#define IDC_PREVIEW                     1023
#define IDC_PRODCHECKSUM                1025
#define IDC_PRODHASH                    1026
#define IDC_PRODHASH2                   1027
#define IDC_OPTIONS                     1031
#define IDC_PRODID                      1032
#define IDC_CLRGROUP                    1033
#define IDC_TREELIST                    1034
#define IDC_TREESEARCH                  1035
#define IDC_FILTER                      1050
#define IDC_FONT                        1079
#define IDC_GOTO                        1079
#define IDC_MOVEUP                      1079
#define IDC_RESET                       1086
#define IDC_SECURITY                    1087
#define IDC_MESSAGE                     1142
#define IDC_MAXSIZEUNIT                 1144
#define IDC_MOVEDOWN                    1176
#define IDC_UNDO                        1201
#define IDC_PASTE                       1204
#define IDC_CUT                         1205
#define IDC_COPY                        1206
#define IDC_INACTIVE                    1207
#define IDC_ACTIVE                      1208
#define IDC_SHOW                        1209
#define IDC_HIDE                        1210
#define IDC_DBGHELPSEARCHPATH           1218
#define IDC_SELECTALL                   1365
#define IDC_DELETE                      1382
#define IDC_SEARCH                      1387
#define IDC_SECTIONTREE                 1393
#define IDC_SETTINGS                    1399
#define IDC_RESTYPE                     1400
#define IDC_TEXT                        1401

#define IDS_PV_MENU_ANSI                        3000
#define IDS_PV_MENU_UTF8                        3001
#define IDS_PV_MENU_UTF16                       3002
#define IDS_PV_MENU_EXTENDED_CHARACTER_SET      3003
#define IDS_PV_MENU_SKIP_TEXT_SECTION           3004
#define IDS_PV_MENU_SKIP_HIGH_ENTROPY            3005
#define IDS_PV_MENU_SKIP_NUMBERS                 3006
#define IDS_PV_MENU_SKIP_SYMBOLS                 3007
#define IDS_PV_MENU_MINIMUM_LENGTH               3008
#define IDS_PV_MENU_REFRESH                      3009
#define IDS_PV_MENU_HIDE_WRITABLE                3010
#define IDS_PV_MENU_HIDE_EXECUTABLE              3011
#define IDS_PV_MENU_HIDE_CODE                    3012
#define IDS_PV_MENU_HIDE_READABLE                3013
#define IDS_PV_MENU_HIDE_PARAMETERS              3014
#define IDS_PV_MENU_FILTER_NON_WRITABLE          3015
#define IDS_PV_MENU_HIGHLIGHT_WRITABLE           3016
#define IDS_PV_MENU_HIGHLIGHT_EXECUTABLE         3017
#define IDS_PV_MENU_HIGHLIGHT_CODE               3018
#define IDS_PV_MENU_HIGHLIGHT_READABLE           3019
#define IDS_PV_MENU_DISPLAY_RESOURCE             3020
#define IDS_PV_MENU_SAVE_RESOURCE                3021
#define IDS_PV_MENU_COPY                         3022
#define IDS_PV_MENU_VIEW_CERTIFICATE             3023
#define IDS_PV_MENU_SAVE_CERTIFICATE             3024
#define IDS_PV_COLUMN_ALGORITHM                   3025
#define IDS_PV_COLUMN_ATTRIBUTES                  3026
#define IDS_PV_COLUMN_BINDING                     3027
#define IDS_PV_COLUMN_CFG_EXPORT_SUPPRESSION      3028
#define IDS_PV_COLUMN_CALL_VA                     3029
#define IDS_PV_COLUMN_CHARACTERISTICS             3030
#define IDS_PV_COLUMN_FORMAT                      3031
#define IDS_PV_COLUMN_COMPONENT                   3032
#define IDS_PV_COLUMN_COUNT                       3033
#define IDS_PV_COLUMN_DLL                         3034
#define IDS_PV_COLUMN_DATA                        3035
#define IDS_PV_COLUMN_DESCRIPTION                 3036
#define IDS_PV_COLUMN_END                         3037
#define IDS_PV_COLUMN_ENTROPY                     3038
#define IDS_PV_COLUMN_FLAGS                       3039
#define IDS_PV_COLUMN_FORWARDED_NAME              3040
#define IDS_PV_COLUMN_FROM                        3041
#define IDS_PV_COLUMN_HANDLER                     3042
#define IDS_PV_COLUMN_HASH                        3043
#define IDS_PV_COLUMN_HINT                        3044
#define IDS_PV_COLUMN_IAT_SLOT                    3045
#define IDS_PV_COLUMN_INFO                        3046
#define IDS_PV_COLUMN_ISSUER                      3047
#define IDS_PV_COLUMN_LANGUAGE                    3048
#define IDS_PV_COLUMN_LENGTH                      3049
#define IDS_PV_COLUMN_MODULE                      3050
#define IDS_PV_COLUMN_NAME                        3051
#define IDS_PV_COLUMN_NAME_TYPE                   3052
#define IDS_PV_COLUMN_OFFSET                      3053
#define IDS_PV_COLUMN_ORDINAL                     3054
#define IDS_PV_COLUMN_ORDINAL_NAME                3055
#define IDS_PV_COLUMN_ORDINAL_HINT                3056
#define IDS_PV_COLUMN_PID                         3057
#define IDS_PV_COLUMN_PRODUCT                     3058
#define IDS_PV_COLUMN_RAW_END                     3059
#define IDS_PV_COLUMN_RAW_SIZE                    3060
#define IDS_PV_COLUMN_RAW_START                   3061
#define IDS_PV_COLUMN_RID                         3062
#define IDS_PV_COLUMN_RVA                         3063
#define IDS_PV_COLUMN_RVA_END                     3064
#define IDS_PV_COLUMN_RVA_SIZE                    3065
#define IDS_PV_COLUMN_RVA_START                   3066
#define IDS_PV_COLUMN_RELOCATION_SYMBOL           3067
#define IDS_PV_COLUMN_SEH_HANDLER                 3068
#define IDS_PV_COLUMN_SSDEEP                      3069
#define IDS_PV_COLUMN_SECTION                     3070
#define IDS_PV_COLUMN_SIZE                        3071
#define IDS_PV_COLUMN_SLACK_SPACE                 3072
#define IDS_PV_COLUMN_START                       3073
#define IDS_PV_COLUMN_STRING                      3074
#define IDS_PV_COLUMN_STRING_ORDINAL              3075
#define IDS_PV_COLUMN_SYMBOL                      3076
#define IDS_PV_COLUMN_SYMBOL_NAME                 3077
#define IDS_PV_COLUMN_TLSH                        3078
#define IDS_PV_COLUMN_TAG                         3079
#define IDS_PV_COLUMN_TARGET                      3080
#define IDS_PV_COLUMN_THUMBPRINT                  3081
#define IDS_PV_COLUMN_TO                          3082
#define IDS_PV_COLUMN_TYPE                        3083
#define IDS_PV_COLUMN_UNDECORATED_NAME            3084
#define IDS_PV_COLUMN_VA                          3085
#define IDS_PV_COLUMN_VALUE                       3086
#define IDS_PV_COLUMN_VERSION                     3087
#define IDS_PV_COLUMN_VIEW                        3088
#define IDS_PV_COLUMN_VISIBILITY                  3089
#define IDS_PV_COLUMN_XFG_HASH                    3090
#define IDS_PV_OPTION_THEME_SUPPORT               3091
#define IDS_PV_OPTION_LEGACY_PROPERTIES           3092
#define IDS_PV_OPTION_VIEW_BORDERS                 3093
#define IDS_PV_OPTION_REMEMBER_LAST_WINDOW         3094
#define IDS_PV_MAPPING_SESSION                     3095
#define IDS_PV_MAPPING_SYSTEM                      3096
#define IDS_PV_MAPPING_UNKNOWN                     3097
#define IDS_PV_RESTART_REQUIRED                    3098
#define IDS_PV_RESTART_PROMPT                      3099
#define IDS_PV_RESET_ALL_SETTINGS                  3100
#define IDS_PV_CLEAN_UNUSED_SETTINGS               3101
#define IDS_PV_CORRUPT_SETTINGS                    3102
#define IDS_PV_CORRUPT_SETTINGS_CONTENT            3103
#define IDS_PV_WARNING_TITLE                       3104
#define IDS_PV_WOW64_WARNING                       3105
#define IDS_PV_UNABLE_LOAD_FILE                    3106
#define IDS_PV_UNSUPPORTED_IMAGE                   3107
#define IDS_PV_CRASH_MESSAGE                       3108
#define IDS_PV_CLR_METADATA_UNAVAILABLE            3109
#define IDS_PV_CLR_PREVIEW_FAILED                  3110
#define IDS_PV_CLR_PREVIEW_CREATE_FAILED           3111
#define IDS_PV_RESOURCE_ENUM_FAILED                3112
#define IDS_PV_RESOURCE_DATA_NOT_FOUND             3113
#define IDS_PV_MENU_COPY_ACCELERATED               3114
#define IDS_PV_MENU_DELETE                         3115
#define IDS_PV_MENU_SIZE_COLUMN_TO_FIT             3116
#define IDS_PV_MENU_SIZE_ALL_COLUMNS_TO_FIT        3117
#define IDS_PV_MENU_HIDE_COLUMN                    3118
#define IDS_PV_MENU_CHOOSE_COLUMNS                 3119
#define IDS_PV_MENU_RESET_SORT                     3120
#define IDS_PV_UNABLE_REMOVE_ATTRIBUTE             3121
#define IDS_PV_UNABLE_LOAD_PDB                     3122
#define IDS_PV_INVALID_MINIMUM_LENGTH               3123
#define IDS_PV_UNABLE_LOAD_ARCHIVE                 3124
#define IDS_PV_UNABLE_SAVE_RESOURCE                3125
#define IDS_PV_UNABLE_REGISTER_WINDOW_CLASS         3126
#define IDS_PV_UNABLE_COMMIT_DETOURS_TRANSACTION    3127
#define IDS_PV_GROUP_FILE_HASHES                     3128
#define IDS_PV_GROUP_IMPORT_HASHES                   3129
#define IDS_PV_GROUP_FUZZY_HASHES                    3130
#define IDS_PV_GROUP_AUTHENTICODE_HASHES             3131
#define IDS_PV_GROUP_WDAC_PAGE_HASHES                3132
#define IDS_PV_GROUP_AUTHENTICODE_PAGE_HASHES        3133
#define IDS_PV_FIRST                               IDS_PV_MENU_ANSI
#define IDS_PV_LAST                                IDS_PV_GROUP_AUTHENTICODE_PAGE_HASHES

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           3134
#endif
#endif
