//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemInformer.rc
//
#include <phappresourceid.h>

#define IDR_RT_MANIFEST                 1
#define IDI_SYSTEMINFORMER              101
#define IDR_MAINWND_ACCEL               102
#define IDD_PROCGENERAL                 103
#define IDD_PROCMODULES                 104
#define IDD_PROCTHREADS                 105
#define IDD_PROCHANDLES                 106
#define IDD_PROCENVIRONMENT             107
#define IDD_THRDSTACK                   108
#define IDD_THRDSTACKS                  109
#define IDD_USRLIST                     110
#define IDC_CPU                         112
#define IDC_PRIVATEBYTES                113
#define IDC_IO                          114
#define IDC_MEMORY                      120
#define IDD_ABOUT                       121
#define IDC_NEWOBJECTS                  121
#define IDC_REMOVEDOBJECTS              122
#define IDD_SRVLIST                     125
#define IDD_SRVGENERAL                  126
#define IDD_HNDLGENERAL                 128
#define IDD_INFORMATION                 129
#define IDD_FINDOBJECTS                 130
#define IDD_ATTACHPROCESS               290
#define IDD_OBJTOKEN                    131
#define ID_PLUGIN_MENU_ITEM             131
#define ID_CALLBACK_MENU_ITEM           132
#define IDD_ZOMBIEPROCESSES             135
#define ID_TRAYICONS_REGISTERED         135
#define IDD_RUNAS                       136
#define ID_COPY_CELL                    136
#define IDD_PROGRESS                    137
#define IDD_PAGEFILES                   138
#define IDD_TOKGENERAL                  139
#define IDD_TOKADVANCED                 140
#define IDD_OBJJOB                      141
#define IDD_OBJEVENT                    142
#define IDD_OBJMUTANT                   143
#define IDD_OBJSEMAPHORE                144
#define IDD_OBJTIMER                    145
#define IDD_JOBSTATISTICS               146
#define IDD_OBJEVENTPAIR                147
#define IDD_OBJSECTION                  148
#define IDD_AFFINITY                    149
#define IDD_SYSINFO                     150
#define IDD_HNDLSECURITY                151
#define IDD_EDITMESSAGE                 152
#define IDD_SESSION                     153
#define IDD_PROCMEMORY                  154
#define IDD_CHOOSE                      155
#define IDD_OPTGENERAL                  162
#define IDD_OPTHIGHLIGHTING             163
#define IDD_OPTTHEMES                   164
#define IDD_OPTTRAYICON                 165
#define IDD_CHOOSECOLUMNS               166
#define IDD_NETSTACK                    167
#define IDD_CREATESERVICE               168
#define IDD_PROCPERFORMANCE             169
#define ID_SHOWCONTEXTMENU              169
#define IDD_PROCSTATISTICS              170
#define IDD_OPTADVANCED                 171
#define IDD_GDIHANDLES                  175
#define IDD_LOG                         178
#define IDD_MEMEDIT                     180
#define IDD_MEMPROTECT                  182
#define IDD_MEMRESULTS                  183
#define IDD_MEMSTRING                   185
#define IDD_OPTGRAPHS                   186
#define IDD_PLUGINS                     187
#define IDD_PLUGINMANAGER               187
#define IDD_HANDLESTATS                 188
#define IDD_PROCRECORD                  189
#define IDD_CHOOSEPROCESS               190
#define IDD_PROCSERVICES                191
#define IDI_PHAPPLICATION               191
#define IDI_COG                         192
#define IDD_SHADOWSESSION               193
#define IDI_PHAPPLICATIONGO             194
#define IDD_TOKCAPABILITIES             194
#define IDI_COGGO                       195
#define IDD_TOKATTRIBUTES               195
#define IDD_SYSINFO_CPU                 196
#define IDD_SYSINFO_CPUPANEL            197
#define IDD_SYSINFO_MEMPANEL            198
#define IDR_SYSINFO_ACCEL               198
#define IDD_SYSINFO_MEM                 199
#define IDD_SYSINFO_IO                  200
#define IDD_SYSINFO_IOPANEL             201
#define IDD_MEMLISTS                    202
#define IDD_CONTAINER                   205
#define IDD_MINIINFO                    207
#define IDD_MINIINFO_LIST               210
#define IDD_MITIGATION                  215
#define IDD_TOKAPPPOLICY                216
#define IDI_PIN                         216
#define IDI_FOLDER                      217
#define IDI_MAGNIFIER                   219
#define IDD_ENVEDIT                     221
#define IDD_ENVEDIT_LIST                293
#define IDD_ENVIRONMENTVARIABLES        294
#define IDB_SEARCH_ACTIVE               223
#define IDB_SEARCH_INACTIVE             224
#define IDB_SEARCH_ACTIVE_BMP           225
#define IDB_SEARCH_INACTIVE_BMP         226
#define IDD_OPTIONS                     227
#define IDD_PLUGINPROPERTIES            228
#define IDD_PLUGINSDISABLED             241
#define IDD_PROCWMIPROVIDERS            242
#define IDD_COLUMNSETS                  243
#define ID_VIEW_TRAYICONS               244
#define IDD_OBJFILE                     249
#define IDD_RUNFILEDLG                  253
#define IDD_LIVEDUMP                    254
#define IDD_HEAPS                       255
#define IDD_PROCDUMP                    256
#define IDD_PROCVDMHOST                 257
#define IDD_OPTSYMBOLS                  258
#define IDD_OPTHOTKEYS                  259
#define IDD_OBJMAPPINGS                 258
#define IDI_UACSHIELD                   261
#define IDD_RUNPACKAGE                  263
#define IDD_MODIFIEDPAGES               264
#define IDD_MEMCFG                      284
#define IDD_GAMESENUMERATION            285
#define IDB_SEARCH_ACTIVE_SMALL         265
#define IDB_SEARCH_INACTIVE_SMALL       266
#define IDB_SEARCH_REGEX_MODERN_DARK    267
#define IDB_SEARCH_REGEX_MODERN_LIGHT   268
#define IDB_SEARCH_CASE_MODERN_DARK     269
#define IDB_SEARCH_CASE_MODERN_LIGHT    270
#define IDB_SEARCH_ACTIVE_MODERN_DARK   271
#define IDB_SEARCH_ACTIVE_MODERN_LIGHT  272
#define IDB_SEARCH_INACTIVE_MODERN_DARK 273
#define IDD_THRDSCAN                    273
#define IDB_SEARCH_INACTIVE_MODERN_LIGHT 274
#define IDD_INPUT                       275
#define IDD_CHOOSENEW                   275
#define IDD_MEMSTRINGSMINLEN            276
#define IDD_MEMSTRINGS                  277
#define IDD_HNDLAUDITING                278
#define IDD_HNDLSECAUDIT                278
#define IDD_INFORMER                    279
#define IDD_PROCINFORMER                280
#define IDD_SYSINFO_CPUEX               281
#define IDD_SYSINFO_CPUEXPANEL          282
#define IDD_SYMBOLS                     283
#define IDD_THRDCONTEXT                 288
#define IDD_CONTAINER_RUN               289
#define IDD_CONTAINER_CREATE            291
#define IDD_OPTADVEDIT                  292
#define IDC_STATUS                      1002
#define IDC_TERMINATE                   1003
#define IDC_COMMAND                     1004
#define IDC_PROCESSISOLATION            1005
#define IDC_FILEICON                    1005
#define IDC_PULLRUN                     1006
#define IDC_FILE                        1006
#define IDC_PROCESS                     1007
#define IDC_COMPANYNAME                 1009
#define IDC_VERSION                     1010
#define IDC_REFRESH                     1015
#define IDC_REFRESH2                    1016
#define IDC_PERMISSIONS                 1018
#define IDC_FILENAME                    1020
#define IDC_CMDLINE                     1021
#define IDC_URL                         1021
#define IDC_RUNSELECTED                 1021
#define IDC_CURDIR                      1022
#define IDC_STARTED                     1023
#define IDC_ABOUT_NAME                  1024
#define IDC_TERMINATED                  1024
#define IDC_PARENTCONSOLE               1024
#define IDC_PARENTPROCESS               1025
#define IDC_MITIGATION                  1026
#define IDC_PAUSE                       1027
#define IDC_PROTECTION                  1027
#define IDC_START                       1028
#define IDC_FILENAMEWIN32               1028
#define IDC_DESCRIPTION                 1029
#define IDC_TYPE                        1032
#define IDC_STARTTYPE                   1033
#define IDC_ADDRESS                     1033
#define IDC_IMPERSONATIONLEVEL          1033
#define IDC_ERRORCONTROL                1034
#define IDC_GRANTED_ACCESS              1034
#define IDC_TOKENLUID                   1034
#define IDC_GROUP                       1035
#define IDC_AUTHENTICATIONLUID          1035
#define IDC_BINARYPATH                  1036
#define IDC_MEMORYUSED                  1036
#define IDC_USERACCOUNT                 1037
#define IDC_MEMORYAVAILABLE             1037
#define IDC_PASSWORD                    1040
#define IDC_PASSWORDCHECK               1041
#define IDC_SERVICEDLL                  1042
#define IDC_NAME                        1044
#define IDC_REFERENCES                  1045
#define IDC_INTERNALNAME                1045
#define IDC_HANDLES                     1046
#define IDC_AUTHOR                      1046
#define IDC_PAGED                       1047
#define IDC_PROCESSTYPETEXT             1047
#define IDC_NONPAGED                    1048
#define IDC_TEXT                        1048
#define IDC_DIAGNOSTICS                 1049
#define IDC_FILTER                      1050
#define IDC_RESULTS                     1051
#define IDC_USER                        1052
#define IDC_USERSID                     1053
#define IDC_ADVANCED                    1054
#define IDC_OWNER                       1054
#define IDC_ENABLETHEME                 1154
#define IDC_THEMEMODE                   1518
#define IDC_SCROLLBARSKIN               1519
#define IDC_GROUPS                      1055
#define IDC_PRIMARYGROUP                1055
#define IDC_VIRTUALIZATION              1056
#define IDC_SESSIONID                   1057
#define IDC_ELEVATED                    1058
#define IDC_VIRTUALIZED                 1059
#define IDC_SOURCENAME                  1059
#define IDC_PROPERTIES                  1060
#define IDC_SOURCELUID                  1060
#define IDC_APPCONTAINERSID             1060
#define IDC_LIST                        1061
#define IDC_TOKENUSER                   1061
#define IDC_UIACCESS                    1061
#define IDC_TOKENSID                    1062
#define IDC_PROCESSES                   1063
#define IDC_SCAN                        1064
#define IDC_SAVE                        1065
#define IDC_METHOD                      1067
#define IDC_INTRO                       1068
#define IDC_PROGRAM                     1069
#define IDC_BROWSE                      1070
#define IDC_USERNAME                    1071
#define IDC_SESSIONCOMBO                1072
#define IDC_DESKTOPCOMBO                1073
#define IDC_SESSIONS                    1074
#define IDC_PROGRAMCOMBO                1074
#define IDC_DESKTOPS                    1075
#define IDC_PROGRESS                    1076
#define IDC_PROGRESSTEXT                1077
#define IDC_LINKEDTOKEN                 1079
#define IDC_DISABLEALL                  1079
#define IDC_MOVEUP                      1079
#define IDC_CLEAR                       1079
#define IDC_GOTO                        1079
#define IDC_OPTIONS                     1079
#define IDC_DETAILS                     1079
#define IDC_ADD                         1079
#define IDC_FONT                        1079
#define IDC_INTEGRITY                   1079
#define IDC_MORE                        1079
#define IDC_VIEWMITIGATION              1080
#define IDC_REPLACETASKMANAGER          1080
#define IDC_RENAME                      1080
#define IDC_VIEWPARENTPROCESS           1081
#define IDC_OPENFILENAME                1082
#define IDC_LIMITS                      1083
#define IDC_OPENFILENAME2               1083
#define IDC_SIGNALED                    1084
#define IDC_SET                         1085
#define IDC_RESET                       1086
#define IDC_PULSE                       1087
#define IDC_APPLY                       1087
#define IDC_COUNT                       1088
#define IDC_ABANDONED                   1089
#define IDC_CURRENTCOUNT                1090
#define IDC_MAXIMUMCOUNT                1091
#define IDC_ACQUIRE                     1092
#define IDC_RELEASE                     1093
#define IDC_CANCEL                      1094
#define IDC_OWNERLABEL                  1095
#define IDC_SETLOW                      1096
#define IDC_SETHIGH                     1097
#define IDC_SIZE_                       1098
#define IDC_CPU0                        1099
#define IDC_CPU1                        1100
#define IDC_CPU2                        1101
#define IDC_CPU3                        1102
#define IDC_CPU4                        1103
#define IDC_CPU5                        1104
#define IDC_CPU6                        1105
#define IDC_CPU7                        1106
#define IDC_CPU8                        1107
#define IDC_TITLE                       1107
#define IDC_CPU9                        1108
#define IDC_CPU10                       1109
#define IDC_TIMEOUT                     1109
#define IDC_CPU11                       1110
#define IDC_CPU12                       1111
#define IDC_STATE                       1111
#define IDC_CPU13                       1112
#define IDC_CLIENTNAME                  1112
#define IDC_CPU14                       1113
#define IDC_CLIENTADDRESS               1113
#define IDC_CPU15                       1114
#define IDC_CLIENTDISPLAY               1114
#define IDC_CPU16                       1115
#define IDC_CHOICE                      1115
#define IDC_CPU17                       1116
#define IDC_OPTION                      1116
#define IDC_CPU18                       1117
#define IDC_CHOICEUSER                  1117
#define IDC_CPU19                       1118
#define IDC_HIDEUNNAMEDHANDLES          1118
#define IDC_CPU20                       1119
#define IDC_CPU21                       1120
#define IDC_STARTMODULE                 1120
#define IDC_CPU22                       1121
#define IDC_OPENSTARTMODULE             1121
#define IDC_CPU23                       1122
#define IDC_KERNELTIME                  1122
#define IDC_CPU24                       1123
#define IDC_USERTIME                    1123
#define IDC_CPU25                       1124
#define IDC_CONTEXTSWITCHES             1124
#define IDC_CPU26                       1125
#define IDC_CYCLES                      1125
#define IDC_CPU27                       1126
#define IDC_PRIORITY                    1126
#define IDC_CPU28                       1127
#define IDC_BASEPRIORITY                1127
#define IDC_CPU29                       1128
#define IDC_IOPRIORITY                  1128
#define IDC_CPU30                       1129
#define IDC_PAGEPRIORITY                1129
#define IDC_CPU31                       1130
#define IDC_STATICBL1                   1130
#define IDC_STATICBL2                   1131
#define IDC_CPU32                       1131
#define IDC_STATICBL3                   1132
#define IDC_CPU33                       1132
#define IDC_STATICBL4                   1133
#define IDC_CPU34                       1133
#define IDC_STATICBL5                   1134
#define IDC_CPU35                       1134
#define IDC_STATICBL6                   1135
#define IDC_CPU36                       1135
#define IDC_STATICBL7                   1136
#define IDC_CPU37                       1136
#define IDC_STATICBL8                   1137
#define IDC_CPU38                       1137
#define IDC_STATICBL9                   1138
#define IDC_CPU39                       1138
#define IDC_STATICBL10                  1139
#define IDC_CPU40                       1139
#define IDC_STATICBL11                  1140
#define IDC_CPU41                       1140
#define IDC_CHOICESIMPLE                1141
#define IDC_CPU42                       1141
#define IDC_MESSAGE                     1142
#define IDC_CPU43                       1142
#define IDC_SEARCHENGINE                1143
#define IDC_CPU44                       1143
#define IDC_MAXSIZEUNIT                 1144
#define IDC_CPU45                       1144
#define IDC_CPU46                       1145
#define IDC_CPU47                       1146
#define IDC_CPU48                       1147
#define IDC_CPU49                       1148
#define IDC_CPU50                       1149
#define IDC_CPU51                       1150
#define IDC_PEVIEWER                    1151
#define IDC_CPU52                       1151
#define IDC_CPU53                       1152
#define IDC_CPU54                       1153
#define IDC_CPU55                       1154
#define IDC_HIGHLIGHTINGDURATION        1155
#define IDC_CPU56                       1155
#define IDC_CPU57                       1156
#define IDC_ENABLEALL                   1157
#define IDC_CPU58                       1157
#define IDC_ZACTIVEPROCESSES_V          1158
#define IDC_CPU59                       1158
#define IDC_ZTOTALPROCESSES_V           1159
#define IDC_CPU60                       1159
#define IDC_ZTERMINATEDPROCESSES_V      1160
#define IDC_CPU61                       1160
#define IDC_ZUSERTIME_V                 1161
#define IDC_CPU62                       1161
#define IDC_ZKERNELTIME_V               1162
#define IDC_CPU63                       1162
#define IDC_ZUSERTIMEPERIOD_V           1163
#define IDC_ZKERNELTIMEPERIOD_V         1164
#define IDC_ZPAGEFAULTS_V               1165
#define IDC_ZPEAKPROCESSUSAGE_V         1166
#define IDC_ZPEAKJOBUSAGE_V             1167
#define IDC_ZIOREADS_V                  1168
#define IDC_ZIOREADBYTES_V              1169
#define IDC_ZIOWRITES_V                 1170
#define IDC_ZIOWRITEBYTES_V             1171
#define IDC_ZIOOTHER_V                  1172
#define IDC_ZIOOTHERBYTES_V             1173
#define IDC_MOVEDOWN                    1176
#define IDC_REMOVE                      1177
#define IDC_DISPLAYNAME                 1179
#define IDC_ZPRIORITY_V                 1181
#define IDC_ZCYCLES_V                   1182
#define IDC_ZTOTALTIME_V                1185
#define IDC_ZPRIVATEBYTES_V             1186
#define IDC_ZWORKINGSET_V               1187
#define IDC_ZPEAKWORKINGSET_V           1188
#define IDC_ZVIRTUALSIZE_V              1189
#define IDC_ZPEAKVIRTUALSIZE_V          1190
#define IDC_ZPEAKPRIVATEBYTES_V         1191
#define IDC_ZPAGEPRIORITY_V             1192
#define IDC_ZIOPRIORITY_V               1194
#define IDC_ZHANDLES_V                  1195
#define IDC_ZGDIHANDLES_V               1196
#define IDC_ZOTHERDELTA_V               1196
#define IDC_ZUSERHANDLES_V              1197
#define IDC_ZOTHER_V                    1197
#define IDC_GROUPCPU                    1198
#define IDC_GROUPPRIVATEBYTES           1199
#define IDC_GROUPIO                     1200
#define IDC_UNDO                        1201
#define IDC_ONEGRAPHPERCPU              1202
#define IDC_ALWAYSONTOP                 1203
#define IDC_PASTE                       1204
#define IDC_CUT                         1205
#define IDC_COPY                        1206
#define IDC_INACTIVE                    1207
#define IDC_ACTIVE                      1208
#define IDC_SHOW                        1209
#define IDC_HIDE                        1210
#define IDC_AUTOSCROLL                  1215
#define IDC_UNDECORATESYMBOLS           1216
#define IDC_DBGHELPPATH                 1217
#define IDC_DBGHELPSEARCHPATH           1218
#define IDC_DESKTOP                     1221
#define IDC_REREAD                      1224
#define IDC_WRITE                       1225
#define IDC_VALUE                       1230
#define IDC_DELAYEDSTART                1234
#define IDC_MINIMUMLENGTH               1236
#define IDC_DETECTUNICODE               1237
#define IDC_PRIVATE                     1238
#define IDC_IMAGE                       1239
#define IDC_IMAGEDESC                   1500
#define IDC_MAPPED                      1240
#define IDC_EXTENDEDUNICODE             1241
#define IDC_SHOWTEXT                    1245
#define IDC_ICONPROCESSES               1248
#define IDC_CLEANUP                     1251
#define IDC_CLEANUP                     1251
#define IDC_CONVERT                     1252
#define IDC_TOGGLEELEVATION             1254
#define IDC_TOGGLESUSPENDED             1255
#define IDC_TRUSTEDINSTALLER            1255
#define IDC_TOGGLEUIACCESS              1256
#define IDC_TOGGLENOPROFILE             1257
#define IDC_PARENT                      1263
#define IDC_PROCESSNAME                 1264
#define IDC_SERVICES_LAYOUT             1266
#define IDC_LINK_SF                     1267
#define IDC_CREDITS                     1270
#define IDC_LOGONTIME                   1272
#define IDC_ZPEAKHANDLES_V              1273
#define IDC_SHIFT                       1274
#define IDC_USEOLDCOLORS                1274
#define IDC_OPENURL                     1279
#define IDC_COMPANYNAME_LINK            1279
#define IDC_SAMPLECOUNT                 1280
#define IDC_SAMPLECOUNTLABEL            1281
#define IDC_VIRTUALKEY                  1283
#define IDC_CTRL                        1284
#define IDC_ALT                         1285
#define IDC_CONNECTTIME                 1286
#define IDC_DISCONNECTTIME              1287
#define IDC_LASTINPUTTIME               1288
#define IDC_ZPRIVATEWS_V                1289
#define IDC_ZSHAREABLEWS_V              1290
#define IDC_ZSHAREDWS_V                 1291
#define IDC_IDEALPROCESSOR              1294
#define IDC_STATICBL12                  1295
#define IDC_BASICINFORMATION            1296
#define IDC_INSTRUCTION                 1298
#define IDC_CPUNAME                     1299
#define IDC_LAYOUT                      1300
#define IDC_UTILIZATION                 1301
#define IDC_SPEED                       1302
#define IDC_ZPROCESSES_V                1303
#define IDC_ZTHREADS_V                  1304
#define IDC_ZCONTEXTSWITCHESDELTA_V     1307
#define IDC_ZINTERRUPTSDELTA_V          1308
#define IDC_ZDPCSDELTA_V                1309
#define IDC_ZSYSTEMCALLSDELTA_V         1310
#define IDC_GRAPH_LAYOUT                1311
#define IDC_ZCORES                      1311
#define IDC_TOTALPHYSICAL               1312
#define IDC_ZSOCKETS                    1312
#define IDC_ZLOGICAL                    1313
#define IDC_ZCOMMITCURRENT_V            1314
#define IDC_ZLATENCY                    1314
#define IDC_ZCOMMITPEAK_V               1315
#define IDC_ZCOMMITLIMIT_V              1316
#define IDC_ZPHYSICALCURRENT_V          1317
#define IDC_ZPHYSICALTOTAL_V            1318
#define IDC_ZPHYSICALCACHEWS_V          1319
#define IDC_ZPHYSICALKERNELWS_V         1320
#define IDC_ZPHYSICALDRIVERWS_V         1321
#define IDC_ZPAGEDWORKINGSET_V          1322
#define IDC_ZPAGEDVIRTUALSIZE_V         1323
#define IDC_ZPAGEDLIMIT_V               1324
#define IDC_ZPAGEDALLOCSDELTA_V         1325
#define IDC_ZPAGEDFREESDELTA_V          1326
#define IDC_ZNONPAGEDUSAGE_V            1327
#define IDC_ZNONPAGEDLIMIT_V            1328
#define IDC_ZNONPAGEDALLOCSDELTA_V      1329
#define IDC_ZNONPAGEDFREESDELTA_V       1330
#define IDC_ZPHYSICALRESERVED_V         1331
#define IDC_ZLISTZEROED_V               1332
#define IDC_ZLISTFREE_V                 1333
#define IDC_ZLISTMODIFIED_V             1334
#define IDC_ZLISTMODIFIEDNOWRITE_V      1335
#define IDC_ZLISTSTANDBY_V              1337
#define IDC_COMMIT_L                    1339
#define IDC_PHYSICAL_L                  1340
#define IDC_ZUPTIME_V                   1341
#define IDC_ZOTHERBYTESDELTA_V          1342
#define IDC_ZREADSDELTA_V               1343
#define IDC_ZREADBYTESDELTA_V           1344
#define IDC_ZWRITESDELTA_V              1345
#define IDC_ZLISTSTANDBY0_V             1346
#define IDC_ZWRITEBYTESDELTA_V          1346
#define IDC_ZLISTSTANDBY1_V             1347
#define IDC_ZREADS_V                    1347
#define IDC_ZLISTSTANDBY2_V             1348
#define IDC_ZREADBYTES_V                1348
#define IDC_ZLISTSTANDBY3_V             1349
#define IDC_ZWRITES_V                   1349
#define IDC_ZLISTBAD_V                  1350
#define IDC_ZWRITEBYTES_V               1350
#define IDC_ZLISTREPURPOSED_V           1351
#define IDC_ZOTHERBYTES_V               1351
#define IDC_ZLISTREPURPOSED0_V          1352
#define IDC_ZLISTREPURPOSED1_V          1353
#define IDC_ZLISTREPURPOSED2_V          1354
#define IDC_ZLISTREPURPOSED3_V          1355
#define IDC_ZLISTREPURPOSED4_V          1356
#define IDC_ZLISTREPURPOSED5_V          1357
#define IDC_ZLISTREPURPOSED6_V          1358
#define IDC_ZLISTREPURPOSED7_V          1359
#define IDC_EMPTY                       1360
#define IDC_SAMPLECOUNTAUTOMATIC        1361
#define IDC_SHOWCOMMITINSUMMARY         1361
#define IDC_ZLISTSTANDBY4_V             1364
#define IDC_ZLISTSTANDBY5_V             1365
#define IDC_SELECTALL                   1365
#define IDC_ZLISTSTANDBY6_V             1366
#define IDC_DESELECTALL                 1366
#define IDC_ZLISTSTANDBY7_V             1367
#define IDC_INSPECT                     1367
#define IDC_ZPAGINGPAGEFAULTSDELTA_V    1368
#define IDC_INSPECT2                    1368
#define IDC_ZPAGINGPAGEREADSDELTA_V     1369
#define IDC_BYTESPERROW                 1369
#define IDC_ZPAGINGPAGEFILEWRITESDELTA_V 1370
#define IDC_PINWINDOW                   1370
#define IDC_ZPAGINGMAPPEDWRITESDELTA_V  1371
#define IDC_ZMAPPEDREADIO               1372
#define IDC_ZLISTMODIFIEDPAGEFILE_V     1373
#define IDC_ZMAPPEDWRITEIO              1374
#define IDC_SECTION                     1375
#define IDC_REGEX                       1377
#define IDC_DESCRIPTIONLABEL            1378
#define IDC_IOREAD_L                    1378
#define IDC_IOWRITE_L                   1379
#define IDC_IOOTHER_L                   1380
#define IDC_VIEWCOMMANDLINE             1381
#define IDC_DELETE                      1382
#define IDC_EDIT                        1383
#define IDC_NEW                         1384
#define IDC_HANDLESEARCH                1385
#define IDC_SEARCH                      1387
#define IDC_FILTEROPTIONS               1389
#define IDC_FILTERTYPE                  1390
#define IDC_TREELIST                    1391
#define IDC_SECTIONTREE                 1393
#define IDC_INFO                        1396
#define IDC_DEFSTATE                    1398
#define IDC_SETTINGS                    1399
#define IDC_PLUGINTREE                  1400
#define IDC_DISABLED                    1401
#define IDC_LIST_DISABLED               1402
#define IDC_COLUMNSETLIST               1403
#define IDC_STATISTICS_LIST             1404
#define IDC_FLUSH                       1406
#define IDC_POSITION                    1407
#define IDC_FILESIZE                    1408
#define IDC_FILETYPE                    1409
#define IDC_FILEMODE                    1410
#define IDC_DEFAULTPERM                 1410
#define IDC_DUMPSTACK                   1411
#define IDC_COMPRESS                    1412
#define IDC_USERMODE                    1413
#define IDC_HYPERVISOR                  1414
#define IDC_SIZESINBYTES                1415
#define IDC_FONTMONOSPACE               1416
#define IDC_ONLYKERNELTHREADSTACKS      1417
#define IDC_HYPERVISORNONESSENTIAL      1418
#define IDC_INPUT                       1419
#define IDC_MINIDUMP_NORMAL             1420
#define IDC_MINIDUMP_WITH_DATA_SEGS     1421
#define IDC_MINIDUMP_WITH_FULL_MEM      1422
#define IDC_MINIDUMP_WITH_HANDLE_DATA   1423
#define IDC_MINIDUMP_FILTER_MEMORY      1424
#define IDC_MINIDUMP_SCAN_MEMORY        1425
#define IDC_MINIDUMP_WITH_UNLOADED_MODULES 1426
#define IDC_MINIDUMP_WITH_INDIRECT_REFERENCED_MEM 1427
#define IDC_MINIDUMP_FILTER_MODULE_PATHS 1428
#define IDC_MINIDUMP_WITH_PROC_THRD_DATA 1429
#define IDC_MINIDUMP_WITH_PRIVATE_RW_MEM 1430
#define IDC_MINIDUMP_WITHOUT_OPTIONAL_DATA 1431
#define IDC_MINIDUMP_WITH_FULL_MEM_INFO 1432
#define IDC_MINIDUMP_WITH_THRD_INFO     1433
#define IDC_MINIDUMP_WITH_CODE_SEGS     1434
#define IDC_MINIDUMP_WITHOUT_AUXILIARY_STATE 1435
#define IDC_MINIDUMP_WITH_FULL_AUXILIARY_STATE 1436
#define IDC_MINIDUMP_WITH_PRIVATE_WRITE_COPY_MEM 1437
#define IDC_MINIDUMP_IGNORE_INACCESSIBLE_MEM 1438
#define IDC_MINIDUMP_WITH_TOKEN_INFO    1439
#define IDC_MINIDUMP_WITH_MODULE_HEADERS 1440
#define IDC_MINIDUMP_FILTER_TRIAGE      1441
#define IDC_MINIDUMP_WITH_AVXX_STATE_CONTEXT 1442
#define IDC_MINIDUMP_WITH_IPT_TRACE     1443
#define IDC_MINIDUMP_SCAN_INACCESSIBLE_PARTIAL_PAGES 1444
#define IDC_MINIDUMP_FILTER_WRITE_COMBINE_MEM 1445
#define IDC_ZMEMSLOTS_V                 1446
#define IDC_ZMEMFORMFACTOR_V            1447
#define IDC_ZMEMTYPE_V                  1448
#define IDC_ZMEMTECHNOLOGY_V            1449
#define IDC_ZMEMSPEED_V                 1450
#define IDC_ZL1CACHE_V                  1451
#define IDC_ZL2CACHE_V                  1452
#define IDC_ZL3CACHE_V                  1453
#define IDC_CAPTURE                     1454
#define IDC_HOTKEYS_LIST_VIEW           1455
#define IDC_HOTKEYS_HOTKEY              1456
#define IDC_HOTKEYS_ASSIGN              1457
#define IDC_HOTKEYS_RESET               1458
#define IDC_CPUEX_CONTEXTSWITCHES_L     1459
#define IDC_CPUEX_INTERRUPTS_L          1460
#define IDC_CPUEX_DPCS_L                1461
#define IDC_CPUEX_SYSTEMCALLS_L         1462
#define IDC_CPUEX_EXCEPTIONDISPATCHES_L 1464
#define IDC_ZCPUEX_CONTEXTSWITCHESDELTA_V 1465
#define IDC_ZCPUEX_INTERRUPTSDELTA_V    1466
#define IDC_ZCPUEX_DPCSDELTA_V          1467
#define IDC_ZCPUEX_SYSTEMCALLSDELTA_V   1468
#define IDC_ZCPUEX_EXCEPTIONDISPATCHESDELTA_V 1469
#define IDC_ZCPUEX_CONTEXTSWITCHES_V    1470
#define IDC_ZCPUEX_INTERRUPTS_V         1471
#define IDC_ZCPUEX_DPCS_V               1472
#define IDC_ZCPUEX_SYSTEMCALLS_V        1473
#define IDC_ZCPUEX_EXCEPTIONDISPATCHES_V 1474
#define IDC_ENABLE_WINDOW_BORDER_COLOR  1475
#define IDC_GDI_TOTAL_SIZE              1476
#define IDC_GAME_DISPLAYNAME            1477
#define IDC_GAME_DESCRIPTION            1478
#define IDC_GAME_CATEGORY               1479
#define IDC_GAME_PROPERTIES             1487
#define IDC_EDITTEXT                    1488
#define IDC_GAME_MAXCPUCOUNT            1490
#define IDC_GAME_EXCLUSIVECPUS          1491
#define IDC_GAME_GPUTIME                1492
#define IDC_GAME_GPUMEMORY              1493
#define IDC_GAME_COMPOSITORMEMORY       1494
#define IDC_VIEWTAB                     1501
#define IDC_TOOL_REFRESH                1502
#define IDC_TOOL_COPY                   1503
#define IDC_TOOL_OPENFOLDER             1504
#define IDC_TOOL_PULL                   1505
#define IDC_TOOL_TAG                    1506
#define IDC_TOOL_DELETE                 1507
#define IDC_TREE                        1508
#define IDC_DETAILTAB                   1509
#define IDC_LABELLIST                   1510
#define IDC_DETAILEDIT                  1511
#define IDC_LAYERLIST                   1512
#define IDC_CONNECTIONTYPE              1513
#define IDC_SHOWALLUSERS                1514
#define IDC_LISTMODE                    1515
#define IDC_ENV_ADD                     1530
#define IDC_ENV_EDIT                    1531
#define IDC_ENV_DELETE                  1532
#define IDC_ENV_NEW                     1533
#define IDC_ENV_BROWSE                  1534
#define IDC_ENV_MOVEUP                  1535
#define IDC_ENV_MOVEDOWN                1536
#define IDC_ENV_EDITTEXT                1537
#define IDC_ENV_NAME                    1538
#define IDC_ENV_VALUE                   1539
#define IDC_TREEMODE                    1516
#define IDC_SUPPORTED                   1517
#define IDC_TRAYICON_LAZYSTART          1520
#define IDC_TRAYICON_PERSISTLAYOUT      1521
#define IDC_TRAYICON_TRANSPARENTICONS   1522
#define IDC_TRAYICON_SINGLECLICK        1523
#define IDC_TRAYICON_RESETLAYOUT        1524
#define IDC_TRAYICON_NOTIFYLIST         1525
#define IDC_TRAYICON_NOTIFYENABLEALL    1526
#define IDC_TRAYICON_NOTIFYDISABLEALL   1527
#define IDC_TRAYICON_ICONLIST           1528
#define ID_OCIIMAGE_RUN                 1520
#define ID_OCIIMAGE_RUNINTERACTIVE      1521
#define ID_OCIIMAGE_PULL                1522
#define ID_OCIIMAGE_PRUNE               1523
#define ID_OCIIMAGE_TAG                 1524
#define ID_OCIIMAGE_DELETE              1525
#define ID_OCICONTAINER_RESUME          1526
#define ID_OCICONTAINER_PAUSE           1527
#define ID_OCICONTAINER_TERMINATE       1528
#define ID_OCICONTAINER_PROPERTIES      1529
#define ID_HACKER_EXIT                  10001
#define ID_PROCESS_DUMP_MINIMAL         10002
#define ID_PROCESS_DUMP_LIMITED         10003
#define ID_PROCESS_DUMP_NORMAL          10004
#define ID_PROCESS_DUMP_FULL            10005
#define ID_PROCESS_PROPERTIES           10006
#define ID_PROCESS_TERMINATE            10007
#define ID_PROCESS_SUSPEND              10008
#define ID_PROCESS_RESUME               10009
#define ID_HACKER_SAVE                  10010
#define ID_THREAD_TERMINATE             10011
#define ID_THREAD_SUSPEND               10012
#define ID_THREAD_RESUME                10013
#define ID_THREAD_PERMISSIONS           10015
#define ID_THREAD_TOKEN                 10016
#define ID_ANALYZE_WAIT                 10018
#define ID_PROCESS_DUMP_CUSTOM          10019
#define ID_PRIORITY_TIMECRITICAL        10020
#define ID_PRIORITY_HIGHEST             10021
#define ID_PRIORITY_ABOVENORMAL         10022
#define ID_PRIORITY_NORMAL              10023
#define ID_PRIORITY_BELOWNORMAL         10024
#define ID_PRIORITY_LOWEST              10025
#define ID_PRIORITY_IDLE                10026
#define ID_IOPRIORITY_VERYLOW           10028
#define ID_IOPRIORITY_LOW               10029
#define ID_IOPRIORITY_NORMAL            10030
#define ID_IOPRIORITY_HIGH              10031
#define ID_PROCESS_RESTART              10032
#define ID_PROCESS_VIRTUALIZATION       10034
#define ID_PROCESS_AFFINITY             10035
#define ID_PROCESS_CREATEDUMPFILE       10036
#define ID_PROCESS_PRIORITYCLASS        10037
#define ID_MISCELLANEOUS_SETCRITICAL    10038
#define ID_MISCELLANEOUS_DETACHFROMDEBUGGER 10039
#define ID_PROCESS_IOPRIORITY           10040
#define ID_PROCESS_MISCELLANEOUS        10041
#define ID_PROCESS_WINDOW               10042
#define ID_PROCESS_PAGEPRIORITY         10043
#define ID_PRIORITY_REALTIME            10048
#define ID_PRIORITY_HIGH                10049
#define ID_MISCELLANEOUS_ACTIVITY       10050
#define ID_MISCELLANEOUS_ECOMODE        10051
#define ID_WINDOW_BRINGTOFRONT          10055
#define ID_WINDOW_RESTORE               10056
#define ID_WINDOW_MINIMIZE              10057
#define ID_WINDOW_MAXIMIZE              10058
#define ID_WINDOW_CLOSE                 10059
#define ID_PROCESS_SEARCHONLINE         10060
#define ID_HANDLE_CLOSE                 10061
#define ID_HANDLE_PROTECTED             10062
#define ID_HANDLE_INHERIT               10063
#define ID_HANDLE_PROPERTIES            10064
#define ID_HANDLE_SECURITY              10065
#define ID_MODULE_UNLOAD                10066
#define ID_MODULE_PROPERTIES            10068
#define ID_PROCESS_TERMINATETREE        10069
#define ID_PROCESS_SUSPENDTREE          10070
#define ID_PROCESS_RESUMETREE           10071
#define ID_THREAD_INSPECT               10075
#define ID_HACKER_RUN                   10076
#define ID_HACKER_RUNASADMINISTRATOR    10077
#define ID_HACKER_RUNAS                 10078
#define ID_HACKER_SHOWDETAILSFORALLPROCESSES 10079
#define ID_HACKER_RUNASPACKAGE          10080
#define ID_HACKER_FINDHANDLESORDLLS     10082
#define ID_HACKER_OPTIONS               10083
#define ID_PROCESS_FREEZE               10084
#define ID_PROCESS_THAW                 10085
#define ID_THREAD_FREEZE                10086
#define ID_THREAD_THAW                  10087
#define ID_VIEW_SYSTEMINFORMATION       10091
#define ID_TRAYICONS_CPUHISTORY         10093
#define ID_TRAYICONS_CPUUSAGE           10094
#define ID_TRAYICONS_COMMITHISTORY      10096
#define ID_TRAYICONS_PHYSICALMEMORYHISTORY 10097
#define ID_VIEW_REFRESH                 10098
#define ID_TOOLS_USER_LIST              10099
#define ID_TOOLS_THREADSTACKS           10100
#define ID_TOOLS_CREATESERVICE          10101
#define ID_TOOLS_ZOMBIEPROCESSES        10102
#define ID_TOOLS_INSPECTEXECUTABLEFILE  10103
#define ID_HELP_LOG                     10104
#define ID_HELP_DONATE                  10105
#define ID_HELP_ABOUT                   10106
#define ID_SERVICE_GOTOPROCESS          10107
#define ID_SERVICE_START                10108
#define ID_SERVICE_CONTINUE             10109
#define ID_SERVICE_PAUSE                10110
#define ID_SERVICE_STOP                 10111
#define ID_SERVICE_DELETE               10112
#define ID_SERVICE_PROPERTIES           10113
#define ID_SERVICE_OPENKEY              10114
#define ID_PRIVILEGE_ENABLE             10116
#define ID_PRIVILEGE_DISABLE            10117
#define ID_PRIVILEGE_REMOVE             10118
#define ID_OBJECT_CLOSE                 10119
#define ID_OBJECT_PROPERTIES            10120
#define ID_HELP_DEBUGCONSOLE            10122
#define ID_TOOLS_PAGEFILES              10126
#define ID_USER_DISCONNECT              10127
#define ID_USER_LOGOFF                  10128
#define ID_USER_SENDMESSAGE             10129
#define ID_USER_PROPERTIES              10130
#define ID_USERS_DUMMY                  10131
#define ID_PROCESS_DEBUG                10133
#define ID_USER_CONNECT                 10138
#define ID_NETWORK_GOTOPROCESS          10139
#define ID_NETWORK_CLOSE                10140
#define ID_OPACITY_10                   10142
#define ID_OPACITY_20                   10143
#define ID_OPACITY_30                   10144
#define ID_OPACITY_40                   10145
#define ID_OPACITY_50                   10146
#define ID_OPACITY_60                   10147
#define ID_OPACITY_70                   10148
#define ID_OPACITY_80                   10149
#define ID_OPACITY_90                   10150
#define ID_OPACITY_OPAQUE               10151
#define ID_VIEW_ALWAYSONTOP             10153
#define ID_UPDATEINTERVAL_FAST          10155
#define ID_UPDATEINTERVAL_NORMAL        10156
#define ID_UPDATEINTERVAL_BELOWNORMAL   10157
#define ID_UPDATEINTERVAL_SLOW          10158
#define ID_UPDATEINTERVAL_VERYSLOW      10159
#define ID_COMPUTER_LOCK                10160
#define ID_COMPUTER_LOGOFF              10161
#define ID_COMPUTER_SLEEP               10162
#define ID_COMPUTER_HIBERNATE           10163
#define ID_COMPUTER_RESTART             10164
#define ID_COMPUTER_SHUTDOWN            10165
#define ID_COMPUTER_RESTART_NATIVE      10166
#define ID_COMPUTER_SHUTDOWN_NATIVE     10167
#define ID_COMPUTER_RESTART_CRITICAL    10168
#define ID_COMPUTER_SHUTDOWN_CRITICAL   10169
#define ID_COMPUTER_RESTART_UPDATE      10170
#define ID_COMPUTER_SHUTDOWN_UPDATE     10171
#define ID_TRAYICONS_IOHISTORY          10172
#define ID_ICON_EXIT                    10173
#define ID_ICON_SHOWHIDEPROCESSHACKER   10174
#define ID_ICON_SYSTEMINFORMATION       10175
#define ID_PROCESSES_DUMMY              10177
#define ID_NOTIFICATIONS_ENABLEALL      10178
#define ID_NOTIFICATIONS_DISABLEALL     10179
#define ID_NOTIFICATIONS_NEWPROCESSES   10180
#define ID_NOTIFICATIONS_TERMINATEDPROCESSES 10181
#define ID_NOTIFICATIONS_NEWSERVICES    10182
#define ID_NOTIFICATIONS_STARTEDSERVICES 10183
#define ID_NOTIFICATIONS_STOPPEDSERVICES 10184
#define ID_NOTIFICATIONS_DELETEDSERVICES 10185
#define ID_NOTIFICATIONS_MODIFIEDSERVICES 10186
#define ID_MISCELLANEOUS_LOCKS          10187
#define ID_MISCELLANEOUS_GDIHANDLES     10188
#define ID_MISCELLANEOUS_HEAPS          10189
#define ID_ESC_EXIT                     10190
#define ID_NOTIFICATIONS_ARRIVEDDEVICES 10191
#define ID_NOTIFICATIONS_REMOVEDDEVICES 10192
#define ID_PROCESS_COPY                 10194
#define ID_THREAD_COPY                  10195
#define ID_NETWORK_COPY                 10197
#define ID_SERVICE_COPY                 10198
#define ID_MODULE_COPY                  10199
#define ID_HANDLE_COPY                  10200
#define ID_OBJECT_COPY                  10201
#define ID_MEMORY_SAVE                  10208
#define ID_MEMORY_CHANGEPROTECTION      10209
#define ID_MEMORY_FREE                  10210
#define ID_MEMORY_DECOMMIT              10211
#define ID_MEMORY_COPY                  10213
#define ID_MEMORY_READWRITEMEMORY       10214
#define ID_MEMORY_EMPTYWORKINGSET       10215
#define ID_FILTER_CONTAINS              10216
#define ID_FILTER_CONTAINS_CASEINSENSITIVE 10218
#define ID_FILTER_REGEX                 10219
#define ID_FILTER_REGEX_CASEINSENSITIVE 10221
#define ID_TAB_NEXT                     10223
#define ID_TAB_PREV                     10224
#define ID_VIEW_COLLAPSEALL             10225
#define ID_VIEW_EXPANDALL               10226
#define ID_MISCELLANEOUS_RUNAS          10229
#define ID_MISCELLANEOUS_RUNASTHISUSER  10230
#define ID_MISCELLANEOUS_PAGESMODIFIED  10231
#define ID_VIEW_HIDEPROCESSESFROMOTHERUSERS 10232
#define ID_MISCELLANEOUS_FLUSHHEAPS     10233
#define ID_THREAD_AFFINITY              10233
#define ID_THREAD_BOOST                 10234
#define ID_VIEW_HIDESIGNEDPROCESSES     10234
#define ID_VIEW_UPDATEAUTOMATICALLY     10235
#define ID_HACKER_RUNASLIMITEDUSER      10236
#define ID_USER_REMOTECONTROL           10237
#define ID_VIEW_HIDEMICROSOFTPROCESSES  10238
#define ID_PAGEPRIORITY_NORMAL          10239
#define ID_PAGEPRIORITY_BELOWNORMAL     10240
#define ID_PAGEPRIORITY_MEDIUM          10241
#define ID_PAGEPRIORITY_LOW             10242
#define ID_PAGEPRIORITY_VERYLOW         10243
#define ID_VIEW_SHOWCPUBELOW001         10246
#define ID_MODULE_OPENFILELOCATION      10247
#define ID_PROCESS_OPENFILELOCATION     10248
#define ID_MISCELLANEOUS_REDUCEWORKINGSET 10249
#define IDC_BACK                        10255
#define ID_VIEW_ORGANIZECOLUMNSETS      10256
#define ID_VIEW_SAVECOLUMNSET           10257
#define ID_VIEW_LOADCOLUMNSET           10258
#define ID_VIEW_SORTROOTPROCESSES       10262
#define ID_DIGIT1                       10263
#define ID_DIGIT2                       10264
#define ID_DIGIT3                       10265
#define ID_DIGIT4                       10266
#define ID_DIGIT5                       10267
#define ID_DIGIT6                       10268
#define ID_DIGIT7                       10269
#define ID_DIGIT8                       10270
#define ID_DIGIT9                       10271
#define ID_VIEW_HIDEWAITINGCONNECTIONS  10272
#define ID_VIEW_HIDEDRIVERSERVICES      10273
#define ID_VIEW_HIDEMICROSOFTSERVICES   10274
#define ID_VIEW_SECTIONPLACEHOLDER      10274
#define ID_VIEW_SCROLLTONEWPROCESSES    10275
#define ID_VIEW_SORTCHILDPROCESSES      10276
#define ID_TOOLS_STARTTASKMANAGER       10277
#define ID_COMPUTER_SHUTDOWNHYBRID      10278
#define ID_COMPUTER_RESTARTADVOPTIONS   10279
#define ID_COMPUTER_RESTARTBOOTOPTIONS  10280
#define ID_COMPUTER_RESTARTFWOPTIONS    10281
#define ID_COMPUTER_RESTARTFWDEVICE     10282
#define ID_HANDLE_OBJECTPROPERTIES1     10282
#define ID_COMPUTER_RESTARTBOOTDEVICE   10283
#define ID_HANDLE_OBJECTPROPERTIES2     10283
#define ID_OBJECT_GOTOOWNINGPROCESS     10284
#define ID_COMPUTER_RESTARTWDOSCAN      10284
#define ID_NETWORK_GOTOSERVICE          10285
#define ID_SERVICE_OPENFILELOCATION     10286
#define ID_PROCESS_GOTOPROCESS          10287
#define ID_MINIINFO_REFRESH             10288
#define ID_MINIINFO_REFRESHAUTOMATICALLY 10289
#define ID_TOOLS_STARTRESOURCEMONITOR   10289
#define ID_TOOLS_STARTPERFORMANCEMONITOR 10290
#define ID_TOOLS_SHUTDOWNWSLPROCESSES   10291
#define ID_HANDLE_GOTOOWNINGPROCESS     10292
#define IDC_MAXSCREEN                   10293
#define ID_TOOLS_GAMES                  10294
#define ID_PRIVILEGE_RESET              10296
#define ID_GROUP_ENABLE                 10297
#define ID_THREAD_CRITICAL              10297
#define ID_GROUP_DISABLE                10298
#define ID_GROUP_RESET                  10299
#define ID_TOOLS_SCM_PERMISSIONS        10300
#define ID_TOOLS_RDP_PERMISSIONS        10301
#define ID_TOOLS_PWR_PERMISSIONS        10302
#define ID_TOOLS_WMI_PERMISSIONS        10303
#define ID_TOOLS_DESKTOP_PERMISSIONS    10304
#define ID_TOOLS_STATION_PERMISSIONS    10305
#define ID_UIACCESS_REMOVE              10306
#define ID_TOOLS_LIVEDUMP               10307
#define ID_NOTIFICATIONS_ENABLEDELAYSTART 10308
#define ID_NOTIFICATIONS_ENABLEPERSISTLAYOUT 10309
#define ID_NOTIFICATIONS_RESETPERSISTLAYOUT 10310
#define ID_NOTIFICATIONS_ENABLETRANSPARENTICONS 10311
#define ID_NOTIFICATIONS_ENABLESINGLECLICKICONS 10312
#define ID_MISCELLANEOUS_EXECUTIONREQUIRED 10313
#define IDD_OBJAFDSOCKET                10314
#define ID_TOOLS_COM_ACCESS_PERMISSIONS 10315
#define ID_TOOLS_COM_ACCESS_RESTRICTIONS 10316
#define ID_TOOLS_COM_LAUNCH_PERMISSIONS 10317
#define ID_TOOLS_COM_LAUNCH_RESTRICTIONS 10318
#define ID_TOOLS_INFORMER               10319
#define ID_THREAD_STACK_SCAN            10319
#define ID_PROCESS_MITIGATION           10320
#define ID_TOOLS_GDI_HANDLE_TABLE       10321
#define ID_TOOLS_USER_HANDLE_TABLE      10322
#define ID_THREAD_REGISTERS             10324
#define ID_TOOLS_RUNCONTAINER           10325
#define ID_HACKER_ATTACHTOPROCESS       10326
#define ID_TOOLS_ENVIRONMENT_VARIABLES  10327

#define IDS_PH_RESET_ALL_SETTINGS                    2000
#define IDS_PH_CLEAN_UNUSED_SETTINGS                 2001
#define IDS_PH_RESTART_REQUIRED                      2002
#define IDS_PH_RESTART_PROMPT                        2003
#define IDS_PH_UNABLE_REPLACE_TASK_MANAGER           2004
#define IDS_PH_UNABLE_ENABLE_START_AS_ADMIN          2005
#define IDS_PH_INSECURE_INSTALL_TITLE                2006
#define IDS_PH_INSECURE_INSTALL_CONTENT              2007
#define IDS_PH_UNABLE_CONFIGURE_OPTION               2008
#define IDS_PH_TRAY_ICON_REQUIRED                    2009
#define IDS_PH_UNABLE_ENABLE_START_AS_ADMIN_OPTION   2010
#define IDS_PH_ADMIN_REQUIRED                        2011
#define IDS_PH_UNSUPPORTED_SCHEMA_VALUE              2012
#define IDS_PH_UNSUPPORTED_SCHEMA_VALUE_CONTENT      2013
#define IDS_PH_RESTORE_DEFAULT_TASK_MANAGER           2014
#define IDS_PH_MAKE_DEFAULT_TASK_MANAGER              2015
#define IDS_PH_CHANGE_DEFAULT_TASK_MANAGER_ACTION     2016
#define IDS_PH_ENABLE_START_AS_ADMIN_ACTION           2017
#define IDS_PH_WARNING_TITLE                          2018
#define IDS_PH_WOW64_WARNING                          2019
#define IDS_PH_UNABLE_CREATE_WINDOW                   2020
#define IDS_PH_UNABLE_CONFIGURE_TERMINATION_POLICY    2021
#define IDS_PH_PROCESS_DOES_NOT_EXIST                 2022
#define IDS_PH_SERVICE_DOES_NOT_EXIST                 2023
#define IDS_PH_UNABLE_LOCATE_FILE                     2024
#define IDS_PH_UNABLE_CREATE_FILE                     2025
#define IDS_PH_UNABLE_OPEN_PROCESS                    2026
#define IDS_PH_UNABLE_PERFORM_OPERATION               2027
#define IDS_PH_UNABLE_FREE_MEMORY_REGION              2028
#define IDS_PH_UNABLE_DECOMMIT_MEMORY_REGION          2029
#define IDS_PH_UNABLE_UNMAP_SECTION_VIEW              2030
#define IDS_PH_UNKNOWN_ERROR_OCCURRED                  2031
#define IDS_PH_ENABLE_SIGNATURE_CHECKING               2032
#define IDS_PH_UNKNOWN_ERROR                           2033
#define IDS_PH_UNABLE_ENUMERATE_PROCESSES              2034
#define IDS_PH_UNABLE_CLOSE_TCP_CONNECTION             2035
#define IDS_PH_UNABLE_EDIT_MEMORY                      2036
#define IDS_PH_UNABLE_EDIT_MEMORY_REGION               2037
#define IDS_PH_UNABLE_DETERMINE_THREAD_WAIT            2038
#define IDS_PH_UNABLE_EMPTY_MEMORY_LIST                2039
#define IDS_PH_UNABLE_EMPTY_REGION_WORKING_SET         2040
#define IDS_PH_UNABLE_ENUMERATE_PROCESS_HANDLES        2041
#define IDS_PH_UNABLE_DUPLICATE_TOKEN                  2042
#define IDS_PH_UNABLE_CHANGE_MEMORY_PROTECTION         2043
#define IDS_PH_UNABLE_CLOSE_WINDOW                     2044
#define IDS_PH_UNABLE_QUERY_HEAP_INFORMATION            2045
#define IDS_PH_UNABLE_QUERY_LOCK_INFORMATION            2046
#define IDS_PH_UNABLE_SEARCH_FOR_STRINGS                2047
#define IDS_PH_UNABLE_CREATE_SEARCH_THREAD              2048
#define IDS_PH_UNABLE_ANALYZE_THREAD                    2049
#define IDS_PH_UNABLE_SHOW_PROCESS_PROPERTIES           2050
#define IDS_PH_UNABLE_CHANGE_SERVICE_CONFIGURATION      2051
#define IDS_PH_UNABLE_CREATE_SERVICE                    2052
#define IDS_PH_UNABLE_SHUTDOWN_WSL                      2053
#define IDS_PH_UNABLE_SAVE_APPLICATION_SETTINGS         2054
#define IDS_PH_UNABLE_FIND_MEMORY_REGION                2055
#define IDS_PH_UNABLE_OPEN_FILE_LOCATION                2056
#define IDS_PH_UNABLE_OPEN_FILE_PROPERTIES              2057
#define IDS_PH_UNABLE_LOAD_STACK                        2058
#define IDS_PH_UNABLE_REFRESH_STACK                     2059
#define IDS_PH_UNABLE_QUERY_PAGEFILE_INFORMATION        2060
#define IDS_PH_MINIMUM_STRING_LENGTH                    2061
#define IDS_PH_MEMORY_TYPE_REQUIRED                     2062
#define IDS_PH_THREAD_NOT_WAITING                       2063
#define IDS_PH_PROCESS_RECORD_ONLY                      2064
#define IDS_PH_BINARY_PATH_EMPTY                        2065
#define IDS_PH_OBJECT_UNNAMED                           2066
#define IDS_PH_UNABLE_OPEN_KEY                          2067
#define IDS_PH_UNABLE_QUERY_32BIT_HEAP_INFORMATION      2068
#define IDS_PH_32BIT_VERSION_NOT_FOUND                  2069
#define IDS_PH_UNABLE_OPEN_THREAD                       2070
#define IDS_PH_UNABLE_MAP_SECTION_VIEW                  2071
#define IDS_PH_SECTION_VIEW_TRUNCATED                   2072
#define IDS_PH_UNABLE_QUERY_SECTION                     2073
#define IDS_PH_64BIT_DUMP_FALLBACK                      2074
#define IDS_PH_UNABLE_HIBERNATE_COMPUTER                2075
#define IDS_PH_UNABLE_RESTART_COMPUTER                  2076
#define IDS_PH_UNABLE_SHUT_DOWN_COMPUTER                2077
#define IDS_PH_UNABLE_SLEEP_COMPUTER                    2078
#define IDS_PH_UNABLE_LOCK_COMPUTER                     2079
#define IDS_PH_UNABLE_LOG_OFF_COMPUTER                  2080
#define IDS_PH_UNABLE_CONNECT_SESSION                   2081
#define IDS_PH_UNABLE_DISCONNECT_SESSION                2082
#define IDS_PH_UNABLE_LOGOFF_SESSION                    2083
#define IDS_PH_UNABLE_REMOTE_CONTROL_SESSION            2084
#define IDS_PH_UNABLE_SHADOW_SESSION                    2085
#define IDS_PH_UNABLE_SEND_MESSAGE                      2086
#define IDS_PH_UNABLE_DETACH_DEBUGGER                   2087
#define IDS_PH_UNABLE_CONFIGURE_ADVANCED_BOOT           2088
#define IDS_PH_UNABLE_CONFIGURE_BOOT_APPLICATION        2089
#define IDS_PH_CANNOT_CONTROL_CURRENT_SESSION           2090
#define IDS_PH_PROCESS_NOT_DEBUGGED                     2091
#define IDS_PH_UNABLE_RESTART_FIRMWARE_OPTIONS          2092
#define IDS_PH_ADMIN_PRIVILEGES_REQUIRED                2093
#define IDS_PH_UEFI_NOT_SUPPORTED                       2094
#define IDS_PH_UNABLE_CREATE_KERNEL_MINIDUMP             2095
#define IDS_PH_KERNEL_MINIDUMP_ADMIN_REQUIRED            2096
#define IDS_PH_UNABLE_ACCESS_DUMP_FILE                   2097
#define IDS_PH_UNABLE_CREATE_MINIDUMP                    2098
#define IDS_PH_UNABLE_CHANGE_AFFINITY_SETTINGS           2099
#define IDS_PH_UNABLE_CREATE_LIVE_KERNEL_DUMP            2100
#define IDS_PH_UNABLE_PERFORM_SCAN                       2101
#define IDS_PH_UNABLE_SET_ENVIRONMENT_VARIABLE           2102
#define IDS_PH_UNABLE_DELETE_ENVIRONMENT_VARIABLE        2103
#define IDS_PH_UNABLE_DISABLE_UIACCESS                   2104
#define IDS_PH_UNABLE_SET_INTEGRITY_LEVEL                2105
#define IDS_PH_UNABLE_READ_MEMORY                        2106
#define IDS_PH_UNABLE_WRITE_MEMORY                       2107
#define IDS_PH_UNABLE_SET_INTEGRITY_LABEL                2108
#define IDS_PH_UNABLE_TERMINATE_PROCESS                  2109
#define IDS_PH_UNABLE_CREATE_PROCESS_STRUCTURE           2110
#define IDS_PH_UNABLE_TERMINATE_JOB                      2111
#define IDS_PH_UNABLE_ADD_PROCESS_TO_JOB                 2112
#define IDS_PH_UNABLE_TERMINATE_TASK                     2113
#define IDS_PH_UNABLE_CLONE_PROCESS                      2114
#define IDS_PH_UNABLE_UPDATE_LENGTH                      2115
#define IDS_PH_UNABLE_QUERY_PROCESS                      2116
#define IDS_PH_UNABLE_START_PROGRAM                      2117
#define IDS_PH_CPU_SELECTION_REQUIRED                    2118
#define IDS_PH_MINIMUM_LENGTH_INVALID                    2119
#define IDS_PH_UNABLE_START_EXECUTION_ALIAS              2120
#define IDS_PH_UNABLE_CHANGE_THREAD_CRITICAL_STATUS       2121
#define IDS_PH_UNABLE_SAVE_LIVE_KERNEL_DUMP               2122
#define IDS_PH_UNABLE_QUERY_CURRENT_AFFINITY               2123
#define IDS_PH_UNABLE_OPEN_TOKEN                           2124
#define IDS_PH_UNABLE_EXECUTE_COMMAND                      2125
#define IDS_PH_INVALID_VALUE                               2126
#define IDS_PH_VALUE_RANGE_0_TO_64                         2127
#define IDS_PH_UNABLE_CHANGE_PROCESS_AFFINITY              2128
#define IDS_PH_UNABLE_CHANGE_THREAD_AFFINITY               2129
#define IDS_PH_UNABLE_UPDATE_THREAD_AFFINITY               2130
#define IDS_PH_UNABLE_UPDATE_THREAD_AFFINITY_CONTENT       2131
#define IDS_PH_UNABLE_APPLY_TOKEN_ACTION                   2132
#define IDS_PH_ACTION_SET                                  2133
#define IDS_PH_ACTION_ENABLE                               2134
#define IDS_PH_ACTION_DISABLE                              2135
#define IDS_PH_ACTION_RESET                                2136
#define IDS_PH_ACTION_REMOVE                               2137
#define IDS_PH_TOKEN_PRIVILEGE                             2138
#define IDS_PH_TOKEN_GROUP                                 2139
#define IDS_PH_UNABLE_TERMINATE_THREAD                     2140
#define IDS_PH_UNABLE_SUSPEND_THREAD                       2141
#define IDS_PH_UNABLE_RESUME_THREAD                        2142
#define IDS_PH_UNABLE_FREEZE_THREAD                        2143
#define IDS_PH_UNABLE_THAW_THREAD                          2144
#define IDS_PH_UNABLE_CHANGE_THREAD_BOOST_PRIORITY         2145
#define IDS_PH_UNABLE_SET_THREAD_BOOST_PRIORITY            2146
#define IDS_PH_UNABLE_CHANGE_THREAD_PRIORITY               2147
#define IDS_PH_UNABLE_SET_THREAD_PRIORITY                  2148
#define IDS_PH_UNABLE_SET_THREAD_IO_PRIORITY               2149
#define IDS_PH_UNABLE_SET_THREAD_PAGE_PRIORITY             2150
#define IDS_PH_UNABLE_EXECUTE_PROGRAM                      2151
#define IDS_PH_UNABLE_GET_PROCESS_START_KEY                2152
#define IDS_PH_HANDLE_ATTRIBUTES_REQUIRE_DRIVER            2153
#define IDS_PH_UNABLE_CLOSE_NAMED_OBJECT                   2154
#define IDS_PH_UNABLE_COMPILE_REGULAR_EXPRESSION           2155
#define IDS_PH_REGULAR_EXPRESSION_ERROR_POSITION           2156
#define IDS_PH_UNABLE_LOCATE_ROUTINES                      2157
#define IDS_PH_UNABLE_LOCATE_APPLICATION_DIRECTORY         2158
#define IDS_PH_UNABLE_OPEN_EVENT                           2159
#define IDS_PH_UNABLE_OPEN_EVENT_PAIR                      2160
#define IDS_PH_UNABLE_OPEN_SEMAPHORE                       2161
#define IDS_PH_UNABLE_OPEN_TIMER                           2162
#define IDS_PH_TOO_MANY_HANDLES                            2163
#define IDS_PH_TOO_MANY_HANDLES_HINT                       2164
#define IDS_PH_UNIDENTIFIED_THIRD_PARTY_OBJECT              2165
#define IDS_PH_UNABLE_UNLOAD_MODULE                        2166
#define IDS_PH_UNABLE_UNLOAD_NAMED_MODULE                  2167
#define IDS_PH_UNABLE_UNLOAD_NAMED_MODULE_ADMIN            2168
#define IDS_PH_UNABLE_UNMAP_SECTION_AT_ADDRESS             2169
#define IDS_PH_SERVICE_DELETION_WARNING                    2170
#define IDS_PH_PROCESS_VIRTUALIZATION_WARNING              2171
#define IDS_PH_REMOVE_PRIVILEGES_WARNING                   2172
#define IDS_PH_REMOVE_UIACCESS_WARNING                     2173
#define IDS_PH_ZOMBIE_TERMINATION_WARNING                  2174
#define IDS_PH_PROCESS_RESTART_NOTICE                      2175
#define IDS_PH_SIGNATURE_FILTER_REQUIRES_CHECKING          2176
#define IDS_PH_ERROR_WITH_DETAILS                          2182
#define IDS_PH_COMMAND_LINE_OPTIONS                        2183
#define IDS_PH_COMMAND_LINE_OPTIONS_CONTENT                2184
#define IDS_PH_UNABLE_INITIALIZE_DESKTOP_POLICY             2185
#define IDS_PH_UNABLE_LOAD_SETTINGS                         2186
#define IDS_PH_UNABLE_APPLY_PROCESS_ACTION_PID              2187
#define IDS_PH_UNABLE_APPLY_PROCESS_ACTION                  2188
#define IDS_PH_UNABLE_APPLY_NAMED_HANDLE_ACTION             2189
#define IDS_PH_UNABLE_APPLY_HANDLE_ACTION                   2190
#define IDS_PH_ACTION_TERMINATE                              2191
#define IDS_PH_ACTION_SUSPEND                                2192
#define IDS_PH_ACTION_RESUME                                 2193
#define IDS_PH_ACTION_FREEZE                                 2194
#define IDS_PH_ACTION_THAW                                   2195
#define IDS_PH_ACTION_RESTART                                2196
#define IDS_PH_ACTION_DEBUG                                  2197
#define IDS_PH_ACTION_REDUCE_WORKING_SET                     2198
#define IDS_PH_ACTION_EMPTY_WORKING_SET                      2199
#define IDS_PH_ACTION_SET_BACKGROUND_ACTIVITY_MODERATION     2200
#define IDS_PH_ACTION_SET_VIRTUALIZATION                     2201
#define IDS_PH_ACTION_SET_CRITICAL_STATUS                    2202
#define IDS_PH_ACTION_SET_ECO_MODE                           2203
#define IDS_PH_ACTION_CREATE_EXECUTION_REQUIRED              2204
#define IDS_PH_ACTION_DETACH_DEBUGGER                        2205
#define IDS_PH_ACTION_LOAD_DLL                               2206
#define IDS_PH_ACTION_SET_IO_PRIORITY                        2207
#define IDS_PH_ACTION_SET_PAGE_PRIORITY                      2208
#define IDS_PH_ACTION_SET_PRIORITY_CLASS                     2209
#define IDS_PH_ACTION_CHANGE_BOOST_PRIORITY                  2210
#define IDS_PH_ACTION_SET_BOOST_PRIORITY                     2211
#define IDS_PH_ACTION_FLUSH_PROCESS_HEAPS                    2212
#define IDS_PH_ACTION_CLOSE_HANDLE                           2213
#define IDS_PH_ACTION_SET_HANDLE_ATTRIBUTES                  2214
#define IDS_PH_PLUGIN_USER_NOTES_NAME                        2215
#define IDS_PH_PLUGIN_USER_NOTES_DESCRIPTION                 2216
#define IDS_PH_PLUGIN_EXTENDED_TOOLS_NAME                    2217
#define IDS_PH_PLUGIN_EXTENDED_TOOLS_DESCRIPTION             2218
#define IDS_PH_PLUGIN_EXTENDED_NOTIFICATIONS_NAME            2219
#define IDS_PH_PLUGIN_EXTENDED_NOTIFICATIONS_DESCRIPTION     2220
#define IDS_PH_PLUGIN_DOTNET_TOOLS_NAME                      2221
#define IDS_PH_PLUGIN_DOTNET_TOOLS_DESCRIPTION               2222
#define IDS_PH_PLUGIN_ONLINE_CHECKS_NAME                     2223
#define IDS_PH_PLUGIN_ONLINE_CHECKS_DESCRIPTION              2224
#define IDS_PH_PLUGIN_UPDATE_CHECKER_NAME                    2225
#define IDS_PH_PLUGIN_UPDATE_CHECKER_DESCRIPTION             2226
#define IDS_PH_PLUGIN_NETWORK_TOOLS_NAME                     2227
#define IDS_PH_PLUGIN_NETWORK_TOOLS_DESCRIPTION              2228
#define IDS_PH_PLUGIN_HARDWARE_DEVICES_NAME                  2229
#define IDS_PH_PLUGIN_HARDWARE_DEVICES_DESCRIPTION           2230
#define IDS_PH_PLUGIN_WINDOW_EXPLORER_NAME                   2231
#define IDS_PH_PLUGIN_WINDOW_EXPLORER_DESCRIPTION            2232
#define IDS_PH_PLUGIN_TOOL_STATUS_NAME                       2233
#define IDS_PH_PLUGIN_TOOL_STATUS_DESCRIPTION                2234
#define IDS_PH_PLUGIN_EXTENDED_SERVICES_NAME                 2235
#define IDS_PH_PLUGIN_EXTENDED_SERVICES_DESCRIPTION          2236
#define IDS_PH_PLUGIN_UNNAMED                                2237
#define IDS_PH_PLUGIN_VERSION_UNKNOWN                        2238
#define IDS_PH_PLUGIN_COLUMN                                 2239
#define IDS_PH_PLUGIN_DISABLED_COUNT                         2240
#define IDS_PH_PLUGIN_DISABLE                                2241
#define IDS_PH_PLUGIN_PROPERTIES                             2242
#define IDS_PH_PLUGIN_PROPERTY_COLUMN                        2243
#define IDS_PH_THEME_AUTOMATIC                              2244
#define IDS_PH_THEME_LIGHT                                  2245
#define IDS_PH_THEME_DARK                                   2246
#define IDS_PH_THEME_CUSTOM                                 2247
#define IDS_PH_LOGON_BATCH                                  2248
#define IDS_PH_LOGON_INTERACTIVE                            2249
#define IDS_PH_LOGON_NETWORK                                2250
#define IDS_PH_LOGON_NEW_CREDENTIALS                        2251
#define IDS_PH_LOGON_SERVICE                                2252
#define IDS_PH_HIDDEN_PROCESS_BRUTE_FORCE                    2253
#define IDS_PH_HIDDEN_PROCESS_CSR_HANDLES                    2254
#define IDS_PH_HIDDEN_PROCESS_ETW_HANDLES                    2255
#define IDS_PH_HIDDEN_PROCESS_PROCESS_HANDLES                2256
#define IDS_PH_HIDDEN_PROCESS_REGISTRY_HANDLES               2257
#define IDS_PH_HIDDEN_PROCESS_NTDLL_HANDLES                  2258
#define IDS_PH_FIND_EVERYTHING                              2259
#define IDS_PH_PROCESSOR_GROUP_FORMAT                        2260
#define IDS_PH_MESSAGE_ICON_NONE                             2261
#define IDS_PH_MESSAGE_ICON_INFORMATION                      2262
#define IDS_PH_MESSAGE_ICON_WARNING                          2263
#define IDS_PH_MESSAGE_ICON_ERROR                            2264
#define IDS_PH_MESSAGE_ICON_QUESTION                         2265
#define IDS_PH_BYTES_PER_ROW_FORMAT                          2266
#define IDS_PH_SERVICE_STOP                                 2267
#define IDS_PH_SERVICE_PAUSE                                2268
#define IDS_PH_SERVICE_CONTINUE                             2269
#define IDS_PH_SERVICE_START                                2270
#define IDS_PH_SESSION_KEY_BACKSPACE                        2271
#define IDS_PH_SESSION_KEY_DELETE                           2272
#define IDS_PH_SESSION_KEY_DOWN                             2273
#define IDS_PH_SESSION_KEY_END                              2274
#define IDS_PH_SESSION_KEY_ENTER                            2275
#define IDS_PH_SESSION_KEY_HOME                             2276
#define IDS_PH_SESSION_KEY_INSERT                           2277
#define IDS_PH_SESSION_KEY_LEFT                             2278
#define IDS_PH_SESSION_KEY_PAGE_DOWN                        2279
#define IDS_PH_SESSION_KEY_PAGE_UP                          2280
#define IDS_PH_SESSION_KEY_PRINT_SCREEN                     2281
#define IDS_PH_SESSION_KEY_RIGHT                            2282
#define IDS_PH_SESSION_KEY_SPACE                            2283
#define IDS_PH_SESSION_KEY_TAB                              2284
#define IDS_PH_SESSION_KEY_UP                               2285
#define IDS_PH_GROUP_ENERGY                                 2286
#define IDS_PH_GROUP_IMAGES_AND_DLLS                        2287
#define IDS_PH_GROUP_NOTIFICATIONS                          2288
#define IDS_PH_GROUP_TRAY_ICONS                             2289
#define IDS_PH_SESSION_USER_NAME                            2290
#define IDS_PH_SESSION_ID                                   2291
#define IDS_PH_SESSION_STATE                                2292
#define IDS_PH_SESSION_LOGON_TIME                           2293
#define IDS_PH_SESSION_CONNECT_TIME                         2294
#define IDS_PH_SESSION_DISCONNECT_TIME                      2295
#define IDS_PH_SESSION_LAST_INPUT_TIME                      2296
#define IDS_PH_SESSION_CLIENT_NAME                          2297
#define IDS_PH_SESSION_CLIENT_ADDRESS                       2298
#define IDS_PH_SESSION_CLIENT_DISPLAY                       2299
#define IDS_PH_HANDLE_SECURITY_OWNER                        2300
#define IDS_PH_HANDLE_SECURITY_GROUP                        2301
#define IDS_PH_HANDLE_SECURITY_INTEGRITY                    2302
#define IDS_PH_TRAY_NOTIFY_NEW_PROCESSES                    2303
#define IDS_PH_TRAY_NOTIFY_TERMINATED_PROCESSES             2304
#define IDS_PH_TRAY_NOTIFY_NEW_SERVICES                     2305
#define IDS_PH_TRAY_NOTIFY_STARTED_SERVICES                 2306
#define IDS_PH_TRAY_NOTIFY_STOPPED_SERVICES                 2307
#define IDS_PH_TRAY_NOTIFY_DELETED_SERVICES                 2308
#define IDS_PH_TRAY_NOTIFY_MODIFIED_SERVICES                2309
#define IDS_PH_TRAY_NOTIFY_ARRIVED_DEVICES                  2310
#define IDS_PH_TRAY_NOTIFY_REMOVED_DEVICES                  2311
#define IDS_PH_STATUS_TRUE                                  2312
#define IDS_PH_STATUS_FALSE                                 2313
#define IDS_PH_STATUS_ENABLED                               2314
#define IDS_PH_STATUS_DISABLED                              2315
#define IDS_PH_STATUS_ENABLED_MODIFIED                      2316
#define IDS_PH_STATUS_DISABLED_MODIFIED                     2317
#define IDS_PH_STATUS_YES                                   2318
#define IDS_PH_STATUS_NO                                    2319
#define IDS_PH_STATUS_NOT_ALLOWED                           2320
#define IDS_PH_STATUS_NOT_CAPABLE                           2321
#define IDS_PH_STATUS_VIRTUAL_MACHINE                       2322
#define IDS_PH_STATUS_DISABLED_HYPERV                       2323
#define IDS_PH_STATUS_UNDEFINED                             2324
#define IDS_PH_STATUS_NO_DRIVER                             2325
#define IDS_PH_STATUS_NO_SYMBOLS                            2326
#define IDS_PH_CREATING_DUMP_FILE                           2327
#define IDS_PH_RESOLVING_SYMBOLS                            2328
#define IDS_PH_SETTING_EDITOR                               2329
#define IDS_PH_FIND                                         2330
#define IDS_PH_CANCEL                                       2331
#define IDS_PH_MAKE_DEFAULT                                 2333
#define IDS_PH_RESTORE_DEFAULT                              2334
#define IDS_PH_NO_SCHEMA_DESCRIPTION                        2335
#define IDS_PH_NULL_VALUE                                   2336
#define IDS_PH_UNKNOWN_SID                                  2337
#define IDS_PH_UNNAMED_JOB                                  2338
#define IDS_PH_STATUS_NOT_ALLOWED_TITLE                     2339
#define IDS_PH_STAT_CPU                                     2340
#define IDS_PH_STAT_CPUUSER                                 2341
#define IDS_PH_STAT_CPUKERNEL                               2342
#define IDS_PH_STAT_CPUAVERAGE                              2343
#define IDS_PH_STAT_CPURELATIVE                             2344
#define IDS_PH_STAT_CYCLES                                  2345
#define IDS_PH_STAT_CYCLESDELTA                             2346
#define IDS_PH_STAT_CONTEXTSWITCHES                         2347
#define IDS_PH_STAT_CONTEXTSWITCHESDELTA                    2348
#define IDS_PH_STAT_KERNELTIME                              2349
#define IDS_PH_STAT_KERNELDELTA                             2350
#define IDS_PH_STAT_USERTIME                                2351
#define IDS_PH_STAT_USERDELTA                               2352
#define IDS_PH_STAT_TOTALTIME                               2353
#define IDS_PH_STAT_TOTALDELTA                              2354
#define IDS_PH_STAT_PRIORITY                                2355
#define IDS_PH_STAT_PRIVATEBYTES                            2356
#define IDS_PH_STAT_PRIVATEBYTESDELTA                       2357
#define IDS_PH_STAT_PEAKPRIVATEBYTES                        2358
#define IDS_PH_STAT_VIRTUALSIZE                             2359
#define IDS_PH_STAT_PEAKVIRTUALSIZE                         2360
#define IDS_PH_STAT_PAGEFAULTS                              2361
#define IDS_PH_STAT_PAGEFAULTSDELTA                         2362
#define IDS_PH_STAT_HARDFAULTS                              2363
#define IDS_PH_STAT_HARDFAULTSDELTA                         2364
#define IDS_PH_STAT_WORKINGSET                              2365
#define IDS_PH_STAT_PEAKWORKINGSET                          2366
#define IDS_PH_STAT_PRIVATEWS                               2367
#define IDS_PH_STAT_SHAREABLEWS                             2368
#define IDS_PH_STAT_SHAREDWS                                2369
#define IDS_PH_STAT_PAGEDPOOL                               2370
#define IDS_PH_STAT_PEAKPAGEDPOOL                           2371
#define IDS_PH_STAT_NONPAGED                                2372
#define IDS_PH_STAT_PEAKNONPAGED                            2373
#define IDS_PH_STAT_SHAREDCOMMIT                            2374
#define IDS_PH_STAT_PRIVATECOMMIT                           2375
#define IDS_PH_STAT_PEAKPRIVATECOMMIT                       2376
#define IDS_PH_STAT_PAGEPRIORITY                            2377
#define IDS_PH_STAT_READS                                   2378
#define IDS_PH_STAT_READSDELTA                              2379
#define IDS_PH_STAT_READBYTES                               2380
#define IDS_PH_STAT_READBYTESDELTA                          2381
#define IDS_PH_STAT_WRITES                                  2382
#define IDS_PH_STAT_WRITESDELTA                             2383
#define IDS_PH_STAT_WRITEBYTES                              2384
#define IDS_PH_STAT_WRITEBYTESDELTA                         2385
#define IDS_PH_STAT_OTHER                                   2386
#define IDS_PH_STAT_OTHERDELTA                              2387
#define IDS_PH_STAT_OTHERBYTES                              2388
#define IDS_PH_STAT_OTHERBYTESDELTA                         2389
#define IDS_PH_STAT_TOTALBYTES                              2390
#define IDS_PH_STAT_TOTALBYTESDELTA                         2391
#define IDS_PH_STAT_TOTALBYTESAVERAGE                       2392
#define IDS_PH_STAT_IOPRIORITY                              2393
#define IDS_PH_STAT_HANDLES                                 2394
#define IDS_PH_STAT_PEAKHANDLES                             2395
#define IDS_PH_STAT_GDIHANDLES                              2396
#define IDS_PH_STAT_PEAKGDIHANDLES                          2397
#define IDS_PH_STAT_USERHANDLES                             2398
#define IDS_PH_STAT_PEAKUSERHANDLES                         2399
#define IDS_PH_STAT_ENERGYATTRIBUTEDCYCLES                  2400
#define IDS_PH_STAT_ENERGYWORKONBEHALFCYCLES                2401
#define IDS_PH_STAT_ENERGYCYCLESHIGHUSER                    2402
#define IDS_PH_STAT_ENERGYCYCLESHIGHKERNEL                  2403
#define IDS_PH_STAT_ENERGYCYCLESABOVENORMALUSER             2404
#define IDS_PH_STAT_ENERGYCYCLESABOVENORMALKERNEL           2405
#define IDS_PH_STAT_ENERGYCYCLESNORMALUSER                  2406
#define IDS_PH_STAT_ENERGYCYCLESNORMALKERNEL                2407
#define IDS_PH_STAT_ENERGYCYCLESLOWUSER                     2408
#define IDS_PH_STAT_ENERGYCYCLESLOWKERNEL                   2409
#define IDS_PH_STAT_ENERGYDISK                              2410
#define IDS_PH_STAT_ENERGYDISKJOULES                        2411
#define IDS_PH_STAT_ENERGYDISKWATTHOURS                     2412
#define IDS_PH_STAT_ENERGYDISKWATTS                         2413
#define IDS_PH_STAT_ENERGYNETWORKTAIL                       2414
#define IDS_PH_STAT_ENERGYNETWORKTAILJOULES                 2415
#define IDS_PH_STAT_ENERGYNETWORKTAILWATTHOURS              2416
#define IDS_PH_STAT_ENERGYNETWORKTAILWATTS                  2417
#define IDS_PH_STAT_CARBON                                  2418
#define IDS_PH_STAT_ENERGYNETWORKTXRX                       2419
#define IDS_PH_STAT_ENERGYMBBTXRX                           2420
#define IDS_PH_STAT_ENERGYFOREGROUNDDURATION                2421
#define IDS_PH_STAT_ENERGYDESKTOPVISIBLEDURATION            2422
#define IDS_PH_STAT_ENERGYPSMFOREGROUNDDURATION             2423
#define IDS_PH_STAT_ENERGYCOMPOSITIONRENDERED               2424
#define IDS_PH_STAT_ENERGYCOMPOSITIONDIRTYGENERATED         2425
#define IDS_PH_STAT_ENERGYCOMPOSITIONDIRTYPROPAGATED        2426
#define IDS_PH_STAT_ENERGYCPUTIMELINE                       2427
#define IDS_PH_STAT_ENERGYDISKTIMELINE                      2428
#define IDS_PH_STAT_ENERGYNETWORKTIMELINE                   2429
#define IDS_PH_STAT_ENERGYINPUTDURATION                     2430
#define IDS_PH_STAT_ENERGYAUDIOINDURATION                   2431
#define IDS_PH_STAT_ENERGYAUDIOOUTDURATION                  2432
#define IDS_PH_STAT_ENERGYDISPLAYREQUIREDDURATION           2433
#define IDS_PH_STAT_ENERGYPSMBACKGROUNDDURATION             2434
#define IDS_PH_STAT_ENERGYKEYBOARDINPUT                     2435
#define IDS_PH_STAT_ENERGYMOUSEINPUT                        2436
#define IDS_PH_STAT_RUNNINGTIME                             2437
#define IDS_PH_STAT_SUSPENDEDTIME                           2438
#define IDS_PH_STAT_HANGCOUNT                               2439
#define IDS_PH_STAT_GHOSTCOUNT                              2440
#define IDS_PH_STAT_NETWORKTXRXBYTES                        2441
#define IDS_PH_TOKEN_RESOLVING                              2442
#define IDS_PH_TOKEN_TYPE                                   2443
#define IDS_PH_TOKEN_IMPERSONATION_LEVEL                    2444
#define IDS_PH_TOKEN_LUID                                   2445
#define IDS_PH_TOKEN_AUTHENTICATION_LUID                    2446
#define IDS_PH_TOKEN_MODIFIEDID_LUID                        2447
#define IDS_PH_TOKEN_ORIGIN_LUID                            2448
#define IDS_PH_TOKEN_MEMORY_USED                            2449
#define IDS_PH_TOKEN_MEMORY_AVAILABLE                       2450
#define IDS_PH_TOKEN_OBJECT_PATH                            2451
#define IDS_PH_TOKEN_SDDL                                   2452
#define IDS_PH_TOKEN_TRUSTLEVEL_SID                         2453
#define IDS_PH_TOKEN_TRUSTLEVEL_NAME                        2454
#define IDS_PH_TOKEN_FOLDER_PATH                            2455
#define IDS_PH_TOKEN_REGISTRY_PATH                          2456
#define IDS_PH_TOKEN_HWID_PUBLISHER                         2457
#define IDS_PH_TOKEN_HWID_USER                              2458
#define IDS_PH_TOKEN_NAME                                   2459
#define IDS_PH_TOKEN_SID                                    2460
#define IDS_PH_TOKEN_NUMBER                                 2461
#define IDS_PH_TOKEN_LPAC                                   2462
#define IDS_PH_TOKEN_PATH                                   2463
#define IDS_PH_GROUP_PROCESSES                              2464
#define IDS_PH_GROUP_THREADS                                2465
#define IDS_PH_GROUP_ENVIRONMENT                            2466
#define IDS_PH_GROUP_WMI                                    2467
#define IDS_PH_GROUP_TOKEN                                  2468
#define IDS_PH_GROUP_MEMORY                                 2469
#define IDS_PH_GROUP_MODULES                                2470
#define IDS_PH_GROUP_SERVICES                               2471
#define IDS_PH_GROUP_IO                                     2472
#define IDS_PH_GROUP_USER                                   2473
#define IDS_PH_GROUP_SYSTEM                                 2474
#define IDS_PH_GROUP_BASIC_INFORMATION                      2475
#define IDS_PH_GROUP_SECURITY_INFORMATION                   2476
#define IDS_PH_GROUP_REFERENCES                             2477
#define IDS_PH_GROUP_QUOTA_CHARGES                          2478
#define IDS_PH_GROUP_ALPC_PORT                              2479
#define IDS_PH_GROUP_EVENT_TRACE_INFORMATION                2480
#define IDS_PH_GROUP_FILE_INFORMATION                       2481
#define IDS_PH_GROUP_SECTION_INFORMATION                    2482
#define IDS_PH_GROUP_MUTANT_INFORMATION                     2483
#define IDS_PH_GROUP_PROCESS_INFORMATION                    2484
#define IDS_PH_GROUP_THREAD_INFORMATION                     2485
#define IDS_PH_GROUP_SYMBOLIC_LINK_INFORMATION              2486
#define IDS_PH_GROUP_AUDITING_INFORMATION                   2487
#define IDS_PH_GROUP_SHARED_WINSOCK_CONTEXT                 2488
#define IDS_PH_GROUP_ADDRESSES                              2489
#define IDS_PH_GROUP_AFD_INFO_CLASSES                       2490
#define IDS_PH_GROUP_TDI_DEVICES                            2491
#define IDS_PH_GROUP_SOCKET_LEVEL_OPTIONS                   2492
#define IDS_PH_GROUP_IP_LEVEL_OPTIONS                       2493
#define IDS_PH_GROUP_TCP_LEVEL_OPTIONS                      2494
#define IDS_PH_GROUP_TCP_INFORMATION                        2495
#define IDS_PH_GROUP_UDP_LEVEL_OPTIONS                      2496
#define IDS_PH_GROUP_HYPERV_LEVEL_OPTIONS                   2497
#define IDS_PH_GROUP_FLAGS                                  2498
#define IDS_PH_GROUP_PRIVILEGES                             2499
#define IDS_PH_GROUP_RESTRICTING_SIDS                       2500
#define IDS_PH_GROUPS                                       2501
#define IDS_PH_GROUPS_LOGON_SID                             2502
#define IDS_PH_GROUPS_MANDATORY_LABEL                       2503
#define IDS_PH_GROUP_GENERAL                                2504
#define IDS_PH_GROUP_LUIDS                                  2505
#define IDS_PH_GROUP_TRUST_LEVEL                            2506
#define IDS_PH_GROUP_PROFILE                                2507
#define IDS_PH_GROUP_SYSTEM_ID                              2508
#define IDS_PH_GROUP_PARENT                                 2509
#define IDS_PH_GROUP_PACKAGE                                2510
#define IDS_PH_CONFIRM_SELECTED_SERVICE                     2511
#define IDS_PH_CONFIRM_SELECTED_SERVICES                    2512
#define IDS_PH_CONFIRM_SELECTED_THREAD                      2513
#define IDS_PH_CONFIRM_SELECTED_THREADS                     2514
#define IDS_PH_ACTION_FREE                                  2515
#define IDS_PH_CONFIRM_FREE_MEMORY_WARNING                  2516
#define IDS_PH_ACTION_DECOMMIT                              2517
#define IDS_PH_CONFIRM_DECOMMIT_MEMORY_WARNING              2518
#define IDS_PH_ACTION_UNMAP                                 2519
#define IDS_PH_CONFIRM_UNMAP_MEMORY_WARNING                 2520
#define IDS_PH_CONFIRM_SELECTED_HANDLES                     2521
#define IDS_PH_ACTION_UNLOAD                                2522
#define IDS_PH_CONFIRM_UNLOAD_DRIVER_WARNING                2523
#define IDS_PH_CONFIRM_UNLOAD_MODULE_WARNING                2524
#define IDS_PH_CONFIRM_UNLOAD_MODULE_COMPAT_WARNING         2525
#define IDS_PH_CONFIRM_UNMAP_SECTION_WARNING                2526
#define IDS_PH_NOTIFY_PROCESS_CREATED_TITLE                 2527
#define IDS_PH_NOTIFY_PROCESS_TERMINATED_TITLE              2528
#define IDS_PH_NOTIFY_SERVICE_CREATED_TITLE                 2529
#define IDS_PH_NOTIFY_SERVICE_STARTED_TITLE                 2530
#define IDS_PH_NOTIFY_SERVICE_STOPPED_TITLE                 2531
#define IDS_PH_NOTIFY_SERVICE_MODIFIED_TITLE                2532
#define IDS_PH_NOTIFY_SERVICE_DELETED_TITLE                 2533
#define IDS_PH_NOTIFY_PROCESS_CREATED_FORMAT                2534
#define IDS_PH_NOTIFY_PROCESS_TERMINATED_FORMAT             2535
#define IDS_PH_NOTIFY_SERVICE_CREATED_FORMAT                2536
#define IDS_PH_NOTIFY_SERVICE_STARTED_FORMAT                2537
#define IDS_PH_NOTIFY_SERVICE_STOPPED_FORMAT                2538
#define IDS_PH_NOTIFY_SERVICE_MODIFIED_FORMAT               2539
#define IDS_PH_NOTIFY_SERVICE_DELETED_FORMAT                2540
#define IDS_PH_NOTIFY_UNKNOWN_PROCESS                       2541
#define IDS_PH_MEMORY_RESULTS_TITLE_FORMAT                  2542
#define IDS_PH_RESULTS_COUNT_FORMAT                         2543
#define IDS_PH_FIND_RESULTS_TITLE_FORMAT                    2544
#define IDS_PH_AFFINITY_THREADS_TITLE_FORMAT                2545
#define IDS_PH_EDIT_ENVIRONMENT_TITLE_FORMAT                2546
#define IDS_PH_MESSAGE_FROM_FORMAT                          2547
#define IDS_PH_STACK_THREAD_TITLE_FORMAT                    2548
#define IDS_PH_HIDDEN_PROCESS_SUMMARY_FORMAT                2549
#define IDS_PH_INSTALLED_MEMORY_FORMAT                      2550
#define IDS_PH_TOTAL_MEMORY_FORMAT                          2551
#define IDS_PH_MEMORY_STRINGS_TITLE_FORMAT                  2552
#define IDS_PH_THREAD_COUNT_AUTO                            2553
#define IDS_PH_THREAD_COUNT_FORMAT                          2554
#define IDS_PH_VERIFIED_LINK_FORMAT                         2555
#define IDS_PH_VERIFIED_COMPANY_FORMAT                      2556
#define IDS_PH_UNVERIFIED_COMPANY_FORMAT                    2557
#define IDS_PH_NON_EXISTENT_PROCESS_FORMAT                  2558
#define IDS_PH_UNKNOWN_PROCESS_FORMAT                       2559
#define IDS_PH_NOT_AVAILABLE                                2560
#define IDS_PH_UNKNOWN                                      2561
#define IDS_PH_PERMISSION_ALLOW                             2562
#define IDS_PH_APP_CONTAINER_CHILD                         2563
#define IDS_PH_LOCK_TYPE_CRITICAL_SECTION                  2564
#define IDS_PH_LINKED_TOKEN_TITLE                           2565
#define IDS_PH_EVENT_TYPE_NOTIFICATION                     2566
#define IDS_PH_HEAP_TYPE_NT                                 2567
#define IDS_PH_HEAP_TYPE_NT_LFH                             2568
#define IDS_PH_HEAP_TYPE_NT_LOOKASIDE                       2569
#define IDS_PH_LOCK_TYPE_RESOURCE                           2570
#define IDS_PH_HEAP_TYPE_SEGMENT                            2571
#define IDS_PH_HEAP_TYPE_SEGMENT_LFH                        2572
#define IDS_PH_HEAP_TYPE_SEGMENT_LOOKASIDE                  2573
#define IDS_PH_EVENT_TYPE_SYNCHRONIZATION                   2574
#define IDS_PH_MEMORY_PROTECTION_VALUES                     2575
#define IDS_PH_DEFAULT_TASK_MANAGER_STATUS                  2576
#define IDS_PH_NOT_DEFAULT_TASK_MANAGER_STATUS              2577
#define IDS_PH_ABOUT_CREDITS                                2578
#define IDS_PH_THREAD_COUNT_VALUE_TITLE                     2579
#define IDS_PH_DEVICE_UNCLASSIFIED                          2580
#define IDS_PH_DEVICE_UNNAMED                               2581
#define IDS_PH_DEVICE_ARRIVED_TITLE_FORMAT                  2582
#define IDS_PH_DEVICE_REMOVED_TITLE_FORMAT                  2583
#define IDS_PH_NATIVE_RESTART_WARNING                       2584
#define IDS_PH_CRITICAL_RESTART_WARNING                     2585
#define IDS_PH_NATIVE_SHUTDOWN_WARNING                      2586
#define IDS_PH_CRITICAL_SHUTDOWN_WARNING                    2587
#define IDS_PH_SYSTEM_PROCESS_ACTION_WARNING_FORMAT         2588
#define IDS_PH_CRITICAL_PROCESS_ACTION_WARNING_FORMAT       2589
#define IDS_PH_CRITICAL_PROCESS_TERMINATE_WARNING_FORMAT    2590
#define IDS_PH_UNKNOWN_OBJECT_TYPE_FORMAT                   2591
#define IDS_PH_ACTION_START                                 2592
#define IDS_PH_ACTION_CONTINUE                              2593
#define IDS_PH_ACTION_PAUSE                                 2594
#define IDS_PH_ACTION_STOP                                  2595
#define IDS_PH_ACTION_DELETE                                2596
#define IDS_PH_UNABLE_SERVICE_ACTION_FORMAT                 2597
#define IDS_PH_FIRST                                 IDS_PH_RESET_ALL_SETTINGS
#define IDS_PH_LAST                                  IDS_PH_SCROLL_DOWN

#define IDDYNAMIC                       50000
#define IDPLUGINS                       55000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        294
#define _APS_NEXT_COMMAND_VALUE         10327
#define _APS_NEXT_CONTROL_VALUE         1519
#define _APS_NEXT_SYMED_VALUE           2611
#endif
#endif
