//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExtendedTools.rc
//
#define ID_PROCESS_UNLOADEDMODULES      101
#define IDD_UNLOADEDDLLS                102
#define ID_THREAD_CANCELIO              104
#define IDD_OBJTPWORKERFACTORY          105
#define ID_MODULE_SERVICES              106
#define IDD_MODSERVICES                 107
#define ID_VIEW_MEMORYLISTS             108
#define IDD_PROCDISK                    110
#define ID_VIEW_DISKANDNETWORK          111
#define ID_PROCESS_WSWATCH              112
#define IDD_SYSINFO_DISKPANEL           113
#define IDD_OPTIONS                     114
#define IDD_WSWATCH                     115
#define IDD_SYSINFO_GPU                 117
#define ID_VIEW_GPUINFORMATION          119
#define IDD_SYSINFO_GPUPANEL            120
#define IDD_PROCGPU                     121
#define IDD_SYSINFO_DISK                122
#define IDD_GPUNODES                    123
#define IDD_SYSINFO_NETPANEL            124
#define IDD_SYSINFO_NET                 125
#define IDD_PROCDISK_PANEL              129
#define IDC_UTILIZATION                 132
#define IDC_SPEED                       133
#define IDD_SYSINFO_GPUDETAILS          141
#define IDD_PROCFRAMES                  142
#define IDD_PROCIFEO                    143
#define IDI_CPU                         159
#define IDI_SEMAPHORE                   160
#define IDI_FILTERPORT                  161
#define IDI_JOB                         162
#define IDI_MEMORY                      163
#define IDD_OBJHANDLES                  164
#define IDI_CALLBACK                    165
#define IDI_KEYEDEVENT                  166
#define IDI_TYPE                        167
#define IDI_TIMER                       168
#define IDI_WINSTA                      169
#define IDD_SYSINFO_NPU                 200
#define ID_VIEW_NPUINFORMATION          201
#define IDD_SYSINFO_NPUPANEL            202
#define IDD_PROCNPU                     203
#define IDD_NPUNODES                    204
#define IDD_SYSINFO_NPUDETAILS          205
#define IDC_LIST                        1001
#define IDC_REFRESH                     1002
#define IDC_WORKERTHREADSTART           1005
#define IDC_WORKERTHREADCONTEXT         1006
#define IDC_SERVICES_LAYOUT             1007
#define IDC_MESSAGE                     1008
#define IDC_ZREADS_V                    1023
#define IDC_ZREADBYTES_V                1024
#define IDC_ZREADBYTESDELTA_V           1025
#define IDC_ZWRITES_V                   1026
#define IDC_ZWRITEBYTES_V               1027
#define IDC_ZWRITEBYTESDELTA_V          1028
#define IDC_ZRECEIVES_V                 1029
#define IDC_ZRECEIVEBYTES_V             1030
#define IDC_ZRECEIVEBYTESDELTA_V        1031
#define IDC_ZSENDS_V                    1032
#define IDC_ZSENDBYTES_V                1033
#define IDC_ZSENDBYTESDELTA_V           1034
#define IDC_ENABLEETWMONITOR            1035
#define IDC_ENABLE                      1036
#define IDC_WSWATCHENABLED              1037
#define IDC_ENABLEFAHRENHEITTEMP        1038
#define IDC_NODES                       1048
#define IDC_ENABLEGPUMONITOR            1049
#define IDC_ENABLESYSINFOGRAPHS         1050
#define IDC_GROUPGPU                    1051
#define IDC_ENABLEFPSMONITOR            1051
#define IDC_GROUPMEM                    1052
#define IDC_GROUPSHARED                 1053
#define IDC_GROUPCOMMIT                 1054
#define IDC_ZDEDICATEDCURRENT_V         1055
#define IDC_GROUPFPSFRAMERENDER         1055
#define IDC_ZDEDICATEDLIMIT_V           1056
#define IDC_GROUPFPSFRAMEDISPLAY        1056
#define IDC_ZSHAREDCURRENT_V            1057
#define IDC_GROUPFPSDISPLAYLATENCY      1057
#define IDC_ZSHAREDLIMIT_V              1058
#define IDC_TITLE                       1073
#define IDC_GRAPH_LAYOUT                1074
#define IDC_LAYOUT                      1075
#define IDC_GPUNAME                     1076
#define IDC_GPU_L                       1077
#define IDC_DEDICATED_L                 1078
#define IDC_SHARED_L                    1079
#define IDC_ZRECEIVESDELTA_V            1080
#define IDC_ZSENDSDELTA_V               1081
#define IDC_ZWRITESDELTA_V              1082
#define IDC_ZREADSDELTA_V               1083
#define IDC_ZGROUPBOX_V                 1084
#define IDC_PANEL_LAYOUT                1085
#define IDC_GROUPNETRECEIVE             1088
#define IDC_GROUPNETSEND                1089
#define IDC_DETAILS                     1092
#define IDC_GPULIST                     1093
#define IDC_POWER_USAGE_L               1094
#define IDC_TEMPERATURE_L               1095
#define IDC_FAN_RPM_L                   1096
#define IDC_GROUPFPS                    1098
#define IDC_GROUPFPSLATENCY             1099
#define IDC_GROUPFPSPRESENT             1100
#define IDC_GROUPFPSPRESENTINTERVAL     1101
#define IDC_POOL_AUTOSIZE_COLUMNS       1104
#define IDC_DISKREAD_L                  1108
#define IDC_DISKWRITE_L                 1109
#define IDC_NETRECEIVE_L                1110
#define IDC_NETSEND_L                   1111
#define IDC_GROUPDISKREAD               1112
#define IDC_GROUPDISKWRITE              1113
#define IDC_OBJMGR_SEARCH               1114
#define IDC_OBJMGR_COUNT_L              1115
#define IDC_OBJMGR_COUNT                1116
#define IDC_PROPERTIES                  1117
#define IDC_SECURITY                    1118
#define IDC_COPY                        1119
#define IDC_OPENLINK                    1120
#define IDC_GOTODRIVER                  1121
#define IDC_GOTOPROCESS                 1122
#define IDC_GOTOTHREAD                  1123
#define IDC_OBJMGR_PATH                 1124
#define IDC_COPYPATH                    1125
#define IDC_RESETSORT                   1126
#define IDC_OPENFILELOCATION            1127
#define IDC_CLOSEHANDLE                 1128
#define IDC_OBJ_HANDLESTOTAL            1129
#define IDC_OBJ_HANDLESBYOBJECT         1130
#define IDC_OBJ_HANDLESBYNAME           1131
#define IDC_OBJ_HANDLESBYNAME_L         1132
#define IDC_GOTODRIVER2                 1133
#define IDC_HANDLE_PROTECTED            1134
#define IDC_HANDLE_INHERIT              1135
#define IDC_COPYOBJECTADDRESS           1136
#define IDC_OPENHANDLES                 1137
#define IDC_ENABLENPUMONITOR            2000
#define IDC_GROUPNPU                    2001
#define IDC_NPUNAME                     2002
#define IDC_NPU_L                       2003
#define IDC_NPULIST                     2004
#define IDC_ENABLEGPUADAPTERSTATS       2005
#define ID_POOL_TABLE                   3000
#define IDD_POOL                        3001
#define IDD_BIGPOOL                     3003
#define IDC_POOLTREE                    3004
#define IDC_POOLSEARCH                  3005
#define IDC_POOLCLEAR                   3006
#define IDC_BIGPOOLLIST                 3007
#define ID_OBJMGR                       4000
#define IDD_OBJMGR                      4001
#define IDI_FOLDER                      4002
#define IDI_MUTANT                      4003
#define IDI_DRIVER                      4004
#define IDI_SECTION                     4005
#define IDI_LINK                        4006
#define IDI_KEY                         4007
#define IDI_PORT                        4008
#define IDI_SESSION                     4009
#define IDI_EVENT                       4010
#define IDI_DEVICE                      4011
#define IDI_UNKNOWN                     4012
#define IDC_OBJMGR_LIST                 4013
#define IDC_OBJMGR_TREE                 4014
#define ID_SMBIOS                       5000
#define ID_FIRMWARE                     5001
#define IDD_FIRMWARE                    5002
#define IDD_FIRMWARE_EDITVAR            5003
#define IDC_FIRMWARE_HEXEDITVAR         5004
#define IDC_FIRMWARE_REREAD             5005
#define IDC_FIRMWARE_WRITE              5006
#define IDC_FIRMWARE_SAVE               5007
#define IDC_FIRMWARE_BYTESPERROW        5008
#define IDC_FIRMWARE_BOOT_LIST          5009
#define IDC_FIRMWARE_BOOT_REFRESH       5010
#define IDD_SMBIOS                      5011
#define IDC_SMBIOS_INFO                 5012
#define ID_PIPE_ENUM                    6000
#define IDD_PIPEDIALOG                  6001
#define IDC_ATOMLIST                    6002
#define IDC_PIPELIST                    6002
#define ID_REPARSE_POINTS               7000
#define ID_REPARSE_OBJID                7001
#define ID_REPARSE_SDDL                 7002
#define IDD_REPARSEDIALOG               7003
#define IDC_REPARSE_LIST                7004
#define ID_PROCESS_WAITCHAIN            8000
#define ID_THREAD_WAITCHAIN             8001
#define ID_WCT_SHOWCONTEXTMENU          8001
#define IDD_WCT_DIALOG                  8002
#define IDD_PROCNET                     8003
#define IDC_WCT_TREE                    8004
#define IDD_PROCNET_PANEL               8004
#define IDD_OBJWINSTA                   8005
#define ID_WCT_MENU_PROPERTIES          8007
#define ID_WCT_MENU_COPY                8008
#define IDD_POWER_POLICIES              9000
#define IDC_POWER_POLICIES_LIST         9001
#define ID_POWER_POLICIES               9002
#define IDD_POWER_GRID                  9003
#define IDC_POWER_GRID_LIST             9004
#define IDD_SRVCOMPAT                   9004
#define IDD_PCASRV                      9004
#define ID_POWER_GRID                   9005
#define IDD_PCAPROC                     9005
#define IDD_PCAPRC                      9005
#define IDC_POWER_GRID_SUMMARY          9006
#define IDD_CACHE_LATENCY               9010
#define IDC_CACHE_LATENCY_LIST          9011
#define IDC_CACHE_LATENCY_STATUS        9012
#define IDC_CACHE_LATENCY_L1            9013
#define IDC_CACHE_LATENCY_L2            9014
#define IDC_CACHE_LATENCY_L3            9015
#define IDC_CACHE_LATENCY_DRAM          9016
#define IDD_SRUM                        9017
#define IDC_SRUM_LIST                   9018
#define IDC_SRUM_PROVIDER               9019
#define IDC_SRUM_SCOPE                  9020
#define IDC_SRUM_DURATION               9021
#define IDC_SRUM_STATUS                 9022
#define ID_SRUM                         9023
#define ID_DISK_GOTOPROCESS             40005
#define ID_DISK_COPY                    40006
#define ID_DISK_PROPERTIES              40007
#define ID_DISK_OPENFILELOCATION        40008
#define ID_DISK_INSPECT                 40009
#define ID_TPM                          50001
#define IDD_TPM                         50002
#define IDC_TPM_LIST                    50003
#define IDC_TPM_LIST_REFRESH            50004
#define IDD_TPM_EDIT                    50005
#define IDC_TPM_HEXEDIT                 50006
#define IDC_TPM_REREAD                  50007
#define IDC_TPM_WRITE                   50008
#define IDC_TPM_SAVE                    50009
#define IDC_TPM_BYTESPERROW             50010
#define ID_CACHE_LATENCY                60002
#define IDD_STARTUP_TASKS               60004
#define ID_ENVIRONMENT_VARIABLES        60006
#define IDD_ENVIRONMENTVARIABLES        60007
#define IDD_ENVEDIT_LIST                60008
#define IDD_ENVEDIT                     60009
#define IDD_FWEVENT_GENERAL             60010
#define IDD_FWEVENT_LAYER               60011
#define ID_ACPI                         60020
#define IDD_ACPI                        60021
#define IDC_ACPI_INFO                   60022
#define ID_WBCL                         60030
#define IDD_WBCL                        60031
#define IDC_WBCL_LIST                   60032
#define IDC_WBCL_REFRESH                60033
#define IDC_WBCL_OPENFILE               60034
#define IDC_ENV_ADD                     60035
#define IDC_ENV_EDIT                    60036
#define IDC_ENV_DELETE                  60037
#define IDC_ENV_NEW                     60038
#define IDC_ENV_BROWSE                  60039
#define IDC_ENV_MOVEUP                  60040
#define IDC_ENV_MOVEDOWN                60041
#define IDC_ENV_EDITTEXT                60042
#define IDC_ENV_NAME                    60043
#define IDC_ENV_VALUE                   60044
#define IDS_ET_BOOT_LOG_ENTRY           61000
#define IDS_ET_FAILED_READ_TPM          61001
#define IDS_ET_NO_SYNCHRONOUS_IO        61002
#define IDS_ET_UNABLE_CANCEL_SYNCHRONOUS_IO 61003
#define IDS_ET_UNABLE_CREATE_SYMBOL_PROVIDER 61004
#define IDS_ET_UNABLE_DELETE_FIRMWARE_VARIABLE 61005
#define IDS_ET_UNABLE_ENABLE_ENVIRONMENT_PRIVILEGE 61006
#define IDS_ET_UNABLE_ENABLE_WS_WATCH   61007
#define IDS_ET_UNABLE_ENUMERATE_OBJECTS 61008
#define IDS_ET_UNABLE_LOCATE_SECURITY_ID_FILES 61009
#define IDS_ET_UNABLE_LOCATE_TARGET     61010
#define IDS_ET_UNABLE_QUERY_DIRECTORY_OBJECT 61011
#define IDS_ET_UNABLE_QUERY_FIRMWARE_TABLE 61012
#define IDS_ET_UNABLE_QUERY_MODULE_REFERENCES 61013
#define IDS_ET_UNABLE_QUERY_EFI_VARIABLE 61014
#define IDS_ET_UNABLE_QUERY_TPM         61015
#define IDS_ET_UNABLE_READ_LOG_FILE     61016
#define IDS_ET_UNABLE_READ_MEASURED_BOOT_LOG 61017
#define IDS_ET_UNABLE_READ_TPM          61018
#define IDS_ET_UNABLE_REMOVE_OBJECT_IDENTIFIER 61019
#define IDS_ET_UNABLE_REMOVE_REPARSE_POINT 61020
#define IDS_ET_UNABLE_RETRIEVE_UNLOAD_TRACE 61021
#define IDS_ET_UNABLE_SELECT_PROCESS    61022
#define IDS_ET_UNABLE_UPDATE_EFI_VARIABLE 61023
#define IDS_ET_UNABLE_WRITE_TPM         61024
#define IDS_ET_BYTES_PER_ROW_FORMAT     61025
#define IDS_ET_ADAPTER_DETAILS_PHYSICAL_LOCATION 61026
#define IDS_ET_ADAPTER_DETAILS_DRIVER_DATE 61027
#define IDS_ET_ADAPTER_DETAILS_DRIVER_VERSION 61028
#define IDS_ET_ADAPTER_DETAILS_WDDM_VERSION 61029
#define IDS_ET_ADAPTER_DETAILS_VENDOR_ID 61030
#define IDS_ET_ADAPTER_DETAILS_DEVICE_ID 61031
#define IDS_ET_ADAPTER_DETAILS_TOTAL_MEMORY 61032
#define IDS_ET_ADAPTER_DETAILS_RESERVED_MEMORY 61033
#define IDS_ET_ADAPTER_DETAILS_MEMORY_FREQUENCY 61034
#define IDS_ET_ADAPTER_DETAILS_MEMORY_BANDWIDTH 61035
#define IDS_ET_ADAPTER_DETAILS_PCIE_BANDWIDTH 61036
#define IDS_ET_ADAPTER_DETAILS_FAN_RPM  61037
#define IDS_ET_ADAPTER_DETAILS_POWER_USAGE 61038
#define IDS_ET_ADAPTER_DETAILS_TEMPERATURE 61039
#define IDS_ET_DEDICATED_MEMORY         61040
#define IDS_ET_SHARED_MEMORY            61041
#define IDS_ET_COMMIT_MEMORY            61042
#define IDS_ET_TOTAL_MEMORY             61043
#define IDS_ET_READS                    61044
#define IDS_ET_READ_BYTES               61045
#define IDS_ET_READ_BYTES_DELTA         61046
#define IDS_ET_WRITES                   61047
#define IDS_ET_WRITE_BYTES              61048
#define IDS_ET_WRITE_BYTES_DELTA        61049
#define IDS_ET_TOTAL                    61050
#define IDS_ET_TOTAL_BYTES              61051
#define IDS_ET_TOTAL_BYTES_DELTA        61052
#define IDS_ET_RECEIVES                 61053
#define IDS_ET_RECEIVE_BYTES            61054
#define IDS_ET_RECEIVE_BYTES_DELTA      61055
#define IDS_ET_SENDS                    61056
#define IDS_ET_SEND_BYTES               61057
#define IDS_ET_SEND_BYTES_DELTA         61058
#define IDS_ET_VIRTUAL_MEMORY           61059
#define IDS_ET_EVICTED_BYTES            61060
#define IDS_ET_DMA_BUFFER_SIZE          61061
#define IDS_ET_DMA_ALLOCATION_LIST      61062
#define IDS_ET_DMA_PATCH_LIST           61063
#define IDS_ET_CONTENTION_EVENTS        61064
#define IDS_ET_DISPLAY_OUTPUTS          61065
#define IDS_ET_OBJECT_ATTRIBUTES        61066
#define IDS_ET_DRIVER_IMAGE             61067
#define IDS_ET_DRIVER_SERVICE_NAME      61068
#define IDS_ET_DRIVER_SIZE              61069
#define IDS_ET_DRIVER_START_ADDRESS     61070
#define IDS_ET_DRIVER_FLAGS             61071
#define IDS_ET_LOWER_EDGE_DRIVER        61072
#define IDS_ET_LOWER_EDGE_DRIVER_IMAGE  61073
#define IDS_ET_UPPER_EDGE_DRIVER        61074
#define IDS_ET_UPPER_EDGE_DRIVER_IMAGE  61075
#define IDS_ET_PNP_DEVICE_NAME          61076
#define IDS_ET_TYPE                     61077
#define IDS_ET_VISIBLE                  61078
#define IDS_ET_INPUT_DESKTOP            61079
#define IDS_ET_USER_SID                 61080
#define IDS_ET_HEAP_SIZE                61081
#define IDS_ET_INDEX                    61082
#define IDS_ET_OBJECTS                  61083
#define IDS_ET_HANDLES                  61084
#define IDS_ET_PEAK_OBJECTS             61085
#define IDS_ET_PEAK_HANDLES             61086
#define IDS_ET_POOL_TYPE                61087
#define IDS_ET_DEFAULT_PAGED_CHARGE     61088
#define IDS_ET_DEFAULT_NP_CHARGE        61089
#define IDS_ET_VALID_ACCESS_MASK        61090
#define IDS_ET_GENERIC_READ             61091
#define IDS_ET_GENERIC_WRITE            61092
#define IDS_ET_GENERIC_EXECUTE          61093
#define IDS_ET_GENERIC_ALL              61094
#define IDS_ET_INVALID_ATTRIBUTES       61095
#define IDS_ET_SESSION_NAME             61096
#define IDS_ET_SESSION_ID               61097
#define IDS_ET_USER_NAME                61098
#define IDS_ET_STATE                    61099
#define IDS_ET_LOGON_TIME               61100
#define IDS_ET_CONNECT_TIME             61101
#define IDS_ET_DISCONNECT_TIME          61102
#define IDS_ET_LAST_INPUT_TIME          61103
#define IDS_ET_GROUP_GPU                61104
#define IDS_ET_GROUP_DISK_IO            61105
#define IDS_ET_GROUP_NETWORK_IO         61106
#define IDS_ET_GROUP_NPU                61107
#define IDS_ET_GROUP_GPU_ADAPTER        61108
#define IDS_ET_GROUP_DRIVER_INFORMATION 61109
#define IDS_ET_GROUP_DEVICE_INFORMATION 61110
#define IDS_ET_GROUP_WINDOW_STATION_INFORMATION 61111
#define IDS_ET_GROUP_DESKTOP_INFORMATION 61112
#define IDS_ET_GROUP_TYPE_INFORMATION   61113
#define IDS_ET_GROUP_TYPE_ACCESS_INFORMATION 61114
#define IDS_ET_GROUP_SESSION_INFORMATION 61115
#define IDS_ET_CACHE_TYPE_DATA          61116
#define IDS_ET_CACHE_TYPE_INSTRUCTION   61117
#define IDS_ET_CACHE_TYPE_UNIFIED       61118
#define IDS_ET_UNKNOWN                  61119
#define IDS_ET_STATE_ACTIVE             61120
#define IDS_ET_SESSION_STATE_CONNECTED  61121
#define IDS_ET_SESSION_STATE_CONNECT_QUERY 61122
#define IDS_ET_SESSION_STATE_SHADOW     61123
#define IDS_ET_SESSION_STATE_DISCONNECTED 61124
#define IDS_ET_SESSION_STATE_IDLE       61125
#define IDS_ET_SESSION_STATE_LISTEN     61126
#define IDS_ET_SESSION_STATE_RESET      61127
#define IDS_ET_SESSION_STATE_DOWN       61128
#define IDS_ET_SESSION_STATE_INIT       61129
#define IDS_ET_CACHE_LATENCY_SUMMARY_FORMAT 61130
#define IDS_ET_DRAM_LATENCY_SUMMARY_FORMAT 61131
#define IDS_ET_WCT_COLUMN_TYPE          61132
#define IDS_ET_WCT_COLUMN_THREAD_ID     61133
#define IDS_ET_WCT_COLUMN_PROCESS_ID    61134
#define IDS_ET_WCT_COLUMN_STATUS        61135
#define IDS_ET_WCT_COLUMN_CONTEXT_SWITCHES 61136
#define IDS_ET_WCT_COLUMN_WAIT_TIME     61137
#define IDS_ET_WCT_COLUMN_TIMEOUT       61138
#define IDS_ET_WCT_COLUMN_ALERTABLE     61139
#define IDS_ET_WCT_COLUMN_NAME          61140
#define IDS_ET_WCT_GO_TO_PROCESS        61141
#define IDS_ET_WCT_GO_TO_THREAD         61142
#define IDS_ET_WCT_PROCESS_NOT_FOUND    61143
#define IDS_ET_WCT_TRUE                 61144
#define IDS_ET_WCT_NO_THREADS           61145
#define IDS_ET_WCT_QUERYING             61146
#define IDS_ET_WCT_TYPE_CRITICAL_SECTION 61147
#define IDS_ET_WCT_TYPE_SEND_MESSAGE    61148
#define IDS_ET_WCT_TYPE_MUTEX           61149
#define IDS_ET_WCT_TYPE_ALPC            61150
#define IDS_ET_WCT_TYPE_COM             61151
#define IDS_ET_WCT_TYPE_THREAD_WAIT     61152
#define IDS_ET_WCT_TYPE_PROCESS_WAIT    61153
#define IDS_ET_WCT_TYPE_THREAD          61154
#define IDS_ET_WCT_TYPE_COM_ACTIVATION  61155
#define IDS_ET_WCT_UNKNOWN              61156
#define IDS_ET_WCT_TYPE_SOCKET_IO       61157
#define IDS_ET_WCT_TYPE_SMB_IO          61158
#define IDS_ET_WCT_STATUS_NO_ACCESS     61159
#define IDS_ET_WCT_STATUS_RUNNING       61160
#define IDS_ET_WCT_STATUS_BLOCKED       61161
#define IDS_ET_WCT_STATUS_PID_ONLY      61162
#define IDS_ET_WCT_STATUS_PID_ONLY_RPCSS 61163
#define IDS_ET_WCT_STATUS_OWNED         61164
#define IDS_ET_WCT_STATUS_NOT_OWNED     61165
#define IDS_ET_WCT_STATUS_ABANDONED     61166
#define IDS_ET_WCT_STATUS_ERROR         61167
#define IDS_ET_WCT_DATE_TIME_FORMAT     61168
#define IDS_ET_FIRMWARE_ATTRIBUTE_NON_VOLATILE 61169
#define IDS_ET_FIRMWARE_ATTRIBUTE_BOOT_SERVICE 61170
#define IDS_ET_FIRMWARE_ATTRIBUTE_RUNTIME_ACCESS 61171
#define IDS_ET_FIRMWARE_ATTRIBUTE_HARDWARE_ERROR_RECORD 61172
#define IDS_ET_FIRMWARE_ATTRIBUTE_AUTHENTICATED_WRITE 61173
#define IDS_ET_FIRMWARE_ATTRIBUTE_TIME_BASED_AUTHENTICATED_WRITE 61174
#define IDS_ET_FIRMWARE_ATTRIBUTE_APPEND_WRITE 61175
#define IDS_ET_FIRMWARE_COLUMN_NAME     61176
#define IDS_ET_FIRMWARE_COLUMN_ATTRIBUTES 61177
#define IDS_ET_FIRMWARE_COLUMN_GUID_NAME 61178
#define IDS_ET_FIRMWARE_COLUMN_GUID     61179
#define IDS_ET_FIRMWARE_COLUMN_DATA_LENGTH 61180
#define IDS_ET_MENU_EDIT                61181
#define IDS_ET_MENU_DELETE              61182
#define IDS_ET_MENU_COPY                61183
#define IDS_ET_FIRMWARE_LEGACY_BIOS     61184
#define IDS_ET_FILTER_BINARY_FILES      61185
#define IDS_ET_FILTER_ALL_FILES         61186
#define IDS_ET_UNABLE_CREATE_FILE       61187
#define IDS_ET_PIPE_STREAM              61188
#define IDS_ET_PIPE_MESSAGE             61189
#define IDS_ET_PIPE_INBOUND             61190
#define IDS_ET_PIPE_OUTBOUND            61191
#define IDS_ET_PIPE_DUPLEX              61192
#define IDS_ET_PIPE_UNLIMITED           61193
#define IDS_ET_PIPE_LISTENING           61194
#define IDS_ET_PIPE_CLOSING             61195
#define IDS_ET_PIPE_REJECT              61196
#define IDS_ET_PIPE_ACCEPT              61197
#define IDS_ET_PIPE_QUEUE               61198
#define IDS_ET_PIPE_COMPLETE            61199
#define IDS_ET_POWER_GRID_NO_FORECAST   61200
#define IDS_ET_SECTION_DISK             61201
#define IDS_ET_SECTION_NETWORK          61202
#define IDS_ET_STATUS_YES               61203
#define IDS_ET_STATUS_NO                61204
#define IDS_ET_STATUS_TRUE              61205
#define IDS_ET_STATUS_FALSE             61206
#define IDS_ET_POOL_NON_PAGED           61207
#define IDS_ET_POOL_PAGED               61208
#define IDS_ET_POOL_NON_PAGED_NX        61209
#define IDS_ET_POOL_PAGED_SESSION_NX    61210
#define IDS_ET_HANDLE_PROTECTED         61211
#define IDS_ET_HANDLE_INHERIT           61212
#define IDS_ET_HANDLE_PROTECTED_INHERIT 61213
#define IDS_ET_HANDLES_BY_TYPE          61214
#define IDS_ET_NTFS_SECURITY_ID         61215
#define IDS_ET_NTFS_REPARSE_POINTS      61216
#define IDS_ET_NTFS_OBJECT_IDENTIFIERS  61217
#define IDS_ET_NTFS_SECURITY_DESCRIPTORS 61218
#define IDS_ET_TPM_READ_WRITE           61219
#define IDS_ET_TPM_READ                 61220
#define IDS_ET_TPM_WRITE                61221
#define IDS_ET_TPM_NONE                 61222
#define IDS_ET_LARGE_ALLOCATIONS_TITLE_FORMAT 61223
#define IDS_ET_OBJECTS_CURRENT_DIRECTORY_FORMAT 61224
#define IDS_ET_MODULE_SERVICES_PROCESS_FORMAT 61225
#define IDS_ET_MODULE_SERVICES_FORMAT   61226
#define IDS_ET_TPM_INDEX_TITLE_FORMAT   61227
#define IDS_ET_WORKER_THREAD_START_FORMAT 61228
#define IDS_ET_WORKER_THREAD_CONTEXT_FORMAT 61229
#define IDS_ET_OPTIONS_SECTION          61230
#define IDS_ET_CACHED_FIRST             IDS_ET_DEDICATED_MEMORY
#define IDS_ET_CACHED_LAST              IDS_ET_OPTIONS_SECTION

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        60043
#define _APS_NEXT_COMMAND_VALUE         60043
#define _APS_NEXT_CONTROL_VALUE         60043
#define _APS_NEXT_SYMED_VALUE           61231
#endif
#endif
