//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HardwareDevices.rc
//
#define IDD_NETADAPTER_OPTIONS          101
#define IDC_GRAPH_LAYOUT                103
#define IDD_NETADAPTER_PANEL            104
#define IDD_NETADAPTER_DETAILS          105
#define IDD_DISKDRIVE_DETAILS_FILESYSTEM 106
#define IDD_RAPLDEVICE_DIALOG           107
#define IDD_RAPLDEVICE_PANEL            108
#define IDD_GPUDEVICE_DIALOG            117
#define IDD_GPUDEVICE_PANEL             120
#define IDD_GPUNODES                    123
#define IDD_GPUDEVICE_NODES             123
#define IDD_GPUDEVICE_DETAILS           141
#define IDC_NETADAPTERS_LISTVIEW        1001
#define IDC_LINK_SPEED                  1002
#define IDC_LAYOUT                      1004
#define IDC_LINK_STATE                  1005
#define IDC_STAT_BSENT                  1006
#define IDC_STAT_BRECEIVED              1007
#define IDC_STAT_BTOTAL                 1008
#define IDC_DETAILS                     1010
#define IDC_DETAILS_LIST                1011
#define IDD_DISKDRIVE_OPTIONS           1013
#define IDC_SHOW_PHYSICAL_ADAPTERS      1013
#define IDD_DISKDRIVE_DIALOG            1014
#define IDD_DISKDRIVE_PANEL             1016
#define IDD_DISKDRIVE_DETAILS_SMART     1017
#define IDC_DISKDRIVE_LISTVIEW          1018
#define IDC_DISKMOUNTPATH               1019
#define IDD_NETADAPTER_DIALOG           1020
#define IDD_RAPLDEVICE_OPTIONS          1021
#define IDC_STAT_BREAD                  1022
#define IDD_GPUDEVICE_OPTIONS           1022
#define IDC_STAT_BWRITE                 1023
#define IDC_ADAPTERNAME                 1024
#define IDC_ADAPTERTEXT                 1025
#define IDC_STAT_ACTIVE                 1026
#define IDC_STAT_BYTESDELTA             1027
#define IDC_RAPLDEVICE_LISTVIEW         1028
#define IDC_STAT_RESPONSETIME           1029
#define IDC_GPUDISCRETE_L               1030
#define IDC_CPUCOMP_L                   1031
#define IDC_STAT_QUEUELENGTH            1031
#define IDC_TOTALPOWER_L                1032
#define IDC_STAT_SPLITCOUNT             1032
#define IDC_TITLE                       1033
#define IDC_DISKNAME                    1034
#define IDC_DEVICENAME                  1035
#define IDC_PACKAGE_L                   1036
#define IDC_CORE_L                      1037
#define IDC_DIMM_L                      1038
#define IDC_PANEL_LAYOUT                1039
#define IDC_TOTAL_L                     1040
#define IDC_GPUDEVICE_LISTVIEW          1041
#define IDC_DOWN_L                      1042
#define IDC_UP_L                        1043
#define IDC_SHOW_HIDDEN_DEVICES         1044
#define IDC_NODES                       1048
#define IDC_ZDEDICATEDCURRENT_V         1055
#define IDC_ZDEDICATEDLIMIT_V           1056
#define IDC_ZSHAREDCURRENT_V            1057
#define IDC_ZSHAREDLIMIT_V              1058
#define IDC_GPUNAME                     1076
#define IDC_GPU_L                       1077
#define IDC_DEDICATED_L                 1078
#define IDC_SHARED_L                    1079
#define IDC_GPULIST                     1093
#define IDC_POWER_USAGE_L               1094
#define IDC_TEMPERATURE_L               1095
#define IDC_FAN_RPM_L                   1096
#define IDD_DEVICE_GENERAL              1100
#define IDC_DEVICE_INFO                 1101
#define IDC_DEVICE_ICON                 1102
#define IDC_DEVICE_GROUPBOX             1103
#define IDC_DEVICE_NAME                 1104
#define IDC_DEVICE_MANUFACTURER         1105
#define IDD_DEVICE_PROPERTIES           1106
#define IDC_DEVICE_PROPERTIES_LIST      1107
#define IDD_DEVICE_INTERFACES           1108
#define IDC_DEVICE_INTERFACES_INFO      1109
#define IDD_DEVICE_RESOURCES            1110
#define IDC_DEVICE_RESOURCES_INFO       1111
#define IDS_HD_NO_GRAPHICS_NODES        12000
#define IDS_HD_CONNECTED                12001
#define IDS_HD_DISCONNECTED             12002
#define IDS_HD_ADAPTER                  12003
#define IDS_HD_UNICAST                  12004
#define IDS_HD_BROADCAST                12005
#define IDS_HD_MULTICAST                12006
#define IDS_HD_ERRORS                   12007
#define IDS_HD_UNKNOWN_NETWORK_ADAPTER  12008
#define IDS_HD_DESCRIPTION              12009
#define IDS_HD_INSTALLED                12010
#define IDS_HD_FIRST_INSTALLED          12011
#define IDS_HD_LAST_ARRIVAL             12012
#define IDS_HD_LAST_REMOVAL             12013
#define IDS_HD_PROBLEM_CODE             12014
#define IDS_HD_PROBLEM_DESCRIPTION      12015
#define IDS_HD_PROBLEM_STATUS           12016
#define IDS_HD_DRIVER                   12017
#define IDS_HD_DRIVER_PROVIDER          12018
#define IDS_HD_DRIVER_DESCRIPTION       12019
#define IDS_HD_DRIVER_DATE              12020
#define IDS_HD_DRIVER_VERSION           12021
#define IDS_HD_DRIVER_INF               12022
#define IDS_HD_DRIVER_INF_SECTION       12023
#define IDS_HD_SERVICE                  12024
#define IDS_HD_SECURITY_DESCRIPTOR      12025
#define IDS_HD_ENUMERATOR               12026
#define IDS_HD_PDO_NAME                 12027
#define IDS_HD_INSTANCE_ID              12028
#define IDS_HD_PARENT_INSTANCE_ID       12029
#define IDS_HD_LOCATION_INFO            12030
#define IDS_HD_LOCATION_PATHS           12031
#define IDS_HD_MATCHING_ID              12032
#define IDS_HD_HARDWARE_IDS             12033
#define IDS_HD_NAME                     12034
#define IDS_HD_GUID                     12035
#define IDS_HD_DEVICE_NAME              12036
#define IDS_HD_CLASS_NAME               12037
#define IDS_HD_INSTALLER                12038
#define IDS_HD_DEFAULT_SERVICE          12039
#define IDS_HD_PROPERTY_PAGE_PROVIDER   12040
#define IDS_HD_STATE                    12041
#define IDS_HD_IPV4_ADDRESS             12042
#define IDS_HD_IPV4_SUBNET_MASK         12043
#define IDS_HD_IPV4_DEFAULT_GATEWAY     12044
#define IDS_HD_IPV4_DNS_ADDRESS         12045
#define IDS_HD_IPV6_ADDRESS             12046
#define IDS_HD_IPV6_TEMP_ADDRESS        12047
#define IDS_HD_IPV6_DEFAULT_GATEWAY     12048
#define IDS_HD_IPV6_DNS_ADDRESS         12049
#define IDS_HD_DOMAIN                   12050
#define IDS_HD_LINK_SPEED               12051
#define IDS_HD_SENT                     12052
#define IDS_HD_RECEIVED                 12053
#define IDS_HD_TOTAL                    12054
#define IDS_HD_SENDING                  12055
#define IDS_HD_RECEIVING                12056
#define IDS_HD_UTILIZATION              12057
#define IDS_HD_SENT_PACKETS             12058
#define IDS_HD_RECEIVED_PACKETS         12059
#define IDS_HD_TOTAL_PACKETS            12060
#define IDS_HD_SEND_ERRORS              12061
#define IDS_HD_RECEIVE_ERRORS           12062
#define IDS_HD_TOTAL_ERRORS             12063
#define IDS_HD_SEND_DISCARDS            12064
#define IDS_HD_RECEIVE_DISCARDS         12065
#define IDS_HD_TOTAL_DISCARDS           12066
#define IDS_HD_PERCENT_FORMAT           12067
#define IDS_HD_MILLISECONDS_FORMAT      12068
#define IDS_HD_RATE_FORMAT              12069
#define IDS_HD_QUEUE_DEPTH_FORMAT       12070
#define IDS_HD_VOLUME_FORMAT            12071
#define IDS_HD_VOLUME_LABEL_FORMAT      12072
#define IDS_HD_CLOSE                    12073
#define IDS_HD_NOT_AVAILABLE            12074
#define IDS_HD_PENDING                  12075
#define IDS_HD_UNKNOWN                  12076
#define IDS_HD_UNNAMED_DEVICE           12077
#define IDS_HD_MILLISECONDS_SUFFIX      12078
#define IDS_HD_RATE_SUFFIX              12079
#define IDS_HD_QUEUE_SEPARATOR          12080
#define IDS_HD_RATE_WITH_BITRATE_FORMAT 12081
#define IDS_HD_PRECISE_PERCENT_FORMAT   12082
#define IDS_HD_SECONDS_FORMAT           12083
#define IDS_HD_UINT64_RANGE_FORMAT      12084
#define IDS_HD_MEGAHERTZ_FORMAT         12085
#define IDS_HD_INTEGER_PERCENT_FORMAT   12086
#define IDS_HD_VERSION_FORMAT           12087
#define IDS_HD_CELSIUS_FORMAT           12088
#define IDS_HD_SIZE_PERCENT_FORMAT      12089
#define IDS_HD_HEX_FORMAT               12090
#define IDS_HD_WDDM_VERSION_FORMAT      12091
#define IDS_HD_FILE_SYSTEM_NTFS         12092
#define IDS_HD_FILE_SYSTEM_FAT          12093
#define IDS_HD_FILE_SYSTEM_REFS         12094
#define IDS_HD_RAPL                     12095
#define IDS_HD_GROUP_GENERAL            12096
#define IDS_HD_GROUP_CLASS              12097
#define IDS_HD_OPTIONS_DISK_DEVICES     12098
#define IDS_HD_OPTIONS_GRAPHICS_DEVICES 12099
#define IDS_HD_OPTIONS_NETWORK_DEVICES  12100
#define IDS_HD_OPTIONS_RAPL_DEVICES     12101
#define IDS_HD_VALUE                       12102
#define IDS_HD_MENU_COPY_ACCELERATOR       12103
#define IDS_HD_MENU_ENABLE                 12104
#define IDS_HD_MENU_DISABLE                12105
#define IDS_HD_MENU_RESTART                12106
#define IDS_HD_MENU_UNINSTALL              12107
#define IDS_HD_RESOURCE_TYPE               12108
#define IDS_HD_SETTING                     12109
#define IDS_HD_MENU_GO_TO_SERVICE          12110
#define IDS_HD_MENU_SEARCH_ONLINE          12111
#define IDS_HD_MENU_SEARCH_DRIVER_UPDATE   12112
#define IDS_HD_MENU_OPEN_KEY               12113
#define IDS_HD_MENU_HARDWARE               12114
#define IDS_HD_MENU_SOFTWARE               12115
#define IDS_HD_MENU_USER                   12116
#define IDS_HD_MENU_CONFIG                 12117
#define IDS_HD_MENU_PROPERTIES             12118
#define IDS_HD_MENU_COPY                   12119
#define IDS_HD_MENU_DEVICES                12120
#define IDS_HD_VOLUME_CREATION_TIME        12121
#define IDS_HD_VOLUME_SERIAL_NUMBER        12122
#define IDS_HD_VOLUME_UNIQUE_IDENTIFIER    12123
#define IDS_HD_VOLUME_PARTITION_IDENTIFIERS 12124
#define IDS_HD_VOLUME_FILE_SYSTEM          12125
#define IDS_HD_VOLUME_VERSION              12126
#define IDS_HD_LFS_VERSION                 12127
#define IDS_HD_TOTAL_SIZE                  12128
#define IDS_HD_TOTAL_FREE                  12129
#define IDS_HD_TOTAL_USED                  12130
#define IDS_HD_TOTAL_SECTORS               12131
#define IDS_HD_TOTAL_CLUSTERS              12132
#define IDS_HD_FREE_CLUSTERS               12133
#define IDS_HD_RESERVED_CLUSTERS           12134
#define IDS_HD_BYTES_PER_SECTOR            12135
#define IDS_HD_BYTES_PER_CLUSTER           12136
#define IDS_HD_BYTES_PER_FILE_RECORD_SEGMENT 12137
#define IDS_HD_CLUSTERS_PER_FILE_RECORD_SEGMENT 12138
#define IDS_HD_MFT_RECORDS                 12139
#define IDS_HD_MFT_SIZE                    12140
#define IDS_HD_MFT_START                   12141
#define IDS_HD_MFT_ZONE_CLUSTERS           12142
#define IDS_HD_MFT_ZONE_SIZE               12143
#define IDS_HD_MFT_MIRROR_START            12144
#define IDS_HD_FILE_READS                  12145
#define IDS_HD_FILE_WRITES                 12146
#define IDS_HD_DISK_READS                  12147
#define IDS_HD_DISK_WRITES                 12148
#define IDS_HD_FILE_READ_BYTES             12149
#define IDS_HD_FILE_WRITE_BYTES            12150
#define IDS_HD_METADATA_READS              12151
#define IDS_HD_METADATA_WRITES             12152
#define IDS_HD_METADATA_DISK_READS         12153
#define IDS_HD_METADATA_DISK_WRITES        12154
#define IDS_HD_METADATA_READ_BYTES         12155
#define IDS_HD_METADATA_WRITE_BYTES        12156
#define IDS_HD_MFT_READS                   12157
#define IDS_HD_MFT_WRITES                  12158
#define IDS_HD_MFT_READ_BYTES              12159
#define IDS_HD_MFT_WRITE_BYTES             12160
#define IDS_HD_EXCEPTIONS                  12161
#define IDS_HD_RESOURCES_EXHAUSTED         12162
#define IDS_HD_VOLUME_TRIM_COUNT           12163
#define IDS_HD_VOLUME_TRIM_TIME            12164
#define IDS_HD_VOLUME_TRIM_BYTES           12165
#define IDS_HD_VOLUME_TRIM_SKIPPED_COUNT   12166
#define IDS_HD_VOLUME_TRIM_SKIPPED_BYTES   12167
#define IDS_HD_FILE_TRIM_COUNT             12168
#define IDS_HD_FILE_TRIM_TIME              12169
#define IDS_HD_FILE_TRIM_BYTES             12170
#define IDS_HD_PROPERTY                    12171
#define IDS_HD_BEST                        12172
#define IDS_HD_RAW                         12173
#define IDS_HD_RAW_HEX                     12174
#define IDS_HD_UNABLE_CREATE_WINDOW        12175
#define IDS_HD_DISK_DRIVES                 12176
#define IDS_HD_PHYSICAL_LOCATION           12177
#define IDS_HD_DRIVER_DATE_TITLE           12178
#define IDS_HD_DRIVER_VERSION_TITLE        12179
#define IDS_HD_WDDM_VERSION_TITLE          12180
#define IDS_HD_VENDOR_ID                   12181
#define IDS_HD_DEVICE_ID                   12182
#define IDS_HD_TOTAL_MEMORY                12183
#define IDS_HD_RESERVED_MEMORY             12184
#define IDS_HD_GPU_FREQUENCY               12185
#define IDS_HD_MAX_GPU_FREQUENCY           12186
#define IDS_HD_MEMORY_FREQUENCY            12187
#define IDS_HD_MEMORY_BANDWIDTH            12188
#define IDS_HD_PCIE_BANDWIDTH              12189
#define IDS_HD_FAN_RPM                     12190
#define IDS_HD_POWER_USAGE                 12191
#define IDS_HD_TEMPERATURE                 12192
#define IDS_HD_FAILED_CHANGE_DEVICE_STATE  12193
#define IDS_HD_FAILED_RESTART_DEVICE       12194
#define IDS_HD_FAILED_UNINSTALL_DEVICE     12195
#define IDS_HD_MENU_SECURITY               12196
#define IDS_HD_NETWORK_ADAPTERS            12197
#define IDS_HD_RAPL_DRIVES                 12198
#define IDS_HD_FIRST                    IDS_HD_NO_GRAPHICS_NODES
#define IDS_HD_LAST                     IDS_HD_RAPL_DRIVES

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           12199
#endif
#endif
