//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Updater.rc
//
#define IDD_OPTIONS                     101
#define IDD_TEXT                        102
#define IDC_AUTOCHECKBOX                1001
#define IDC_TEXT                        1002
#define IDC_COMMITS                     1003
#define IDC_TEXT2                       1003
#define IDC_SHOWSTARTPROMPTCHECK        1004
#define IDC_SKIPWELCOMEPAGECHECK        1005
#define IDC_SHOWUPDATENOTIFICATION      1007
#define IDC_UPDATE_INTERVAL             1008
#define IDS_UP_UNABLE_EXECUTE_SETUP     12000
#define IDS_UP_INTERVAL_ONE_DAY         12001
#define IDS_UP_INTERVAL_ONE_WEEK        12002
#define IDS_UP_INTERVAL_ONE_MONTH       12003
#define IDS_UP_LAST_UPDATE_CHECK_FORMAT 12004
#define IDS_UP_NEXT_UPDATE_CHECK_RELATIVE_FORMAT 12005
#define IDS_UP_NEXT_UPDATE_CHECK_FORMAT 12006
#define IDS_UP_NEW_VERSION_AVAILABLE    12007
#define IDS_UP_CHECK_FOR_UPDATES        12008
#define IDS_UP_OPTIONS_SECTION          12009
#define IDS_UP_BUTTON_CHECK             12010
#define IDS_UP_CHANNEL_STABLE_RECOMMENDED 12011
#define IDS_UP_CHANNEL_CANARY_PREVIEW   12012
#define IDS_UP_BUTTON_DOWNLOAD          12013
#define IDS_UP_AVAILABLE_DETAILS_FORMAT 12014
#define IDS_UP_BUTTON_INSTALL           12015
#define IDS_UP_DOWNLOADING_CHANNEL_FORMAT 12016
#define IDS_UP_DOWNLOADING_UPDATE_FORMAT 12017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           12018
#endif
#endif
